---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.17.3
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system

  maxHistory: 5
  install:
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    prometheus:
      enable: true
      scrapeInterval: 30s
    master:
      replicaCount: 1
    worker:
      config:
        core:
          labelSources:
            - cpu
            - pci
            - system
            - usb
