---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres15
spec:
  instances: 3 # set to the number of nodes in the cluster
  imageName: ghcr.io/cloudnative-pg/postgresql:15.8
  primaryUpdateStrategy: unsupervised

  storage:
    size: 20Gi
    storageClass: openebs-hostpath

  superuserSecret:
    name: postgres-superuser

  enableSuperuserAccess: true

  resources:
    requests:
      cpu: 500m
    limits:
      memory: 4Gi

  postgresql:
    parameters:
      max_connections: "600"
      max_slot_wal_keep_size: 20GB
      shared_buffers: 512MB
      timezone: ${CLUSTER_TIMEZONE}

  monitoring:
    enablePodMonitor: true
    # Ref: https://github.com/cloudnative-pg/cloudnative-pg/issues/2501
    podMonitorMetricRelabelings:
      - { sourceLabels: ["cluster"], targetLabel: cnpg_cluster, action: replace }
      - { regex: cluster, action: labeldrop }

  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://postgresql/
      endpointURL: http://minio.minio.svc.cluster.local:9000
      serverName: postgres15-v1
      s3Credentials:
        accessKeyId:
          name: postgres-minio-secret
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: postgres-minio-secret
          key: MINIO_SECRET_KEY

  bootstrap:
    pg_basebackup:
      source: postgres14
  externalClusters:
  #   - name: *previous-cluster
  #     barmanObjectStore:
  #       wal:
  #         compression: bzip2
  #         maxParallel: 8
  #       destinationPath: s3://postgresql/
  #       endpointURL: http://minio.minio.svc.cluster.local:9000
  #       serverName: postgres-v3
  #       s3Credentials:
  #         accessKeyId:
  #           name: postgres-minio-secret
  #           key: MINIO_ACCESS_KEY
  #         secretAccessKey:
  #           name: postgres-minio-secret
  #           key: MINIO_SECRET_KEY

  # this represents an existing cnpg cluster to migrate from (e.g. upgrading from postgres v14 to postgres v15)
  - name: postgres14
    connectionParameters:
      host: postgres14-rw.database.svc.cluster.local
      user: postgres
      dbname: postgres
      sslmode: require
    password:
      name: postgres-superuser
      key: password
