apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: home-ops-db-superuser
data:
    username: ENC[AES256_GCM,data:hEbS+CZG3g0+TlTRy+sVfB1Ak24pqxavfQ==,iv:1GM0+24qA43haR8ZefbtHL4yxXIdbS53sqW48HUgBQ4=,tag:Cz4q6JxhFbAhukh6ZQMDdg==,type:str]
    password: ENC[AES256_GCM,data:oJm4Ue43MiSwcbgh6pO5qfF0rL7d+uFusg==,iv:6k75lPyEgnMdIFB31Q5NBBh9uQOeoz5H4bjUmcFe16k=,tag:5Gvgo4E7doSalcM9vVCujQ==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T19:18:30Z"
    mac: ENC[AES256_GCM,data:kou0GfE9D+YqQHOap17eUQK9V0Ci5+ScRJXwR5NUIlPHYR19B4nBeKMPu9JwmSMhDDqCfzjVAg8h6BcwingH6WhQE4IMLJp70p5tSWbvVFZvcEyumlRYldH/A5S81dTC9U76t78vdUlTrI8c6TlRp07e2tWdlmYQgtU8UYMS5XQ=,iv:x0yR1XOiDAe9Zyqys6ZVQcVdH2exoyzn0qGUxF6CW4Y=,tag:EPNtgDbl0mimyEXwQjIkxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: home-ops-db-garage-secret
stringData:
    AWS_ACCESS_KEY: ENC[AES256_GCM,data:ezZJG5QusGicLrPjnXDZu9oBDw77OYouuqQ=,iv:lKNoE7hvrt8slVLafHO15H/9JFOf1GQSLOVKBbOoz6g=,tag:sT2xNQ/CY4ohj3Z1n46PJw==,type:str]
    AWS_SECRET_KEY: ENC[AES256_GCM,data:z8U6lg/BfoSWlaZEOt/vzS0wDRwf3kiFe/hS6ybMLLJVXOMTVjZnJKpDuzWl04+B4HC4wfnwbmSBlyQ853Gnpg==,iv:CGAl32GL3cz+mY0bzuVPjXsXF9YpMxF2+R0EEOwnspc=,tag:ME+HIVg6UJQ8YXHvkQsMpw==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T19:18:30Z"
    mac: ENC[AES256_GCM,data:kou0GfE9D+YqQHOap17eUQK9V0Ci5+ScRJXwR5NUIlPHYR19B4nBeKMPu9JwmSMhDDqCfzjVAg8h6BcwingH6WhQE4IMLJp70p5tSWbvVFZvcEyumlRYldH/A5S81dTC9U76t78vdUlTrI8c6TlRp07e2tWdlmYQgtU8UYMS5XQ=,iv:x0yR1XOiDAe9Zyqys6ZVQcVdH2exoyzn0qGUxF6CW4Y=,tag:EPNtgDbl0mimyEXwQjIkxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
