---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app garage
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: garage
  maxHistory: 5

  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    controllers:
      garage:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/dxflrs/garage
              tag: v2.3.0@sha256:866bd13ed2038ba7e7190e840482bc27234c4afaf77be8cfa439ae088c1e4690

            envFrom:
              - secretRef:
                  name: garage-secret

            env:
              TZ: ${TIMEZONE}

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: [ALL]}

            resources:
              requests:
                cpu: 100m
              limits:
                memory: 512Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1504
        runAsGroup: 1504
        fsGroup: 1504
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
        seccompProfile: {type: RuntimeDefault}

    service:
      app:
        ports:
          s3:
            port: &port 3900
          api:
            port: 3903

    persistence:
      config:
        enabled: true
        type: configMap
        name: garage-configmap
        globalMounts:
          - path: /etc/garage.toml
            subPath: configuration.toml
      data:
        existingClaim: garage-data-pvc
        globalMounts:
          - path: /data
      meta:
        existingClaim: garage-meta-pvc
        globalMounts:
          - path: /meta