apiVersion: v1
kind: Secret
metadata:
    name: garage-secret
    namespace: storage
stringData:
    GARAGE_RPC_SECRET: ENC[AES256_GCM,data:3grDfoZKiKjbZP+xeqgmDj21Gg/iI4w7S4a8v9ul+AY7lgy8sIiHoZH7w2kIFHA/PY2e23DIgXEioEBzm2r5mw==,iv:MTlEjK6Mxb2voSZ8rkXVdnsHI5EkQr/m5RFE4rez4gg=,tag:pRJZy9G3RULG+KhzrngxXA==,type:str]
    GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:asZ4i0BVwIYE0GEVlj95ygNaBgA4w0OsnifQ1cAu5YmJLN6icvJhfEmoGtg=,iv:yD6V7e4LRca25EEMVMRWcUkG0DD6lyTubNdNyR6FMNQ=,tag:pbjY4RvqOwRi43Dzde7Bxg==,type:str]
    GARAGE_METRICS_TOKEN: ENC[AES256_GCM,data:V1kactlwjBmoTrvLjogR8E4i816ofLEnPtpMyBRsGMdPuBv3n0GAcFth5Gw=,iv:DGQNnqerinAOiRm/+yiv9NEMQq4t29JTPc84EHcQXMc=,tag:S2Q8mXPGJ/ZD+x+4ib1M8g==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T22:15:45Z"
    mac: ENC[AES256_GCM,data:noqd8Jo6QIC92FruwgSrzPglEMcjQivyuQeRgQcMamjDxmLFBSqwlFNLWTnQxG7WXKPqTmDpyHM3eWIumaGN5CLM1Fy2U2j8UjKzVU0F4nmJL0YA3QitC7IEN0r+Ln2hEKiCvcknO1uRwfwXlO7iQhwLmpzaxtC1E2ZbYLJCG3w=,iv:s0vb/UtRZ2ngTB8+/mU8A/0q7hXZMurVEbTQV53bXSM=,tag:HhgRjSai8ZsLOWtnaaUZjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
