---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mealie
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    createNamespace: false
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    controllers:
      mealie:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          enableServiceLinks: false

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: "16.3"
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: mealie-init-db

        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v2.4.1
              pullPolicy: IfNotPresent

            env:
              TZ: ${CLUSTER_TIMEZONE}
              BASE_URL: https://reshipi.${SECRET_DOMAIN}
              ALLOW_SIGNUP: "false"
              API_DOCS: false
              API_PORT: "9000"
              DB_ENGINE: postgres
              OIDC_PROVIDER_NAME: Authentik
              OIDC_AUTH_ENABLED: true
              OIDC_SIGNUP_ENABLED: true
              OIDC_AUTO_REDIRECT: true
              OIDC_REMEMBER_ME: true
              PUID: 1000
              PGID: 1000
            envFrom:
              - secretRef:
                  name: mealie-secret

            resources:
              requests:
                cpu: 5m
                memory: 256Mi
              limits:
                memory: 512Mi

    service:
      app:
        controller: mealie
        ports:
          http:
            port: 9000

    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          mealie:
            app:
              - path: /app/data
