apiVersion: v1
kind: Secret
metadata:
    name: mealie-secret
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:ooKTvXuEvsFl7U0H,iv:R74RDGOHAeDY77PhCQJrh1aSneTk3sAXvyz1t13pv/o=,tag:+z9+wAXLSsieaeFc2i1y4Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:HRH4A8HTTvbe5cPizeetUSeMVrWt7cGk0Qyv,iv:Au1mJdmi8sAoSDjG8ULBHj2A3JBPEgrDten4pUM7MIA=,tag:x5nh036dJEPrEN73pkNpYQ==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:KAgZuOycSwo2O04WhstpGXAhhg==,iv:M/3HQksGmLwuNnLv5Trprjl9tR0ZqdM5X/7C8GZSfdE=,tag:vDQDT383AFLDpmv+A4/Xbg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Y/OKbpDB,iv:7owaVXxg+V/Bz/r8By8CmD9eTt3kxNm9EApDCWL1124=,tag:gWjJrnb+YZmz7MlvwL8Twg==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:SbqjozgO7mhbn4/PldB6CksCU1nCMNaUElGnC7IiJQWKjmFYbw==,iv:thwPS5NCliSgxPZ4lldzepWa5uQSjS2rO7av1HvWi1I=,tag:W4klc481wjGpy55RlVbV7Q==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:5Og=,iv:XHk8etasZOucX0UiENfMlM1e2Okwc/z6fbXMx7Pa1h8=,tag:CsKbl/+3ngY/GoN5lCaKiw==,type:str]
    SMTP_FROM_EMAIL: ENC[AES256_GCM,data:un4Y7ymW2pF/XaepLR5I7mVAq3owMOZjsaY=,iv:wEU90l4FWQYIg5H874Ulty8PDre5IREqBmv9CaSBqlU=,tag:8vq4ynDtYWbMsXftEhI71w==,type:str]
    SMTP_FROM_NAME: ENC[AES256_GCM,data:PIGHQtZ9,iv:2jNPm4ejwUC4Odylt/SiwEReL0sqwVhmBiN+exWjmNI=,tag:RErXLnqV5VPLF6Ghs7Ga/w==,type:str]
    SMTP_AUTH_STRATEGY: ENC[AES256_GCM,data:DOvcSg==,iv:CcxyZ4MEMa8j8jxHlVO9nns9HX1EwkwMfHrz2/rLQSM=,tag:rF3IGZyE7Tb1oGRdsEkG3Q==,type:str]
    OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:65mWjbl6lI3n+tTwvRQIQf6+JqatzOcbhxwlFlh3IG1n4XoTQKhd2I+QRZBHoD4YMKs8gGlfVMYr44/uojf7BVSJR2bGl7+viSnBO4zrSlUTTFs=,iv:HrCqU6pDnbJqOnivAbd857D9C0j8TYYkODtcj4CSD8Y=,tag:NI2IF8Sk74yvu9MzLm2TqQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:jth3noEA/GuUsmDWQnJ6dX4mK8lyMzGPysT6h7GVwfsqsP0wEQDe+w==,iv:m1Pz5R2KhuDC2HZ21IYl2UkyvfqRdDxLXGBRpa44iZ8=,tag:8lwbqxM2PZmfGzDjbPoyyQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:lRpglMmuqAzupgZg8etZH7n7uZRfLbplIaNsoXLTid4Q4AfnqzJg25q8KTcsj/fup02XlVElJ6Fxj8v6U7JaNOOZv0/eexWWu9Fml6sH8BMHvo6eMXzun3ehAfI9h4Zl9/wmL1aPbj327rBdmPuq4ToqFVLBVxXs1oShqRnVXdI=,iv:m815UZcN/+t9qr/a/4wu0V6g+4Uw0Se2nA2hPY5yyzg=,tag:h4yLhMOph4m96XIa7rIZgg==,type:str]
    OIDC_SIGNING_ALGORITHM: ENC[AES256_GCM,data:XJvEWKM=,iv:CobEfYa1O5LKjl50GtY7Ifcgt8qYBnjA19yHbewTF6s=,tag:lu6GvSsyXCVtK1XS2Jip7Q==,type:str]
    OIDC_USER_GROUP: ENC[AES256_GCM,data:+8EgNVOxnIlSKZ+4,iv:UUeMG5TmrOOo1iZyPB8oxsolTt/pi/PQjLiYLhdXRLw=,tag:hswk6V9ssqwl6p220SETpQ==,type:str]
    OIDC_ADMIN_GROUP: ENC[AES256_GCM,data:dKjDEMrX+mykPIFTvQ==,iv:nGE2Aaa23s3ltN4DTDeoiyWcVsAFEbWQ82VHRjjHETw=,tag:kBz+dWmxktsw6mQYU1L4Rw==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T20:54:06Z"
    mac: ENC[AES256_GCM,data:6uRygWxJS1sj7WQOByY964jitDXzwMxSb7kzDway7R6wRg7wp6BpjWp+aWyjByqsYgBKWHwIbC/TNhjduHePdPdJuFQ8le24KL/eHLdReaO+ikMCNK3gzawfUKyNHUNrdzdU1PRqhus3Gdqb15D8c63oH1/gh7zRp/HGlxCYLXk=,iv:vwXt220rW2socQKzLJb0nUqvFTJCZY9gVg+XiMnWysw=,tag:l92uIB+uSpH6fTOPzIIv/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: mealie-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:R6V8HIF+pVo=,iv:3Ma3JNogEXYGq3XVEQi0MotgPgCVQaCmk0xUOeVTV/0=,tag:EmmR0XAnVvQgU7b/ak6htQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:s4DqHCDX+Wuijm5iZP6f6yw5pAlITwe9t+OgPX5twGMLJTDfGoh8Pq3YMvxQ2luBiO6Ur8g+hH8=,iv:2+8Kg1tS/IOYqcleAmYi+cZ3OjrDyIAOFSXVB9L8TtU=,tag:maqIAjFAHpbLz0Oft64GpA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:cO6/eAyvVLxddokE5FO1aw==,iv:iMhbCG2NY2CKQqBAMsd8FERkKuBwHfup+pR5/jDpnDw=,tag:pnKcmH1NTr9SP45/uau1Kw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:UDm+/L4vAnRb938SvoIlsVQurg6xRmWGWhoLICcTf/pw18Jg,iv:mYRaObqdNnNgXkqwcJAUYgFzZqML3fB6t6EtVdi7k78=,tag:XznZBExDFUk7pOYXEtnIdg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pFwxhGOwHKAu2xIyBftXJX/vVh2j2ZP9LA==,iv:yu6KuqH2ptJ+SYum+MVAdH0EYGNRDml3ZXxEivJXl58=,tag:IrJxPc2sWt01Y3ZRZdlmUg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T20:54:06Z"
    mac: ENC[AES256_GCM,data:6uRygWxJS1sj7WQOByY964jitDXzwMxSb7kzDway7R6wRg7wp6BpjWp+aWyjByqsYgBKWHwIbC/TNhjduHePdPdJuFQ8le24KL/eHLdReaO+ikMCNK3gzawfUKyNHUNrdzdU1PRqhus3Gdqb15D8c63oH1/gh7zRp/HGlxCYLXk=,iv:vwXt220rW2socQKzLJb0nUqvFTJCZY9gVg+XiMnWysw=,tag:l92uIB+uSpH6fTOPzIIv/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
