apiVersion: v1
kind: Secret
metadata:
    name: monica-db-secrets
    namespace: monica
type: Opaque
stringData:
    #ENC[AES256_GCM,data:0zg=,iv:jjsUOvc+W0Jzsf3kaeP8XG/+OqN0JUnDl0ZCjhQc8xg=,tag:NHUfpNrgZ+/2YHZpAIEDsA==,type:comment]
    mariadb-root-password: ENC[AES256_GCM,data:EKtKinKPmSQkttJ+HyEJB/bZXRvtiDaNdQ==,iv:LAI5S1YRwOoSiTuA7IiuadNVLeigQ0gjZx3BMqJ38e8=,tag:REPXUEYMygdHs0xPZR2LkQ==,type:str]
    database: ENC[AES256_GCM,data:l7hh9Zkxeu+r,iv:2VGt89Gi2zjnRBJNOlH7eCD2SLSEP1eeBzbXEg0jEcE=,tag:hHx3trtY6u4N8VrhRKW+RQ==,type:str]
    username: ENC[AES256_GCM,data:Q07YgzQ2pTKlIYMN+HD5HgE=,iv:/YWqrVUEBrCVsthrdyahzaaCwiAUFREmUE+n2DKvjsQ=,tag:tzHy5RaRR5+PQsU1EzME/A==,type:str]
    mariadb-password: ENC[AES256_GCM,data:CfTk2JiNJjGqKvfYZX3VIbnd2K2Y97LIvw==,iv:fjMHJ5RpOYTeTSIJDaAkMuznu5ryYG6iVj3BjtmkBOw=,tag:9xU9PyYoMwYCJq6mv10e/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T15:18:03Z"
    mac: ENC[AES256_GCM,data:slTWkChPV3o5YTA5XW6A0aMFUMC4jRUt0TC/ZvhISLjbm3MDS85R/wJAjSykeUsBXzfYxOkV+VEaUTHbMX6EP2hvwJsfPw5Z2BmOQW30qxLjAnn+X2zB+O7uGxAQ5CrdKuYYS1qXBqOAL6QT/EqYtP79BxwiteQJCJvgo5hML5g=,iv:QZI4jOymizbf3YtAi9r1Aa85w8oC4r5DesJP6VpTomQ=,tag:C0RH57uUfQZgvXznloP/Tw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
