apiVersion: v1
kind: Secret
metadata:
    name: minio-secrets
    namespace: minio
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:QZLYqjtFbWAsCQ7p,iv:5kBABOex58T8FvdPxsjITRx16b2lpxb6InqcqkB7fQM=,tag:4n0Q7ow5wk9WJ9g03oWwnA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:5pz5oVNqZ8TVwnypfCDMHIkp+uf4e31La5lr,iv:4JDzHD87dxBy5nMKTm2k01XcTR7vrbhGozULW2QK2Hw=,tag:VGmnDMMua1ZhgHmRCLzVAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T11:58:36Z"
    mac: ENC[AES256_GCM,data:jaP66tKDp/QCVNFA6x2oz9meqngyT7edtltlBvYJGAjFbFzk9Pl/SzLTDSEGWrDw2uqv+bwO5RBb5KtQzIlTbrOGNpWto5sxTIa7QY9Z/1HruEiNyyGkCt8WJdIh+7BVe2BCEJ6yMrO+ZaIgm512Ufn2bZXp7b0z4UPc444Lzxo=,iv:onwPz8wT/4jz+gjCHTpX9gDXulgqmRjiYVojkXY4unU=,tag:d6cDTm6isP6PVFRfaRquIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
