---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app smtp-relay
  namespace: flux-system
spec:
  targetNamespace: networking
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/networking/smtp-relay/app
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  prune: true
  wait: true
  interval: 30m
  retryInterval: 2m
  timeout: 5m

