apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:b/ENbPnf9mNgbDAcsNA9qZ/Ne1sPdLoVO1OJ7jzaPz+6TW/ZFT5C3e90WaMrkGdmehlVYWRImeJN2Xo=,iv:xYk5Hk4b9e54fdab6lSlyg5hdqVkeSwxTpC4i8V4DZk=,tag:60aKShPNkBLygyqTX9ur+w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:ciB6vxfD0c4dX8SEZnJSCzxHffvpv+t0qeU=,iv:PXt2tbb3wZl003PkaFvqIY6eqYHD9hXJNXNC0uWZQyU=,tag:v+p9MkzEnwVP3M3z2hARhQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:NetFIR4QRCxf6nPobJnSVNp0TjaPWTKx,iv:A7JVlhIpD86nUfQ+9bhDJ2jZBgPU5rJU5HUuuxe890o=,tag:/TJBHlSjaglIBA2JYi7C7Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9zZNEjynbs1pn8Y5u+b11NTWdnqTWVVe7XvDgw==,iv:bOPNemcRQbQKcxeIC62FI4qCxKmbq1BZiSN4Ka7BdhY=,tag:4MHa7qQWMg96EKxjmCk+/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T12:29:21Z"
    mac: ENC[AES256_GCM,data:xFBNd3VzFYZprF5KyFBufc9icuAcEY4bI5mZEq4uOMgpXZ4K5Xk1mkhp7f35IbC/xL5bTc+9v4CGTLEJ0hubsuAD2CXP2rXasvOonDQVDjvqtiSj17S4XlPv064yd2Tlk2aFN7x/58iEu3KsANE5a8l2eMoTrHwQuIUbKbf0z9k=,iv:BglrVrF12yNonXZirWciVL/Z/FeKo2nCSJxzc03TafE=,tag:MzgfNk7eOl4Yo5dmoofUjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
