apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: media
stringData:
    #ENC[AES256_GCM,data:gGCadg==,iv:pu7F+RJvOSqbS+spF4Jwc6NMoyZIccudVvvwH53LQsI=,tag:uISTckSd4IQ+SpeZwT1lGA==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:ensWCbqbfQ76F3Xa0Ta12NHQ0ym2XtHg,iv:jEAHECg/TVwxczZwNMGKQiKkmR+VzhHpoAGV4S97cxs=,tag:/ScU/50fi+Hr2YYx9nNzbA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:P0Nz08UbwHq5Jwceem8knp5F9KWUdLR/PQ==,iv:4jSiAwhhaaXm4k+fSdQJnVP8HTY8237xfy30FW+H2Vo=,tag:QxSO6ODpY+2NnDoDhYzchw==,type:str]
    #ENC[AES256_GCM,data:e/TfZfixUEwP,iv:6roP8vGnMoSpXFEylH6K5jJ9IRAinunzdUx+Xec1XeQ=,tag:XMpUOJQPNfz5x3aPTr3ddA==,type:comment]
    DB_HOSTNAME: ENC[AES256_GCM,data:R7li10wRqwptYBELFVovnEGclIw=,iv:AO1PmgJusrKQIP6hEaHHmOzGyEs6TBsQVM9VnQPeRK0=,tag:yoTk03Q/a9+X3G5CfcFcyQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:cBr6rdBl+kIWkwMnoEVgsvShXtA=,iv:xiyy2hQ1HNYjNCKCh3dk7PlhBHJ0ar6YJGjAOR1WFp8=,tag:ACuy/VqNnyZ8HJdapGJOFA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:wfOS7NPaoifkeiPsaFA3s4bza0Q=,iv:gukRebpsLLXx9JTAhc9DQfVVCQXEbc9iuhaSDmxWwzo=,tag:wWlKrSacDKtcDFmyoYfRCA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:wOWeBGiCWlUWiMKZAEtfrFY8W8iFf2Gn,iv:ysejtygfFXaSYlk+GRPN6+tmxEKxR4uDi+C3IBynj44=,tag:2ZxGCPhHl/NpF1oMQWhz+g==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:VD9c8gHtXOPmk45AsuGv+v9OL9/+ng==,iv:7p43V2ILjibyNauX0S44ba+nnTkMLuRDtPaHetki9+g=,tag:mvwnEe2iKDyNklbvVLumVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhWZXZXU2tPcVhGUVFN
            MjhZWU51M3ltTDNJcGtXWSt4TjlGMmtaTkhzClQ0TU1ZTHYwcUE4d2FQeTZleTJU
            dFAzL0ZSQkJVZ0RiTDZuSlNuV09Qck0KLS0tIG5tWnBrYnpta2JMMjlvU3ZaZkVE
            aTJiVDQrNEFrcmphQllSemVoUW4wWmcKuYowXh/u9jhxhH2eJSk7x2UAsZi+jA2O
            nYMOTDdNIzuSsOI2969MCVdlLFyn8t6pxESDBPROsu4FegZrRveM6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T10:24:28Z"
    mac: ENC[AES256_GCM,data:OVkC+xowdPM2y9mYoJdunH+DkxWNxSe9VrMdhA6EqgPnpqR5WQlQTB9ugmW9+MWJXNHUEXjP8z16I+N6hz2hpVS4H0rSA7YdBsZ7skqk+wvhlyB4HcsuWWWTUv6bqGp5BNMKCp0mHhAYrpbTR6MuC2r4PfAFeC/DKbVoW6vrfJ4=,iv:0bubGl2MrYy4r3m7AH8v7RU0jYKCHTFJvsCIX3JcbY0=,tag:A1jIeT+14pF2c8axY2iZ7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
