apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: media
stringData:
    #ENC[AES256_GCM,data:hn1DRA==,iv:AN4lBHCOku4SkWImrA4nHiIEn3Le044A5MOA58gN8pc=,tag:wTyh3kuILzKa5UxGoNro8Q==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:e0X1464lhUiB0MNbvT1qF47gHMTVu956Ec1TB8BGuI4=,iv:H5QEXgEnTe+t7dOU2Bdjretnti0LlD5f59iOW8FSm94=,tag:K/AY8vGk7d8bJw3c2iHPlw==,type:str]
    #ENC[AES256_GCM,data:q9Z6BtF0YIca,iv:5adme6j3l9uJ+7MaANoEDdGMVbchmuogVDXxJSzaAT4=,tag:PUQtMkAZu2fNbaifTOGO4g==,type:comment]
    DB_HOSTNAME: ENC[AES256_GCM,data:xnm/sJiE/13JYvccXnHdyceN7Q==,iv:oF5ctSfAN1Occc4WoE9oggquG/5yXQdSVRJwc2GXo4w=,tag:BQCCtQrcE3podHpPNfF2ug==,type:str]
    DB_PORT: ENC[AES256_GCM,data:ZQuF3miYaks+wuwK4VWA8g==,iv:zDQCusj2pEPvCT3PYkZZXZgiif82xsfP4ZTiCRJmld4=,tag:9Pf/6QBNmhGT5Ch3tSIoHQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:PdTSJmE3uvSkX5O5,iv:Th3x220tOqcAYA5Sz6quazW40GvTlMBmdahn0eKeRIA=,tag:82A9Q3wzNMqeSGSgxcTiTA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:HzafvChpynW3L07q/IE4Qx+ciHizHSe7Z0dkRgZAsYs=,iv:Vv6iXs7XW20UPWti4WqHRapu5Y2KvvwdVt5hQBiSibQ=,tag:Yx+djpFXGGmLrOc86Qp76g==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:Q5bfX7q+,iv:NxfodDZs8gV/iByT8FKPwyi/riFfWBUhWyQ/hfzIvkg=,tag:zEHhP6elJc2MB9k1Iyi/Sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T21:23:44Z"
    mac: ENC[AES256_GCM,data:fnXi3q5VHLb1EYm2jw+Z3BzjFN6bn8BpRfIM0zD+2xcszSA07KhBCYE2/YQYai+nKzF6h29swePx268ZZuDDdrMT38f7HF9eLIA91SSaVm7c9DGNq9hQWudIZEMxax/uKQTJ7IYmJ1FxPFc8YYNCvNipqVBACslXFIegLwlAnXA=,iv:V9cpzOFk+q+etuT8uU5hbYx5nJ4+RUTg7X9v9K5xop0=,tag:wWQ1DvOiI7oKtk3EayTRnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:imw7Z4Qi4C4=,iv:so1UiPL16tUtyXQQzJRjW7jkWxEeuXvDJ2+TT8rOBxA=,tag:sLGW9I78wTwZ5cs/9JO6+w==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:EL8lWkV5fRR5csuUEZhC5OjFHvHftrbDmJLBKltbEoeX3X/l5GRnCtTjHD7Zx6Zyj5qCynVl/6w=,iv:9fsA72uFROTgJOW0WxCoCRkuipJOruLALcW2qEcOGUE=,tag:PNfXxnw29dKgnpfY0kUprg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:vElJSVAPG0dSuoSjaSUmgQ==,iv:fIs6Nnej3UwFJW54LG/Lg7esYdCQWB7EN1K70Q20wrQ=,tag:aTfvsyOloSrC6cD97HU6Yg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Zv2UrRDvIdBrKIdJu/OZxEjHJyXohPdymYT9MF7dRvcrhKODzQNiJZwsM+0=,iv:dyZDsTUs2kt1Ya+m+BrEcmVo8+EpGsy8m7Pc8OEGcnI=,tag:wK/k1RTzKx8LftHv9jLZhg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:/CkHY6zTAG75ivkV/pm0ONMvY0u35u9jMA==,iv:td9wNNe136PrYZNiHuOsG8usU14D25hmEikZ06poZD8=,tag:q+HVuy1joNEE5TAbrTv0fQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T21:23:44Z"
    mac: ENC[AES256_GCM,data:fnXi3q5VHLb1EYm2jw+Z3BzjFN6bn8BpRfIM0zD+2xcszSA07KhBCYE2/YQYai+nKzF6h29swePx268ZZuDDdrMT38f7HF9eLIA91SSaVm7c9DGNq9hQWudIZEMxax/uKQTJ7IYmJ1FxPFc8YYNCvNipqVBACslXFIegLwlAnXA=,iv:V9cpzOFk+q+etuT8uU5hbYx5nJ4+RUTg7X9v9K5xop0=,tag:wWQ1DvOiI7oKtk3EayTRnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
