---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app intel-device-plugin
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/kube-system/intel-device-plugin/operator
  dependsOn:
    - name: node-feature-discovery
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  prune: true
  wait: true
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app intel-device-plugin-gpu
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/kube-system/intel-device-plugin/gpu
  dependsOn:
    - name: intel-device-plugin
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  prune: true
  wait: true
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
