---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db18
spec:
  instances: 3 # set to the number of nodes in the cluster
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.3-1.1.1
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover

  storage:
    size: 10Gi
    storageClass: openebs-hostpath

  superuserSecret:
    name: immich-db-superuser

  enableSuperuserAccess: true

  resources:
    requests:
      cpu: 500m
    limits:
      memory: 2Gi

  postgresql:
    parameters:
      max_connections: "600"
      max_slot_wal_keep_size: 20GB
      shared_buffers: 512MB
      timezone: ${CLUSTER_TIMEZONE}
    shared_preload_libraries:
      - "vchord.so"

  monitoring:
    enablePodMonitor: true

  backup:
    volumeSnapshot:
      className: csi-ceph-blockpool
      snapshotOwnerReference: cluster

  plugins:
    - enabled: true
      isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters: &barmanParameters
        barmanObjectName: garage-immich-db
        serverName: immich-db18-v1

  bootstrap:
    initdb:
      database: app
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: app

  externalClusters:
    - name: source
      plugin:
        enabled: true
        isWALArchiver: false
        name: barman-cloud.cloudnative-pg.io
        parameters: *barmanParameters