apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: immich-db-superuser
data:
    username: ENC[AES256_GCM,data:hEbS+CZG3g0+TlTRy+sVfB1Ak24pqxavfQ==,iv:1GM0+24qA43haR8ZefbtHL4yxXIdbS53sqW48HUgBQ4=,tag:Cz4q6JxhFbAhukh6ZQMDdg==,type:str]
    password: ENC[AES256_GCM,data:C0MOaVHj+3d8VhA44qbGlgIdRhGEmbtiapG4Um9Td7/uRbV2ovPhobyc0Y0=,iv:yjKdutblve/Hw00r5LXQhMvKQCTtT4yIAl+aaNxCTEo=,tag:/hYJylc4UliWo9JaeEsFRg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T17:43:04Z"
    mac: ENC[AES256_GCM,data:sDnTX9+yvZ6jHQ2xY+483v4dGgJf4NtLHFEhrEELze0W+6DymXg/Ab8n5ClsIi44rmTnbNbPpTmpFZixBlJMsqUHJV1VIJxmlg9O+4lhdjCimJOnZC72UDcHd/bXq8qAnJ93gncpu3sotNwW1R0Cwcf3svarWk1rdOLTTem71SM=,iv:C4MYIJneKFY+1nW0+XEHSVncutHBlLXLA87unwG2ohg=,tag:U1ZYbG88PMc4A9IKJXnBSw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: immich-db-garage-secret
stringData:
    AWS_ACCESS_KEY: ENC[AES256_GCM,data:zQ9NkDH+J9GMFZpGVRLJA+sgbBogPxonWRY=,iv:QttoFyBid9QNZiGTmZhWaVnDfnLBkzydl5fzJWGelBs=,tag:ib55R1O/6MZTWlwyVVvmfQ==,type:str]
    AWS_SECRET_KEY: ENC[AES256_GCM,data:iUCbsFez2z66rdbOFWAuISZkEIKPNIiAcy6tYrR1rI1716UKUCsF69q0PLXkVgGEkR8nm16W3yECjTnyqCiRFQ==,iv:FTldWMm/VKx9tcQG5IaflOS3Wvx+v0fmRmDApcnxqI0=,tag:PyDuI5Q04mVRGgTKpwPSqQ==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T17:43:04Z"
    mac: ENC[AES256_GCM,data:sDnTX9+yvZ6jHQ2xY+483v4dGgJf4NtLHFEhrEELze0W+6DymXg/Ab8n5ClsIi44rmTnbNbPpTmpFZixBlJMsqUHJV1VIJxmlg9O+4lhdjCimJOnZC72UDcHd/bXq8qAnJ93gncpu3sotNwW1R0Cwcf3svarWk1rdOLTTem71SM=,iv:C4MYIJneKFY+1nW0+XEHSVncutHBlLXLA87unwG2ohg=,tag:U1ZYbG88PMc4A9IKJXnBSw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
