apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: immich-db-superuser
data:
    username: ENC[AES256_GCM,data:hEbS+CZG3g0+TlTRy+sVfB1Ak24pqxavfQ==,iv:1GM0+24qA43haR8ZefbtHL4yxXIdbS53sqW48HUgBQ4=,tag:Cz4q6JxhFbAhukh6ZQMDdg==,type:str]
    password: ENC[AES256_GCM,data:C0MOaVHj+3d8VhA44qbGlgIdRhGEmbtiapG4Um9Td7/uRbV2ovPhobyc0Y0=,iv:yjKdutblve/Hw00r5LXQhMvKQCTtT4yIAl+aaNxCTEo=,tag:/hYJylc4UliWo9JaeEsFRg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T19:24:46Z"
    mac: ENC[AES256_GCM,data:w8karqycnt4nLS5l+7wedS1lMutxSCf0wnmzkYRtLN9Ud1LrIGbhSWkFNZlGme2bpUHm8162PMjntNx/xQsTTKqJg8bqLeRWw2RNkz8XZWkN6Cs+igB+8uUyrMGUkE+pjsu6u7mikO8D0VM5ky0vRvYmu4xKZJSS9PSefknRZ7g=,iv:56dbm8zUKuWfBu+l3YSNds9Zy6WijpzLpxUBH/0bhqk=,tag:jxcdofco62z5s4nawmb6ew==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: immich-db-garage-secret
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:FP0vbbFLfZzcLiA+FbmssRXfgChSQXAHCl4=,iv:PpoMZOJ5izKnAScQPFwi9CzDDPP29QcTCz5rtQABdC4=,tag:RBQzM4rmV6ZQ/LCsip8nvQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:BDiZgcFyee1uUtUsUcL2OOtGCys/GjdCMG6Y/qSYcKs1FLeQHKTUKSmGETQsV5hEonq5hSLUVOtUvZD0amDUKQ==,iv:wQGvDKCYIkaJd+bcb/b+vhbQwwqImXtH3ZWmQL1vCoM=,tag:ImMnx8aGt5M++ru4fyd82Q==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T19:24:46Z"
    mac: ENC[AES256_GCM,data:w8karqycnt4nLS5l+7wedS1lMutxSCf0wnmzkYRtLN9Ud1LrIGbhSWkFNZlGme2bpUHm8162PMjntNx/xQsTTKqJg8bqLeRWw2RNkz8XZWkN6Cs+igB+8uUyrMGUkE+pjsu6u7mikO8D0VM5ky0vRvYmu4xKZJSS9PSefknRZ7g=,iv:56dbm8zUKuWfBu+l3YSNds9Zy6WijpzLpxUBH/0bhqk=,tag:jxcdofco62z5s4nawmb6ew==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
