apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: media
stringData:
    #ENC[AES256_GCM,data:euHhQA==,iv:04JTh4bMEtz1w21JLMkORcStKPofc1JVuULxIg2SP6Q=,tag:LXo5qWfn3whPHFIao3z1xA==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:6WDECk3dYT0vsxYUU5PFgwQ/lGBUBxnI5pXkfca6qNY=,iv:nimt3vm7bPgv7Jwj9oCuNVZ5htcFFee+OMwvK8W/HGE=,tag:Cd2qYkWeTvZmN8SiI3uMhA==,type:str]
    #ENC[AES256_GCM,data:Oo1FsNuVcyV/,iv:+4aCCG+1Wjp6MwoK790OPjglE9fblxyUhcb6zDkw80o=,tag:Yob2IhOVWVj9gC2iDI6jrQ==,type:comment]
    DB_HOSTNAME: ENC[AES256_GCM,data:wBpPzr1Qh+d+TrJfM8AqlA/DeoyKVSWLufAMGyZmtz2WTg+SYylxPwG+,iv:qSK5hBSaZpaONbtia2V8dGn2jOW3psfBCzSD9WrydmY=,tag:A562K70cj5E8YJ8LK9bUdw==,type:str]
    DB_PORT: ENC[AES256_GCM,data:QzqA0A==,iv:IZIRZxVT8NZ0986WywJfyelGoBLCOegTnFAwaeop7OM=,tag:l+H9L3RjDXCnkgifHKIbEw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:bArm8NaUzNpOrzhd,iv:bcBtPGnkD44pocXovmmoBRDlUQSnAwZFwjl4YwpXx9g=,tag:XZitzQUTSFBpgJWXbhQkNg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:vOlfsH82H6OdvT/0owT1iL9EFivLTjprlSrmSEWXtlo=,iv:r7K9rqjMsDDAid84VHllNNmxUYdyHmgdRU8sC+mHhoU=,tag:DOMhpmPp46ciuUmTKMF8Bg==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:wpGAg3/s,iv:Y3UUSvZ5wEbrgti8YF7QA6lHdQuwDh1qwcfu/nnQy9E=,tag:OldQ/tbwdmGUS/MUGUbwdg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T09:26:13Z"
    mac: ENC[AES256_GCM,data:uLokIc+UPqP/vqvJvqCN2bEVVa6KaqiZlIDPMWOe/ljPnelvux0MkTa1TYLMoi6Kks+jOQk2uMmjvSJU8RhOgrUQadb2TdGGa6gdGcEiVgWC3GL8iAZmOX/T/U4YF4xKFOpg2Y0odUDn39OEVopAwoeH38CTtupBETb9dRX2sO0=,iv:1qUpM6coApjRdoRD+gMwgkwhKM5YTGK2WmwjFpkPlPU=,tag:M+LvCRw6pwf4MZSAJPjHow==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:TW+D1zvJwJY=,iv:AABkPJkpqVRwgfLH5M4Xh5OHJ9wdLNQyWh+sAjcbuvs=,tag:il5ETCHKdrHlrlAAS/JtJA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:dlmJgrhVAURAqhE5/+mCHFEbboJBazbiCrG8Z5hcXv1Tl/pufCYi/YW5wFQ1gQNxgeul7x3F9rQ=,iv:P+Cz5SPXU1VeSWWvxyljIwK4cjrTrPeHo53sgiCgNsw=,tag:QJH++UnI8uHdpAJiEswNEg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:UaPs9m0g1q+HQJPCP7ZO7w==,iv:f6kv5qIU6I4pQr3Y3SOs8KLJ46M96OHMAUWL0trERng=,tag:9Wo+x04d8f2sGFgLm2Y21w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:7dCEoKSMhLbCyZ2ckCfshajMWuw2i8Fuac1by/KqYZIbrhVRD8XfCdQ7+L0=,iv:ZvhgQDnmCRyPi2wKT86/vbX03Zq+ZBR+uRdxPLXHkcA=,tag:rQn0F0x3zkPuFHGQ8cAuYg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:7Ji41o0qInfXp1NdVKvlRdjfAnmCGafRqi2h0rDLzfxr635ZHOk++xZgSd4=,iv:IekbGpzkPzrzq+5cSwKgcKqc6m/xcC+59tQbeKRuhIw=,tag:SHOT3QW3qj8mxcmHY5KuQw==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T09:26:13Z"
    mac: ENC[AES256_GCM,data:uLokIc+UPqP/vqvJvqCN2bEVVa6KaqiZlIDPMWOe/ljPnelvux0MkTa1TYLMoi6Kks+jOQk2uMmjvSJU8RhOgrUQadb2TdGGa6gdGcEiVgWC3GL8iAZmOX/T/U4YF4xKFOpg2Y0odUDn39OEVopAwoeH38CTtupBETb9dRX2sO0=,iv:1qUpM6coApjRdoRD+gMwgkwhKM5YTGK2WmwjFpkPlPU=,tag:M+LvCRw6pwf4MZSAJPjHow==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
