apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
type: Opaque
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:QvG1MrLMpefo9FKhj7tMMCe023UP,iv:lMLZozjnP09gM3yyTCPS5IoVusXL/vDezI8PbT8JKok=,tag:xPoFCvejbYaNmGv9YvsbGw==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:wY9ifkmd7Y8DC6TbuPRa,iv:VWR6crlDr9V0T0jexTf6uwFClXWVM8xT5gooisIVGkE=,tag:YEstrpd2X7YhTqHw3TIiEw==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:uFIdf2Xe/z/pLPN8nOCV3cuBBOQ28igz,iv:NQcmXRgwDOPWKnECWMIdXkK9qXIaMj6ofGsEAvpiXeg=,tag:rOfNCZnNI1SbJTC+08OHqw==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:a5t5MNCbUvZm6vezka5J/Z+A+0FGGvd7,iv:eyYwhaR17veesBHe8ghKIjyicfX6eWO6bJnewD/gxBw=,tag:9LYRPvo+5Ie7OscWbNaWTg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T19:33:46Z"
    mac: ENC[AES256_GCM,data:b5fx+5KDhwNpfKEegB0lNh9Fl64J7BRuJDiY2SnHIHyz13TMg/q1oY+JTRnKg6Jb44mvg9vLUvetgSX89ehSJ5l5Z0DG34MPKUtXKn1bQYa+bVJiBCGC/tOk7/Q/VurEPSmVeSzIYWOKOP3YWkn87oZdaFy7mPmHD+Ln+Fed7r4=,iv:AEwxvmK4vLIPG9YwLO4YmTKOMtIEBDEgeYFcbRZTtuU=,tag:TdLghCiSfV6oOhNM7IJdSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
