apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
type: Opaque
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:myeSdrOFcJWYg6xU5Jv8phjS,iv:7oVfg3K5Vfld2IKSYecZQSUdi2nJknKfqQpJrQAbsYM=,tag:1IyXJ8fbNlsOnj4CHNoANw==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:5VTbaWBIFiQPJ/2j5Bkb,iv:b626XwpL/CYD8voJXnIFz3m0ldiBB5hkhJ2jc5icyKk=,tag:LFaGNDYLNhpojIarS3wVYQ==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:GZGDQi5ZJVgr+PVHzuNa4ov2/2hmOAkcpXM=,iv:rfKAADs15uymzfqLDkJMhHXPG52+ee/+XLUc0S6XkC4=,tag:5aSe+cVr4dZae1+eSHnl5Q==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:StsXnOH7A6zgpCp3y2l8yPhrOxIjhpIf,iv:x86KNAk69AIveqU+x6TT1WFQ5sk04+bWV79x8YMHQpE=,tag:npknTyrwcvqr8T/UooXSTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T15:12:45Z"
    mac: ENC[AES256_GCM,data:Da6TpOy458K9Fx9Lu/K8RGgJlZQqlqfTu2CrOz2Wm2qYgeouO9QWEzmn5bP5OVTQEIhvDgz26h2ILX7rWSv747O7/eD93PaZ8yeh1ypOFak5UzP2f755itUXujIPodc3+WgfCHvVM+yQUddluDFOxfs6TDScj3YEXwqkraXlw2g=,iv:t4WmHpMEAqkZj4H15pSLLxisARhvK+J65X+lcRjwny8=,tag:sBE0Wi38iu8FCvEAcfm/9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
