apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
type: Opaque
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:ae1RskhHiCnwUB97ood9kuVL2BZJ,iv:FTnll3CEtC+J5unA9D+vYnsalvCRTaSBQhEKUGsreQw=,tag:XEdYTcNALF2gQHXVGmrpWQ==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:5VTbaWBIFiQPJ/2j5Bkb,iv:b626XwpL/CYD8voJXnIFz3m0ldiBB5hkhJ2jc5icyKk=,tag:LFaGNDYLNhpojIarS3wVYQ==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:CuyuU4HjUixYSvig6VEpyMHOH8ktiIQy,iv:Ry0N0EPgJDmdmkjgmQgQ2gNOKxwo4QcCyRzcvzdHX/Y=,tag:azbUzkkf0DYTjrQnUm2Bnw==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:StsXnOH7A6zgpCp3y2l8yPhrOxIjhpIf,iv:x86KNAk69AIveqU+x6TT1WFQ5sk04+bWV79x8YMHQpE=,tag:npknTyrwcvqr8T/UooXSTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T12:09:00Z"
    mac: ENC[AES256_GCM,data:BxLmMgH0/BCJYrc95cTHiNbjY7uUNT8iU5U5Q1afwJCXSfQUAbZU37l2/AMvDU8Ee0rtqo0LQBMDXS74J1ZJOUO+Qpg9efGjriE+xoBJobKD8KB42LLMHqBUigSnePRkxh2PK5q25wjWxzRS8tNNFbBabmBodG4wiDSdBgLCCSs=,iv:wpwYFu2+sHLZ+d8lb1VeHCdRYgToNFRFfxUVwOwfVZg=,tag:84uMk3pwHZTEnc5WtpuirA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
