apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:w23rktlebwNo0GDD4DJT9JH5/ltNiSqA3iGRGD8IHPtbqIX/oOfRAMZUCfOtImUA8QjRAGw8ZU5+IU9VStZ+ILzCPrdewdVQgrFNJnZPhE+fUAMHSz2EHqaYEK79Ojo1b/idBbAhKcpWKkTzz6Y=,iv:xviExP8nqX/wf9mOEwxA4QILfcN/lRHm59oy+a79Ne4=,tag:EfLkfm1r2SJHb/WrXDIp5Q==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:vrkzxm7RdbjvXlU=,iv:8jN7LP/AHeHhvLfTARIP0UIKuDTncpe3IncM8GJy8uU=,tag:5JMPxAOfNLKZVehufK+Wkg==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:dUX9mMwZM7gzcpevgCGqzNNNEXOM/mMiXwg=,iv:NV82pnzUvJKl3ahquKtF1FZiySPXBNhU9SbzVVCCWko=,tag:6wPQlJ3AmL/XTaJYOtQDHQ==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:6hWSM9O1uP7B32Y5NTvSpV3R5eyLAo8YrRLpclMSlJKxnbgd1xiy/A==,iv:w3yku4Bkk0I/rsBueEJ4tTI+Lwvambo6mhdrDdallDc=,tag:Kd7hCxVdRYywCqAzQHnzOw==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbDMvOUVFVEQ5R1VkcHN4
            dWplU0cvRldlN29KU0Jub0h4UDFUVEZhQ1hRCk85L2hMRXZianRNRHR0NlJ0eW9P
            MkFLdzdqbzZjb2hIaVlFTysyN1RJSE0KLS0tIGtRc0FZemwzZlhpdVpTcnNBeGVr
            Y2krb0pVTWk0TnJLalhhT09pZC82bXMKW59BVpnSVACGbzVgJtdOAjW9qVOTTjpW
            RLuyt+Nct7O+eYb2ZenB8aohSsanVzmU4mFvh3yKaKEFnMPhcCXmjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T19:49:33Z"
    mac: ENC[AES256_GCM,data:YBWYkNd1axReo1XhNvAwfkvhvKahAfFNbCDV8MJ/qrHL2eFvR+N2vwOeSskLdZUcWDtbxuk5OuC2n2+t2okyp6a8xn1RDZTrsGU8DqqMx+R0jrFxgY9RNzxt5I3zd6ZDVme7i/cGVbozrQMrym4stv8bd9j0zXpQy4PBk6hf+qQ=,iv:1XAbN4xPA9nrT+r50xy9s5pidHHWALfbO++r7pkaKRM=,tag:NDgna6CdRoyv1YJZBJyOTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:FxtDgk4rH3gWJYhKZJdzEw==,iv:Rlz9k2gOatfg8w7eaFr4NQ+Z8tC+inFDHG5S93Jk5Ws=,tag:Yo/ovsB9V2plnmMw99Rnbg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:k4hSl3lMFXTuLOHjlFIQ+l2Xep2TqDSmK2pVSdYLR4GZfVzqeYfU8rlEMiG2n2GDZ5glt3yaYIM=,iv:ub175esehqg+FhybgRNyh4J8lmHfPWtu+PmlB5f5Zzc=,tag:vLDSQjdSlQyITVTOCDoytg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:rmAARQ0H57NphChPcEdJRg==,iv:UOp7SoFx16N2RNbBWgr3b2dLRGcUmsGCsF9nyoktYc4=,tag:XrkYbATszD5XimnInhb08A==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:G2JIr0Wdhl16s/jLOQzmcbUgYasBeDhPSMsIJx+tUOGi/5Eq,iv:/mYSIT0xXsYXJ/eLmn8gi8pKQ/3FnKIsA1mlvLql8WA=,tag:aYg/NrPc7pCN2fV54JgyFQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:D9Ui1ji3u4xvUd4NinlwWs09jxhxzEsDGw==,iv:c/fuFReoBOKjqHYf0hA0eWZQqU/j2gNg9LzIZakOexY=,tag:EIVEzxTX91QRf/E6uVDKrA==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbDMvOUVFVEQ5R1VkcHN4
            dWplU0cvRldlN29KU0Jub0h4UDFUVEZhQ1hRCk85L2hMRXZianRNRHR0NlJ0eW9P
            MkFLdzdqbzZjb2hIaVlFTysyN1RJSE0KLS0tIGtRc0FZemwzZlhpdVpTcnNBeGVr
            Y2krb0pVTWk0TnJLalhhT09pZC82bXMKW59BVpnSVACGbzVgJtdOAjW9qVOTTjpW
            RLuyt+Nct7O+eYb2ZenB8aohSsanVzmU4mFvh3yKaKEFnMPhcCXmjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T19:49:33Z"
    mac: ENC[AES256_GCM,data:YBWYkNd1axReo1XhNvAwfkvhvKahAfFNbCDV8MJ/qrHL2eFvR+N2vwOeSskLdZUcWDtbxuk5OuC2n2+t2okyp6a8xn1RDZTrsGU8DqqMx+R0jrFxgY9RNzxt5I3zd6ZDVme7i/cGVbozrQMrym4stv8bd9j0zXpQy4PBk6hf+qQ=,iv:1XAbN4xPA9nrT+r50xy9s5pidHHWALfbO++r7pkaKRM=,tag:NDgna6CdRoyv1YJZBJyOTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
