apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:gyIVHmfdYu9wDkmwvzP/9IQmXsS5zWdepXymM5e/Srp49uOOzvCFnEbhY1pXOZ036BugrZP6Rs/NYZr/f4KIoUuMNRXSVFgFeKorhrF0dQ+6E7f8xIuuIfgf5B2wsJKWcI4JRu6Z3iue/3bYa1M=,iv:JrjoZGVfRaO9xtD/AIqZOIXsFMssvfjpN3ds6DEcPUk=,tag:4VgaVa8WjucsJaLwaf2qFQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:O+3gKEL5OWNmFcY=,iv:9VVRe33IgzuaZXf5AY1v1glmm59TH38tl/6YLu9p9fc=,tag:GyeOdhl5lXX6A0N2kChe9w==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:f9rlXzI982yni0h8B+Fhl40HlStcHbTOrDo=,iv:UFguA9NPseb4r8jHIjawIzARAR2NL8fDqR9qZiV/Lqw=,tag:i6KWC6kBnt0c+0L9+1UypA==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:Rd84MTtl7ReL6H9FE8Dhk3JrF72UMxCOSficBB6S0trmOf0sKpfhHA==,iv:DgmK/eX45BvNC28p4ufz4ygzQGdkoxduKfLJRR/uvME=,tag:85ypi0xGrbbW0aL3QN9xKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-23T21:04:27Z"
    mac: ENC[AES256_GCM,data:J/lyBc/xLk9pGN9JxNmwlfGH7eMsHqjhGX6r7pEsVwuTDKjOROV3NvtNWpQwfl+mE9cFE1xnA+bh8/8UMWCpEkLBPwl6Vbe4/x5D6Ks3HUbboe3PhOZDkXlBICq3MWWMDoSYD7NWOCp6k8yZqSblFye1trntRoB04fY9xwMitc8=,iv:0g+iF7qnZzlxl4+nrI/jZkNvFs1+gF7JK42Ni6Z9BBY=,tag:aOsNl9sSYFOolSvEqGcTBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:KebRvcyyeMrh9x6JwQv/Zg==,iv:2km0fakmcnzfCcJ3t0or1A/U5mCoqPuODlFmlWb8uKU=,tag:RvcTnt2hg7vQSnr+UOPgJw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:/a+nP936NdKtNSwcbJmH9SphlgRTLU2WyGZHdPeOPynuq/ixMfyHlKJxt+MvaNmxM4S6xmoyWLQ=,iv:siZlZGqmaO3e5fLuf4YBrQC6Dw3ea6R5tIbrFpuSsWk=,tag:SaGjrQtO/jep1qsuiJrmjw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:LgjT3AoLH6RpGSj7So2BLg==,iv:oRUiPv5sdoxRAM26LnNAKH68YCJxqAlk45+000xEKio=,tag:MDT4s5+wWL5rzAWSReWZBA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:RATi8XpRqc88gdgVWsE28bghxZS18kWZeKQiV1qL/JpdMgbA,iv:pGj9X/0U5s6nkgA7k6vrypBWWROnXlyTKVFp1Co3jy4=,tag:JWgnc+++UykSYoMYYB23IQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:/CkHY6zTAG75ivkV/pm0ONMvY0u35u9jMA==,iv:td9wNNe136PrYZNiHuOsG8usU14D25hmEikZ06poZD8=,tag:q+HVuy1joNEE5TAbrTv0fQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-23T21:04:27Z"
    mac: ENC[AES256_GCM,data:J/lyBc/xLk9pGN9JxNmwlfGH7eMsHqjhGX6r7pEsVwuTDKjOROV3NvtNWpQwfl+mE9cFE1xnA+bh8/8UMWCpEkLBPwl6Vbe4/x5D6Ks3HUbboe3PhOZDkXlBICq3MWWMDoSYD7NWOCp6k8yZqSblFye1trntRoB04fY9xwMitc8=,iv:0g+iF7qnZzlxl4+nrI/jZkNvFs1+gF7JK42Ni6Z9BBY=,tag:aOsNl9sSYFOolSvEqGcTBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
