---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: snapshot-controller
      version: 3.0.6
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system

  install:
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 5
  uninstall:
    keepHistory: false

  values:
    controller:
      serviceMonitor:
        create: true

      # volumeSnapshotClasses:
      #   - name: csi-rbdplugin-snapclass
      #     driver: rook-ceph.rbd.csi.ceph.com
      #     annotations:
      #       snapshot.storage.kubernetes.io/is-default-class: "true"
      #     parameters:
      #       clusterID: rook-ceph
      #       csi.storage.k8s.io/snapshotter-secret-name: rook-csi-rbd-provisioner
      #       csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph
      #     deletionPolicy: Delete

    webhook:
      enabled: false
