---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./ingress.yaml
  - ./secrets.sops.yaml
  - ./pvc-addons.yaml
  - ../../../../templates/volsync
  - ../../../../templates/gatus/external
configMapGenerator:
  - name: odoo-configmap
    files:
      - ./config/odoo.conf
generatorOptions:
  disableNameSuffixHash: true
