apiVersion: v1
kind: Secret
metadata:
    name: odoo-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:CJgP5Q==,iv:rFmqsHwvjJ+jo+/AtsrEQsHds7rUObKWL58ruIVtH1k=,tag:zuMDUuRSoBN6X/LZs0Xmsw==,type:comment]
    HOST: ENC[AES256_GCM,data:47lDtaQkFAHRdyq6KOuKqEihedSvTmlAwOhmbX7G4zgNuPbgqiSkhg==,iv:XIujdvm7cA50zih/80ZceQ+Ryn/e2IeIdyFgbgCNC8Q=,tag:WuoNXeA9A5AHTcJq+p/uGg==,type:str]
    PORT: ENC[AES256_GCM,data:/VJ9lQ==,iv:7ixoa9YAES5BbC8cwy+zhFys5yjCP2pr4woTio/KDSo=,tag:pnuUe/VL4Sy7L7EGjw7GGg==,type:str]
    USER: ENC[AES256_GCM,data:dVnhFj/D+ClpEg==,iv:16iLtBotIohV0xowARvtUoIY+ycBV02XpqWAExZhrO8=,tag:8m1+RDFfGsbU3hVUaf7XaQ==,type:str]
    PASSWORD: ENC[AES256_GCM,data:LZ2hKVZa7E/CShrBEBo39LtmuuGQHN1HQV2CkNccUHE=,iv:iwD9W53/Np5YPyxuFtyKmehADQDTVxjGxCPRLImQQa4=,tag:7Vq7KP5AUd8+akKbjI1mkA==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T16:31:45Z"
    mac: ENC[AES256_GCM,data:MhRAuWMfk2jyGabOY94R3Rl7rHqBHoYcKjxEvsQLgxtj0E/mSCB1vV1AbbuctK4v5Dn+PK1kUjLJ3zs+fh8RnTx7J0Xu1EsMibYm3GvPbbbHZK0pcdXfz3ZfP7eXhCZjTlfaZuGeYg9MxwAVFew/Pe9aoAMpaa3RuR+hePDDD+w=,iv:TRkXG5koEUvVMFNthG7X5836Z5BdWPH8WQ63Zzplm7k=,tag:WMVAEVzvi0WeP6DiBROu+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: odoo-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:E3lqg3aqSoM=,iv:Z0ykDuV7Rio+ZQttV3N7GwuhJA85DrykCkDP80qBy/o=,tag:3Y+yoHmNCR2+IQfAyU5JkA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:+Iu2ka7yiId3oNQNJjNrxm3A+3yT10JjlV2QHvp80Ve4xx7DLIzfml8LVSPLZSG7PmBAHsX/3rg=,iv:cfLo5wFiSCbVvxWShE1+RfPMw5CrLuIxk1QKD18iXq8=,tag:uHyE4EZm8OX46hJzyXB4wA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:1PZl0BLJF6yA2vOa4rEEug==,iv:pP2hjP42dDsWnHcsLP65hXH6aapEMFEZKJ8CRxQoVxo=,tag:yQRS+Sb+/gHTPUoyBe7OMA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:cXRBfZ5yv+Ukx6jI5vo8PuGztFZ51nZo3Yyha3mI4lPMmh7H9MAda0zh5Kg=,iv:0rzjH8y+jRgivSSsTZk2sW3Mor0Ear+1ExMXC++kx1g=,tag:2VUeNmSnjK8SYZX2AgAw3w==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pFwxhGOwHKAu2xIyBftXJX/vVh2j2ZP9LA==,iv:yu6KuqH2ptJ+SYum+MVAdH0EYGNRDml3ZXxEivJXl58=,tag:IrJxPc2sWt01Y3ZRZdlmUg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T16:31:45Z"
    mac: ENC[AES256_GCM,data:MhRAuWMfk2jyGabOY94R3Rl7rHqBHoYcKjxEvsQLgxtj0E/mSCB1vV1AbbuctK4v5Dn+PK1kUjLJ3zs+fh8RnTx7J0Xu1EsMibYm3GvPbbbHZK0pcdXfz3ZfP7eXhCZjTlfaZuGeYg9MxwAVFew/Pe9aoAMpaa3RuR+hePDDD+w=,iv:TRkXG5koEUvVMFNthG7X5836Z5BdWPH8WQ63Zzplm7k=,tag:WMVAEVzvi0WeP6DiBROu+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
