---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ghostfolio

spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 5
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false

  values:
    controllers:
      ghostfolio:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: "17.4"
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: ghostfolio-init-db

        containers:
          app:
            image:
              repository: docker.io/ghostfolio/ghostfolio
              tag: 2.157.1@sha256:ba87d45b1d3d26382ea6e3d25478c81fdcb9f7b29ec39224c60241b9d5afebd2

            env:
              TZ: ${CLUSTER_TIMEZONE}
              NODE_ENV: production
              REDIS_HOST: dragonfly.database.svc.cluster.local.
              REDIS_PORT: 6379

            envFrom:
              - secretRef:
                  name: ghostfolio-secret

            resources:
              requests:
                cpu: 200m
                memory: 384Mi

    service:
      app:
        controller: *app
        ports:
          http:
            port: 3333

