apiVersion: v1
kind: Secret
metadata:
    name: ghostfolio-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:MqhrwucsgsqaS50C1OfFctQhNFbK9p1QTuvlf0dc2VHNa99DHO3JVSnpsCE1M1tCx1SczRvi3Zfl9WtSrrIpRMhhi59BuYjSgWR9qnsUT/vtX62QQpFUUJkrm/8qVRc/FlR8av+2Mpav7IuckpmghSu55liL8cwfX1uC3Lkb6wUR,iv:f+LBuRHoOZl4HmvjsU2gRptPuQHbVBJUVggqk5qlT0I=,tag:dTmc2hHZu+c3b8ybmK5Iag==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:HgVC2u4ua+TeNw==,iv:Lzag2yDE0ZOWzdRxPnT8P7+liLR3rf5ZpoP9EbS+rBM=,tag:TlNStuddPUOiZ4+VGK0YXw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:hDMyTRm7VMgkYIZX3Dx2Tw==,iv:gY8rzaMvOZNwM0QTnsMKxKHsAVZfYjcMxkISSu3dxWo=,tag:YHZRXRbULuge92eHjhNdmg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:CVwEUdqHDaH0Q5PAl3YPNp42n9EUu3sI1g==,iv:7yYeNhC8IjRza3A5nmbvu3GJi5jqe4UVf72unPgq3s0=,tag:HAk/DyNIAcysoB5H0Wq1kw==,type:str]
    ACCESS_TOKEN_SALT: ENC[AES256_GCM,data:vfI/nh/R80buf/hNa0hPomg1o0rxkfnhg/xA4e8fxtM+cnp2wAhOlt/JEaJClIgRNjLX/H5SJo1WHwUluhTk4g==,iv:0wEA8ZiYSM9pj+V0noPJF1Qf7sywCPgmGQKnQEbJQ7A=,tag:mNaqC97VnzMasb6tUQMigg==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:STXEi3ENxsTKnoZ4ACmWE36cvXOErIeO3NbLsGkitHDUe0MBXZlQcZ8Z93nonR+Dfmzp5BuibP46/bf3eRWFQRKiAShk2PmyCuitjRcwBw6bq3hM7JBOw4rBMJ1hW0BGsu0gOi64t5DVMrhpwg0NvjwhJISmzHQmhXGNSwkHpjQ=,iv:Ox/8uA9jmNnZ0veCrJ7c7d0t3CmwejiarlKAlTE4Tho=,tag:8tLeKoEVnY0R82QJ5or+5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T18:44:12Z"
    mac: ENC[AES256_GCM,data:h38ZWDj+BfmifxXOCTeYShVVaJk4jf7DETQ7hSjx2mikmwgbA+kh4Kfxj0cEkw33Skb4BvrCCV+oV+LZKFlWEFB4VUnAObjzZtS5wqitGEBZd3vZpWnbupqxgnLHTPC9BLBZbCQSpM+wzkpqTEo9jubbe+Npic15iY7VVaPvjKM=,iv:B3nOgffue3O87NxZVtLX1mC5TASMVy+P0mZ508diRXc=,tag:ogpU+a89EXcA5WEblXSRTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: ghostfolio-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:jIkWHui5d35L3NfdEmq4Ig==,iv:SMXDdw9+5FL9pVpSL9NZ/aGGBdsHRzv39991kgnyfMY=,tag:+9hAF5H59XwhW67wJb9M+g==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:KS95hkMWn4m27RqVTVk8vNBTrnfu3PWYaBe2avskPuAd90mkBfZ9Lqjmn17LC9wpS6atVmlLrz4=,iv:NvgQdsliqyBoYEElPExB/HigYRchbp7EMWQ6K9Y4VTs=,tag:dsHIlLMWLiOUzHGqjvlabQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:Rcc0jbiSOB9sZmTBVXA5KgC/uEPcQhN9,iv:JLSomEr3TP9mPGjWqRp4ftKSzFLaMmBvyDJH0n3OUQM=,tag:6r01YjhkFBgqB3LWWW3bjQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:/kluWnhy17FekKPXie6ju+BxWAY5n6DgSeHmjd9aZzbaKvw1,iv:T37ITxKRjssYSWJlYyopbPPr2Uu+OAdeM3KbcWDpp4g=,tag:1199jk7ziPeLZoPIWveImw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:MvbObNH/DyOIVIH97SrILnr+R8uzQqXmRw==,iv:8Vws5zWPPqroBzqjEcDHUJqOqeytNjbQH9BIK4d/8R0=,tag:Kpp1qO0mfeny4PCuW6jS1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T18:44:12Z"
    mac: ENC[AES256_GCM,data:h38ZWDj+BfmifxXOCTeYShVVaJk4jf7DETQ7hSjx2mikmwgbA+kh4Kfxj0cEkw33Skb4BvrCCV+oV+LZKFlWEFB4VUnAObjzZtS5wqitGEBZd3vZpWnbupqxgnLHTPC9BLBZbCQSpM+wzkpqTEo9jubbe+Npic15iY7VVaPvjKM=,iv:B3nOgffue3O87NxZVtLX1mC5TASMVy+P0mZ508diRXc=,tag:ogpU+a89EXcA5WEblXSRTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
