apiVersion: v1
kind: Secret
metadata:
    name: ghostfolio-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:msfUHauo3KaOvdMjh3Yn0jd3/M7IwixeXsVbyu+j2BbF3XEx8EDJQ1ti952Dvw2KyCYVr1MNDjSMDyFAOmdtKUfcMil6Ij6t6lsFvxHW3a3uCqikYy6k2RSaECga6oXLOGBWwd4dGtQu4RU+N1RVbkqA+pqp6Cf9Pr4+o4xObIU=,iv:qbp/VrgzaietFFNKLX7YsRcMWSzZfUzVaeord4CRJAQ=,tag:87kqXZa3ijblsNhZNjHCIw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:qxDPdEgEkgAfzw==,iv:gSASCY24Q5IYE+gKjUzzVHlgL6dZOa0rBespiGc/Yow=,tag:SsHXJ/KOWbGqsGhtyotQhw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:h++fboXjNhu8toiJpa1jiA==,iv:Qg/OVm6v5JfBBHj5BJ6aN84jCfoHLzyyusyx7ABrt1M=,tag:gNCiLXxyMJJPleGwF76CSg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Jp+3RHxIjF5aXUQZmT3iD/380PIo7RFHhg==,iv:GuXuu39B9Otyt5o3dUQq164IGOJFbEDqzbWhNHxF7AU=,tag:Rdu3GoBPEBbL9uM+1UpjJw==,type:str]
    ACCESS_TOKEN_SALT: ENC[AES256_GCM,data:mbK5L0vORJ49FOY7LCtwFYxOWZO+i3XJSr3mpo9hlG8FOlgeKR4muU2dCng3ceFyXwxz+2ItZbl2CPT2J6fzAQ==,iv:ET0jYZiCcVtCt8weZT+htwyB8uPucBlyPGK+/jDS4oE=,tag:8YXsKJt7tnua8ybYIgrEdA==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:pgzO6lWg8mat66WjVZzNZZaPlpk3d0vIe53bO2YpIHvdheTN76DbGoEVmsn9BUbsGUwQXPYGQTVEgNJtRx8c7T4ZI970Pk8mVkqqSAs12Z6go27VnSK60P6o+0c4gapd2lrWR1sAImkAQzDDtJf5W2goOu/Hisay6UrxljZsTDA=,iv:VldyyXAA9uARARsHndUZepc0RKDiWWpD5bSbAJZTROY=,tag:9uiOErRaKsUu5amWLwq1NQ==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T22:09:59Z"
    mac: ENC[AES256_GCM,data:BpHM79Ft+muqRntu/eCm/c7iXgHZIJRQH5sMK/aqP9GZyWQzhO/Feq1nOKVZrS+FAIL9GBdSHgvF1n9mqP89k1GWjgqUImdE6igyvZkaIT3O64cqzOlSfx6vWJSrAEbRBJyY+MzNoW6fuadtSFJwS3eMJPfeYEMwNDYX1W/TFwM=,iv:yfxuRRT0kxfEkGp2OBARpn7EAOCo/PdUWJLSAYZlCb0=,tag:PjoXR0oLwagidabiTGkTKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: ghostfolio-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:e0F75zH42x4501pwjE0W4Q==,iv:Fgaq95UVOARKd59aXMtbAWAOjrkV8A5SOS02ngY5QJk=,tag:pM86Etl+xNrDcAMXwVPDQw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:eLBHRKwi7bEjkkjiSqJ5/nZlEMcz+qZXH0RVJV4srqgRhqqsG4ZdGrHwpRRfYvCAne6kR+eRheU=,iv:AOWZ2d3nZUwb0RrDXvvc4/sJ1+HJXDQQCWEFyT/p67w=,tag:Y7lhb1hTYa18T5qwB9oXMQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:/Ajr5XVgL1r4Q6fnUkAZNd3NO7sPBnni,iv:yHRjVSG8Qzl4g8MbQtDmBrCuXH/J7LyLQ4IaW9c3wgc=,tag:wSUd5Sm7HhzH+c/qMCX2aw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:qXyk4aRrbXJwp6HUwSp3e0HM/W4GJghl+LFHPEniylztiJ4o,iv:XrI0O2ocro3m2n41lM9HBuwwndVAIslaIThQRMHwupI=,tag:VYITecvLWWxrhO9ePpEalQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pFwxhGOwHKAu2xIyBftXJX/vVh2j2ZP9LA==,iv:yu6KuqH2ptJ+SYum+MVAdH0EYGNRDml3ZXxEivJXl58=,tag:IrJxPc2sWt01Y3ZRZdlmUg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T22:09:59Z"
    mac: ENC[AES256_GCM,data:BpHM79Ft+muqRntu/eCm/c7iXgHZIJRQH5sMK/aqP9GZyWQzhO/Feq1nOKVZrS+FAIL9GBdSHgvF1n9mqP89k1GWjgqUImdE6igyvZkaIT3O64cqzOlSfx6vWJSrAEbRBJyY+MzNoW6fuadtSFJwS3eMJPfeYEMwNDYX1W/TFwM=,iv:yfxuRRT0kxfEkGp2OBARpn7EAOCo/PdUWJLSAYZlCb0=,tag:PjoXR0oLwagidabiTGkTKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
