apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    #ENC[AES256_GCM,data:DuvDWPGpD1Er,iv:qTeV2/7xemTDardWhNh6W79JeSRDv0Avi0WWYLLnL7s=,tag:4zOyOG+cjnaHvWMHxzhPqg==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:p1GFocnWejScgWBOP5bxz6v5IXs3U5s7qeupWKK+YeBgHiwaRUBOHqpXcYvg3HVf9AX7qlgKtRo59PncYFhIFQ==,iv:q8zXRRSvsOJqFs8KBeBBUN9ZXpv0aUyF1JMvOQUBJlY=,tag:kJt7P1cOes7C8B2l2F6arA==,type:str]
    AUTHENTIK_REDIS__HOST: ENC[AES256_GCM,data:QQEnop5ADrDITVm4CBrQRzUIzdWMwdr1hBMJy6Ogbdw4bsjmFg==,iv:BM9vUuIp01u9c2lLfCJQ/3evyLhttlqRFFCF/1aGa+Y=,tag:V7sHDGwANgwdWSUN4dDqJA==,type:str]
    AUTHENTIK_REDIS__PORT: ENC[AES256_GCM,data:ymEfQA==,iv:JkSfVHZQhR7K6kJckSPW4+RyyhvBgnUvkAtVaCY8O1I=,tag:QFa8S+0YJV7ZP5HwYiDbVA==,type:str]
    AUTHENTIK_REDIS__DB: ENC[AES256_GCM,data:ow==,iv:A3w6aW2lNIGCP6w9Hflv4m81ut5c4D+9FThC68lAuF4=,tag:HWCC/VQdPkdzIHHBA+4pJA==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:rGRthbyrSHKHiGsChUq3/FN8TQ==,iv:P0wyb2/hGzUfYj4BxMVqujjoqMzgjVA5VBMkUhy0zN8=,tag:O4QqSWRL8QltMcq2up8rpg==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:YeF1tBVTvmFR,iv:vUuD+h8zSo0DoZp9tfGdXz9BQa1trgJmU9p7jOCV9C0=,tag:zZsXDSd+wn+5/CN+cSxPIA==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:k63uA9qTW1i33yaobU9l,iv:Wdf8U9K0ZSCa41ZUEr93Sm91ch6C7MaKgQI3x7xlqAI=,tag:b4YdF8So3x0HPGQRdVjC9Q==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:niPPCWWVuiV5F+bnj9ByDm3DJImE0QwAkg==,iv:7y310cy7AzztKXLq24I0k9ifozqejkuA8EWfFSNbqkk=,tag:wSxL4FKl+Zs5R+uYKRRVcA==,type:str]
    AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:EkM4KNOqIlE+X3UNcIa9wbPxo0ZhiB/1hgBO8A7630hc3YVylg==,iv:2Yj99DJ0/kJkOk5Q/obJtSFJUR3tYYc4k5mF41bfe5w=,tag:rAJu5K09R+oYDd32blrqeg==,type:str]
    AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:xaQ=,iv:G9nLbCk4YCPYnf7lld/HrDPpZPgYoXF8Ymbdsbw4afg=,tag:RqIwBI344rSYYUwNZnnBzw==,type:str]
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:gV4c/CzXOoFcpxbMg+md43WNRsp8E2DQd9X8zkFz6XnJjViNiLQ=,iv:7jOnaaXOrDnjkGP5JtRdJcE1qdeAzvQW5DyKTY8ixe4=,tag:2BWuIEejAGnhR/+e+YLypA==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:cs6YLr+hi+J74WLwJNHeFr67nCKUk6UyQ5h5/5Bo,iv:DIkT+11GpdIYcsg2D/dXubV1A13ee+HCdK69VaPlhTA=,tag:BDBlVsou6bB8T8iLDzXZKA==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:KjvH2o6j7Mp3Rh4SC8StzwEw98g5SD2C0KqT7WPSqkU=,iv:zlmufm2emxEAw07qu/o3Ii7eMTMRT4wwtVohaPfD99A=,tag:nF+kTzilEM6tiUZvE3SH/A==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:eWOdRYBS1kVsKrPDW1J+h6BlfpxuuZlls2HFe22H9cg4z8ruq3pHVds25RHUn1fgQcV1/1JC1clhal5JZMQkjg==,iv:3D75pcNOHk3crxR8zg5sGBozdt0Q6jO/UOhRr6hC2kQ=,tag:8uzdpu103MBPWNZzy4hnbg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T04:13:28Z"
    mac: ENC[AES256_GCM,data:aSLsZP4w23ZE9yGE89tC6RdyDnWCVou8W/vwH1mHklDgvMmG8P6geRQ65/A6bDUBXKjeYpLCATRpT06LZe/Y/ZNBxiVHWcJbw7znhcaWbpPW2CYnqVTmaqN58cqk8nqAL7gkbfjjt3AXeWC3q5VgGmrqcx6Sim7xEx/Cot/mzcg=,iv:F2F/c0ZC5/aXVDEcb8jQDubzcEhwe/v0rtIwFvMcXzc=,tag:FIEMnYbxzaTvIps1fvvhTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:l8NJUwW4hAvyyKjx,iv:uawGXixqb6CZ9oO90cbU74B2apJprlOcudEjA3yCW+Y=,tag:jGRwd10t9GLBbEf/ibbxvg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:ZwhB1Ue8ioUfExhED6h8VJvtdg26oR8BK2/h8V9GGgw40TDvkfS3XgA0nRKph7h0H/xWMpdnqJ4=,iv:Ouqi25uAUo6ZJV5GjSrYYeS9zr7NQc9pzm4WUyaZhRc=,tag:/bH1TBP6jKAEvC8IYFDEtA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:M+ipPGQaOtNBQCGHLv9fYkHmZ6Y=,iv:1OfUHGkfPXuPf5ViLsqLEH/GxTTOgAP1yH2iHSIxFaU=,tag:cVX05HPivLTLRLatr8ExxA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:8P0HzfYjhzYcyqurPvxI1vqZBCcfuWhhFnsrMf4sCAuxEo7q,iv:j6/GhzCSOWTE9tv1ck+7hw9jAUlY4uqfMnF1ha644bo=,tag:/sGI73LtC+QvNBoG3rD+bw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pFwxhGOwHKAu2xIyBftXJX/vVh2j2ZP9LA==,iv:yu6KuqH2ptJ+SYum+MVAdH0EYGNRDml3ZXxEivJXl58=,tag:IrJxPc2sWt01Y3ZRZdlmUg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T04:13:28Z"
    mac: ENC[AES256_GCM,data:aSLsZP4w23ZE9yGE89tC6RdyDnWCVou8W/vwH1mHklDgvMmG8P6geRQ65/A6bDUBXKjeYpLCATRpT06LZe/Y/ZNBxiVHWcJbw7znhcaWbpPW2CYnqVTmaqN58cqk8nqAL7gkbfjjt3AXeWC3q5VgGmrqcx6Sim7xEx/Cot/mzcg=,iv:F2F/c0ZC5/aXVDEcb8jQDubzcEhwe/v0rtIwFvMcXzc=,tag:FIEMnYbxzaTvIps1fvvhTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
