apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:6CfK7uaUOo5SP66ofq8asY5I68N6Zpy9pgC7pXjpCnGmaBTfpN+KIg==,iv:3vwCR6xLSG1YIH7fYYggv9SMjQvoKwCvlT/qxoyK6ac=,tag:h1MF8ATL4eo7mqmCXEk2aQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T10:46:13Z"
    mac: ENC[AES256_GCM,data:3ZRUSKrCmRvsCT5q93yTV4ZRwvhrZhFeLngzZT42WA5b06P20cJ04s5e7zGfBrQdFboIWjnDcWVGAVvjnIsU37AeF/TwjKen2QIG2EHDM7ub0/NOXjdhcGCjs4RHI+RNRBh5xXH7iKIrebJffYB7PW0FKsqbLyexJv7dmDC1dKc=,iv:R0vEgIEJSWFT4wmKSWExRrsjFAgaFllgZnAW82CFsuc=,tag:+DP/cz/5jQf7Qif2O3jflg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
