apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:AdytOx6m35sxX2eQyAc9GZ9DAKFHmKQ8D8o6O4i4fPCKLTjoq+wDaw==,iv:DUfj+0ahRLh0I+itzlmAhwfno8qiJvx/PdL6zv6CKBk=,tag:0CnSlNmuMZ344BlQkytAvA==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T22:36:28Z"
    mac: ENC[AES256_GCM,data:LJiwX7FDHcICvITc+1IzdaF2wB1i/SBD1Yi1u2iwgqWw6q/QWBADMev1PTUn+cNEojJLwxz2I09WdZKICp3uCu8Om/C9P8gJ04CVj1Ntiym2U1Oy+YmWVYkrv+d8+OMsqnerdq1PdwX/Jl9TEdgiYAxBQj3KAAy+EOZPpCU4Sa4=,iv:zPDzsbzu2889Z2xcbRUewVmcAnNCklasC4eKKxVGzN4=,tag:qRT1rIttwk7kn5lMZPqACw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
