apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:vKlIaLbuA4YqjYndVYLT39Jelx0v16/lYX5EMrvUf9NcStA2orlKNQ==,iv:HOD7L0paZW+i/GpzKd8xlJ1lEmQvR57qF7qmWBUPMAU=,tag:7OtD54bJ1Dz94iXNbtLJDA==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T22:46:04Z"
    mac: ENC[AES256_GCM,data:OgWeSPVOx5whJ2vaOuB+gQ+XljYnlnlOsMYs95YbPCP3nXa3JNUenh4FqTkaeKppad59/yHzlWRx5Z5bjlCQibLFw9/l+s02zoOwM8NFXCpU3jsx0J49iMkVjmlNv5rTpke32A9s6BRmKhbAeYj69JKRwiCt1+aP1pt8PDbp5Rw=,iv:YvUB1uGBNGsvsfKHBHr5dyiELi21cJQJfpmeOZB5OM0=,tag:LRaH1lQ2ji2CPlseLq4kzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
