apiVersion: v1
kind: Secret
metadata:
    name: gatus-secrets
type: Opaque
stringData:
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:9U0NmXrFfn5MFQqCr9nQCHmv0w8X08Me8/rGlvQu,iv:lS2VeS3E7zwZQJg/KlpZn1SUremNtss4kZf9XqyG7c4=,tag:Du0z3TsWObJvJRH1SX+iXA==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:AQkFo6az2vgKyVpPOqTpS9Q4bvR9hEk20MQiD1pQ,iv:2imAvg9A7e3SDPCEFE3g46megfXY80TuQf+Um9Lp9zk=,tag:emJZHtcCJKdecukSFYTVOQ==,type:str]
    GATUS_DOMIAN: ENC[AES256_GCM,data:XMV/QgpEWIxRgYlb4pne2ux9,iv:WxevEwm/SJKPVJj1r+PxGpmxGE8v+atmG91GDIWjlgU=,tag:NBjInJjN42mQjV91LOlqTA==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T23:03:35Z"
    mac: ENC[AES256_GCM,data:Jza44Wtgr1dzx5IId6FILJoF4xHqI3TSjQODgp0ud0J4GTJc8UrXccDodJmuY/PxfIxIKVFmyG0RUdAjO8KtwKai4Mj5YXAIrHQXUzLjLOFHbeTRaAiWLCA450lVlTXLghDuqcQoEYy2YxXyCadHYh7WW/qGTX+QnLmqiNpj8os=,iv:cy1J7AwUlSMJwXM+V4OEXoHXWWqeS9cXyITAhUSoNzw=,tag:MhlPrgRnX/9lhCoIgEcQDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: gatus-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:fU+XudUNVds=,iv:u1E2zJIcxOOeUvwho9thHw4o+sO6yIskzhBsnKD5Ejg=,tag:wzPGYUfy2q1JrboWNqctrA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Eyevs0BpIDPL/fjZU+9w/0q53vC+jRvj/EI/5h8un4RPmGe2i6j0ysoMNc3QmKWHzBUsKn6aphQ=,iv:3TkZjKRVuIaNtrsN8beO7RXcjauZaUy0k5CH+hCHwfw=,tag:JEJRQCW8hOyo/Yb7m08rCg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:1nMxj9DPS9W4AK7AUWznjA==,iv:ruXlDEvEVnB33C6ox/kXQ/2vJ1JFTBCJdUqw9gi7NIw=,tag:EdZM1wz+eo3OlJWoVI8w9Q==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:NyREUnm63xeWDdivkTLhntvdMRTwl/vuDl4oz2wcEKa2oJqEovMM5iCnhIc=,iv:FaBNOM0Q+6/CQVLrDuSe9xzHt5t3t3fUegU6SgRLQVc=,tag:sostQ6cbBp3Pay/oikaG6Q==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pFwxhGOwHKAu2xIyBftXJX/vVh2j2ZP9LA==,iv:yu6KuqH2ptJ+SYum+MVAdH0EYGNRDml3ZXxEivJXl58=,tag:IrJxPc2sWt01Y3ZRZdlmUg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T23:03:35Z"
    mac: ENC[AES256_GCM,data:Jza44Wtgr1dzx5IId6FILJoF4xHqI3TSjQODgp0ud0J4GTJc8UrXccDodJmuY/PxfIxIKVFmyG0RUdAjO8KtwKai4Mj5YXAIrHQXUzLjLOFHbeTRaAiWLCA450lVlTXLghDuqcQoEYy2YxXyCadHYh7WW/qGTX+QnLmqiNpj8os=,iv:cy1J7AwUlSMJwXM+V4OEXoHXWWqeS9cXyITAhUSoNzw=,tag:MhlPrgRnX/9lhCoIgEcQDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
