apiVersion: v1
kind: Secret
metadata:
    name: gatus-secrets
type: Opaque
stringData:
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:nrvO0ezyUGaOq8UUL3sdXOc3bgsJDeMB2TOF+zic,iv:0XBwv+SLphuIJAITBiJYRx3OFU/lWSvzu4WNhXnlFDI=,tag:Lp6RRxLFoXSxjNLilIohpg==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:Cc4ISiOvsbrTm5A+UWSfQRAlH86StragRXwiASAs,iv:jU1fAHNknQXVrdwWtLfQdrsgdH2HSNJUQw8XvT15pZw=,tag:V2ukNp7OqUZxoO/p5BR45w==,type:str]
    GATUS_DOMIAN: ENC[AES256_GCM,data:6B1cF3qAxcX3hqvn19i1WMIG,iv:10XDoaOfdTqCZTfC8imTbXTMIJGSOkle1iHq1IHPDg0=,tag:MpqkbWAIfE5X/nc0aOxtrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T21:08:18Z"
    mac: ENC[AES256_GCM,data:0ua+B0HCWtkg04sqCaSsa0oEfjwV4CIhBtJxlLuOd1146+2ZgPUWRTRfGMSq5EoIcdMmJ87ri2+Brqy/6/PIzzpU5gyDuKQgiJAT5FfJqOkMfROV/kka3KgTDoVs0WoXPY/1tyZHSIBPPiI+qaLZzDdLq531D84NBl8i12KdIY4=,iv:7Hae+A5faL7/2HUPjEUlJZbEzrxGYytPzZ2V9TmibMw=,tag:vTK6Gzvpu64MQ39c/MnAEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gatus-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:DuZD+pEiuVQ=,iv:fV9xi+i8E7+6sAD6YzN2YQ8FbGyTlmpG7vWMyf+W3To=,tag:oZ3cBfDaFBzu+EhMmBxhFQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:R8eA8Gym2ngoYSAhssfwR83sFMWF2fa/H9JpB7Pr3kEjZKypE6M9hD5rDItMsY7f8TrJXdC/rf0=,iv:yZeFHmLW1k8AldeApFXwg7QKfdC5NAZJb5CNDtD1nvw=,tag:ryED2WHQKCqH9SSM24+LnQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:QyMcWTGotpiiuukjIX3WNQ==,iv:aOb65wt4UI0edwRLsm4kN8KHXmJ6Vivjexkw71F6KmE=,tag:A8+3yJlLFFGHIgqX8DzVcQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:dXlRKl1tRSktYy1F5nfZ9jL48vqjQsS31VEX7nOGl9zy+ECtfAI6Z4MMHrM=,iv:+Tl5nxUVqq1DVXNI8PQkt8zr75nSIqCo97za1fDl57o=,tag:/2ZEsNEe+xsKj5CRY10hlw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:MvbObNH/DyOIVIH97SrILnr+R8uzQqXmRw==,iv:8Vws5zWPPqroBzqjEcDHUJqOqeytNjbQH9BIK4d/8R0=,tag:Kpp1qO0mfeny4PCuW6jS1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T21:08:18Z"
    mac: ENC[AES256_GCM,data:0ua+B0HCWtkg04sqCaSsa0oEfjwV4CIhBtJxlLuOd1146+2ZgPUWRTRfGMSq5EoIcdMmJ87ri2+Brqy/6/PIzzpU5gyDuKQgiJAT5FfJqOkMfROV/kka3KgTDoVs0WoXPY/1tyZHSIBPPiI+qaLZzDdLq531D84NBl8i12KdIY4=,iv:7Hae+A5faL7/2HUPjEUlJZbEzrxGYytPzZ2V9TmibMw=,tag:vTK6Gzvpu64MQ39c/MnAEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
