apiVersion: v1
kind: Secret
metadata:
    name: gatus-secrets
type: Opaque
stringData:
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:nrvO0ezyUGaOq8UUL3sdXOc3bgsJDeMB2TOF+zic,iv:0XBwv+SLphuIJAITBiJYRx3OFU/lWSvzu4WNhXnlFDI=,tag:Lp6RRxLFoXSxjNLilIohpg==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:Cc4ISiOvsbrTm5A+UWSfQRAlH86StragRXwiASAs,iv:jU1fAHNknQXVrdwWtLfQdrsgdH2HSNJUQw8XvT15pZw=,tag:V2ukNp7OqUZxoO/p5BR45w==,type:str]
    GATUS_DOMIAN: ENC[AES256_GCM,data:6B1cF3qAxcX3hqvn19i1WMIG,iv:10XDoaOfdTqCZTfC8imTbXTMIJGSOkle1iHq1IHPDg0=,tag:MpqkbWAIfE5X/nc0aOxtrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-23T22:08:25Z"
    mac: ENC[AES256_GCM,data:il78bV0eAW7/lvVXkwJXyqtq4PJMwmIe4LFAK9F9+9UVcRBbIkH1oQPaycdBNZqidjypiBZa+6PWKpXXPLTiPq0J1DGYkkZ2BiaZAg+jABDLesaHyqDWv9sba7TrGawwPjneZ2krPXQWfRsqv6satyxIRMBPWKzfxDxMnsubeLk=,iv:sF/yfwar6Mz5oX63tUbpRbQkN599b6wDX31ucFWUtTk=,tag:VCxW+tpo0OAE5W+MNfWzhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: gatus-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:DuZD+pEiuVQ=,iv:fV9xi+i8E7+6sAD6YzN2YQ8FbGyTlmpG7vWMyf+W3To=,tag:oZ3cBfDaFBzu+EhMmBxhFQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:AqjwZULnn3ap7Mc+h2/Oc4Ixbem60HVFddjLO4ebc81N7J6MhxQ3wil/TeAMtVRZWBvJY45OKO4=,iv:tXvxUVKBmy0FpEPFuQhMpxKVSY35mr48VQU8GwE0zps=,tag:M/7bmmz4j1uJmHD6lBGu9w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:QyMcWTGotpiiuukjIX3WNQ==,iv:aOb65wt4UI0edwRLsm4kN8KHXmJ6Vivjexkw71F6KmE=,tag:A8+3yJlLFFGHIgqX8DzVcQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:dXlRKl1tRSktYy1F5nfZ9jL48vqjQsS31VEX7nOGl9zy+ECtfAI6Z4MMHrM=,iv:+Tl5nxUVqq1DVXNI8PQkt8zr75nSIqCo97za1fDl57o=,tag:/2ZEsNEe+xsKj5CRY10hlw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:MvbObNH/DyOIVIH97SrILnr+R8uzQqXmRw==,iv:8Vws5zWPPqroBzqjEcDHUJqOqeytNjbQH9BIK4d/8R0=,tag:Kpp1qO0mfeny4PCuW6jS1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-23T22:08:25Z"
    mac: ENC[AES256_GCM,data:il78bV0eAW7/lvVXkwJXyqtq4PJMwmIe4LFAK9F9+9UVcRBbIkH1oQPaycdBNZqidjypiBZa+6PWKpXXPLTiPq0J1DGYkkZ2BiaZAg+jABDLesaHyqDWv9sba7TrGawwPjneZ2krPXQWfRsqv6satyxIRMBPWKzfxDxMnsubeLk=,iv:sF/yfwar6Mz5oX63tUbpRbQkN599b6wDX31ucFWUtTk=,tag:VCxW+tpo0OAE5W+MNfWzhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
