---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app volsync
  namespace: flux-system
spec:
  targetNamespace: volsync
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/volsync/volsync/app
  # dependsOn:
    # - name: snapshot-controller
    # - name: minio
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  prune: true
  wait: false
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
