apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:LKWDm/uc8i9TO5xp9m8jVvaoodaQZ9xDnzD0w9Pj8zND7i/NygKdf9F1PVK1wGjK3ExbZYB1ZT5QiK2vVU4JL1Q963W7MgGDa3UVh3NOXS4hMVS7UPxsxM0x5HbhxLl0sMRPyM1QMXCxta+A57oLlhthG2bel92obiUsakQuOEFkZ/eYwh/W48W/AYreCoeFhMnLXEuSBi+YJqx/YAZVEU1YNG1wu3rkGyesyKUnYg6dkyxPqsVEeYF6//Iihd4a,iv:Jd8FqK3zZgquLEUONfe0dUY3MOP/NYyzzVcgJ/L3zYI=,tag:t2ZCzzkwGxS/TmI84cZJpg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWFZGdk0rVTlSNU0xL0pk
            N2R2Zm44azhtKzhwaGU5WC93bCtPVXJXaFNjCjI0Y2Npa3FueUdsVCsrQm5uWXFG
            TDlLdlpneVl5MXM2RzJwSFQrc0dQY3cKLS0tICtpRDdSMTRTbVNLTXlCd1F2endt
            aklHMDMrNkJ5UlhQVncxNXVDci9QUzQKgWrjO4jRcVJka6Y6XJFenUOhWXEH8YE+
            5f85n6o3O51+8+Wk+QhbGPHjoT27vC+TUCo2UIa2u8OWGWgjjtXZJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T20:54:10Z"
    mac: ENC[AES256_GCM,data:rF7o0BUM+uysfXn0jMYf6Xy/tRQw7ufTfEmZtK1YLAVUWIhQGgwc+ENgt4hMX0IDmuKRTkZNE0GtiwjUzlxXMnY8zK8UZclnV8HAfN07CHGl70/OYN1QBbuu013e+7uny8cdbpad3TJKUSW8wQuDxGWfzPUmRkf4k+VbQ2B2RM4=,iv:jdMXKv0AtHvDeq/6qgWHBcLg5UMRcE+p7o3vi3peLug=,tag:ag0RDCpjIb4F4PcFbqUGZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
