apiVersion: v1
kind: Secret
metadata:
    name: monica-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:9VRh,iv:kV/mNQkSRoAsHhYDvZwmR8vVl2M6zLbnzJwGlZMbG6k=,tag:TAKW+tuL7CJzBwiXw8QH+A==,type:comment]
    APP_KEY: ENC[AES256_GCM,data:GMlJIgJdBLAEk6sZAT36q/T/PZ0hb7pzsOoRCizOorI=,iv:R/yy9Utb2P9kMrNFtKfwBNpgnm+tVrrW/IlEyMmifEY=,tag:mQDl/XcG/8PALtns+GHqHA==,type:str]
    DB_CONNECTION: ENC[AES256_GCM,data:iOzKVc8=,iv:Y0H7/AGCgFgVqREpYr3SHXp8hhZLTTPJqZ1xyGDgZ0c=,tag:/f5lGl3vlckXV2O29ntjrg==,type:str]
    DB_PORT: ENC[AES256_GCM,data:3TIgZw==,iv:UwLfgKQ3adCsS2bGdEcwH6GhUkoljlJu/CKKmlOLSV8=,tag:wvQmMpQ7fWwtaX6JX+q7YQ==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:clDYHrNR,iv:4bUEEhmMIbdz4DbXBIZDro3SK1VqDTMmrvFxBQtZdUk=,tag:jbMDOTbhc0x+Rbin4g6qAQ==,type:str]
    DB_HOST: ENC[AES256_GCM,data:XCgL+wZjrTnmI489aqJxKCy4GQ==,iv:r0mfIcWZaNCFGyDgJfjNPUK09TFIhLI6VsYcvySvYho=,tag:PBMVcQ0A0zP/cpHcI753pQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:F6ocW0T9ydZ+jfNCJKkrvH9K7FY7dcjd,iv:bb8WbBLRGFatrvSW62J/CQI1AukrbY8jAWvEQnIoe1M=,tag:+F8U59fBzZ1JbFTMfis4Tg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:ItKmhJZ23u2r7tCYeQ==,iv:ZUc6vejFcFhJhY1PQG7GE8OtS/EJZp096fpP+YoHXOs=,tag:BJHitski4NVJTTw0g1zbHw==,type:str]
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:LPmf,iv:Iq/lPEwIq5fnRqWSzs3t5vJUMQ2t3OJgLfcnnJv3MAQ=,tag:y1TpKbrraFzQgHinqovS9g==,type:str]
    MAIL_FROM_ADDRESS: ENC[AES256_GCM,data:fU6mzERN/AB5C47uoNmImvxb1oY387RYEwM=,iv:MaQvGCDnYTT3AAnk0EWB8cldvE4V872JBhuVaGLPASE=,tag:crAtN3Wyg1KFK1LZP2a+0A==,type:str]
    MAIL_FROM_NAME: ENC[AES256_GCM,data:TXf1TL8Z,iv:2hvsWRLt4W6ekl8FRD71QndrVvN1czQmyi79VTw1zpU=,tag:VX2hBdEyElAZWkEcVmSbuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-29T23:00:37Z"
    mac: ENC[AES256_GCM,data:lQg1EA9yutvxf2lK3UX80FyMjlLGQHeZNn0WiBjOVLcA5a4MShiy/CcYYHJs1ReKYqyDS0+Vhf6G6p/DuH/Y8K5Z+/ELaqTKbcu7a5gUVUVN7qDyA6MXKrWpgq1OCVIRAUEF8nQGeokV774NV0F07DNEzX1aAt51Fzzl1/HTrj4=,iv:Ahi8yg0c3bDCEdu+zJI62RMm38jCaEKYOqK6s1Eo2bg=,tag:R3k20yUby+FTTXO97FRdaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: monica-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:H8mOIi/UrqQ=,iv:LCmt2x94mrXy0n6LernYkZrBG4u/Zhlb7ClD81yY9qM=,tag:jkeSFzHEGNazkL0lKN7XlA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:+A4zI5louJUnO6Owaj0SN/iRjupXLwpf3AKMmLqU//5m74Sl/0IBdznUm6o0wK6KvmzpCzay00Y=,iv:6/S341uiAyaFL8UNCEfvDKDgb/2DI1+tAjpnXjax9sA=,tag:v6YEc/8vdqUdBVEDf5RcJA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:IwvqREFeVoPU36vnDIfFzrBkJa0=,iv:Oz66CwA57Y5kcrJIIby38MQDXYMOVRuecEBJ2Hl3Ja8=,tag:HcpG1xd2/lStCA+0wEwMHg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:nIg6lLwWiA5PyURpfs1WrOG/4oEtmMlFq6gZgVoShAg=,iv:slbJX42bYemQ5MLMxObxaTPNqwvEM8m76GQcy/KaDx0=,tag:cAQbQ35JhWtpyhXNIzIjZA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:8mj0Bl82uCvmV1G23bCQSSTfO4Emzx7i1w==,iv:R5wETHoKulLtr+zxhMoAKNAJQl0Nz0JIVIb9uq7hzs0=,tag:WTWtk0HDsGWRmP71TSeIxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-29T23:00:37Z"
    mac: ENC[AES256_GCM,data:lQg1EA9yutvxf2lK3UX80FyMjlLGQHeZNn0WiBjOVLcA5a4MShiy/CcYYHJs1ReKYqyDS0+Vhf6G6p/DuH/Y8K5Z+/ELaqTKbcu7a5gUVUVN7qDyA6MXKrWpgq1OCVIRAUEF8nQGeokV774NV0F07DNEzX1aAt51Fzzl1/HTrj4=,iv:Ahi8yg0c3bDCEdu+zJI62RMm38jCaEKYOqK6s1Eo2bg=,tag:R3k20yUby+FTTXO97FRdaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
