apiVersion: v1
kind: Secret
metadata:
    name: monica-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:9VRh,iv:kV/mNQkSRoAsHhYDvZwmR8vVl2M6zLbnzJwGlZMbG6k=,tag:TAKW+tuL7CJzBwiXw8QH+A==,type:comment]
    APP_KEY: ENC[AES256_GCM,data:ifD67jDDUySlGKtRutNLIlv7CIAVQZL0uxRrTpIyeI8JrFgNnTdp/u49mfE=,iv:/8md5RfXYVCU7ZWg0nh0Hgv2vSrw3KazJgfG+xYwJrA=,tag:sY13/nAJbwTZdf7Ak71i/A==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:RWc2P78gYT9h,iv:62ouN2dmuZ/egeurXcY23hg22q6ZELwvXlKuCYBSqUQ=,tag:AE4eutSRdRN5Us2N1BfAlw==,type:str]
    DB_HOST: ENC[AES256_GCM,data:htGoup8bRK/ploAKnHF5p9nMvv0IwQKYFx3eb2ZICaTH3eTy058=,iv:DGXYaDMjfc20CNRgGfB8yhmgM2D+80OsI8xznuKYqdc=,tag:fJ7q2GfWtL/uQee2HDNC6Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:eH6OoxrV4GtImXf1DfWnarabK70NWlCceQ==,iv:3LD7p44Rsxmtx+YoBU06VHA8QUSz+unZHF0t1CZaCJ0=,tag:xm2rZ5ASQHXQ1b0CY/VrBg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:pQEfv6CNeynywHhZsjYOjRU=,iv:ZjHmnWNfMGjSdQrL0x1JrJtv4M397pBY6neOhTXlbe0=,tag:1X+0DT1SYvVnguIskxZoyQ==,type:str]
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:LPmf,iv:Iq/lPEwIq5fnRqWSzs3t5vJUMQ2t3OJgLfcnnJv3MAQ=,tag:y1TpKbrraFzQgHinqovS9g==,type:str]
    MAIL_FROM_ADDRESS: ENC[AES256_GCM,data:M0r2KuMYIdqOpj43A0wsjifo6oqi87yuWps6rg==,iv:b4iPi19ZuLimESf506rGGMUGWUbVZ4IcmaEptFdXnFQ=,tag:FbReL1TLF5CuUsgV1voZ4Q==,type:str]
    MAIL_FROM_NAME: ENC[AES256_GCM,data:TXf1TL8Z,iv:2hvsWRLt4W6ekl8FRD71QndrVvN1czQmyi79VTw1zpU=,tag:VX2hBdEyElAZWkEcVmSbuw==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:4se0eA==,iv:JYEqscV45Uxh+y0pLJK1IojaH9M70quHkkba0W79h/s=,tag:9HSias+nm6AIRTrjjKS/yA==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:DmH55A==,iv:p9Y1lAJYY/KS00Lbuq5VYeRxBW4yd13kTOgKwnvUTO0=,tag:JLb+sIfe0A3xu0DtHjRvuw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:NGndVNk5aMye7Dx17DjRigZ0J5k=,iv:TnKhqTTlwkWmkIQlMKlO7o6tISS9QvYCQ/aidW55dpc=,tag:7QxcQwixk8uz/S5xru1gMQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:zeT7KG32p4dNSD5RGk0MgnyiKRnaZwSLfrjHhCingUxfHCBn4HO6Og==,iv:wLNG24anABIHsTTSyUaW104QVY1YMzmpD7E4j+M8j+0=,tag:0g0o/S/qgwB+Lg/xAQbcZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T12:41:48Z"
    mac: ENC[AES256_GCM,data:8Z7qh5OHKB4lddVefurLJ3YSAB5AZpd7xfYl/WaKrtKHuWTt5xs9uyZaXo3U0qC3L5+p0I2yBk6aqFu3ht8QANe5m27SzpnQStyR0cDvPgRsx0KH8Kq04P+U0n89Eozdm/PLl6FObVDARhGLPmzg3wEmNuS4zMwMvteDkJnXVCA=,iv:G7iDQKL6FGwQXNwKhPbXilZIn5LyTesNkXe609CFBnE=,tag:o2nlyfrMdJ9Sx9stbRWMVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: monica-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:6LwcVxdHnzBhd9FH,iv:hZaGcnEuPIdN1/5GeK6YQxPx6PT4wAaKeqIIvNTjKEE=,tag:S2ylaBlCNtcFhCN2LYVnkQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:/+RZFuUMEdSOGvWBO1Yl9d6DTHGIhGiLBxTlMqr86kG5nR06YN704O5gmkgJYlwntq3FPJSjg2o=,iv:TOYlA7wWHgz59Y1WbRriFBsUffXoovr/kgF1d6u5ftU=,tag:SqqHAH4k+sW5nZKzADfL5Q==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:8jl5ms4sqJShpcOn,iv:YDm0tcvpk0HuAUPzcw7zLSVQg+gzS53AyyxuNb3CVLo=,tag:wv/LDB/nwX7XsIlFtePuOw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:mXZjUqqzpzcBt2eaNZX9DmyG6MANyOT/GSw8mpwncFs=,iv:2YRiSlHkVvtXAuP+3liifLF22CnxhsKKQOTNTWR89MU=,tag:D+B1hk9LTf0E4nPOrvsGiw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:8mj0Bl82uCvmV1G23bCQSSTfO4Emzx7i1w==,iv:R5wETHoKulLtr+zxhMoAKNAJQl0Nz0JIVIb9uq7hzs0=,tag:WTWtk0HDsGWRmP71TSeIxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T12:41:48Z"
    mac: ENC[AES256_GCM,data:8Z7qh5OHKB4lddVefurLJ3YSAB5AZpd7xfYl/WaKrtKHuWTt5xs9uyZaXo3U0qC3L5+p0I2yBk6aqFu3ht8QANe5m27SzpnQStyR0cDvPgRsx0KH8Kq04P+U0n89Eozdm/PLl6FObVDARhGLPmzg3wEmNuS4zMwMvteDkJnXVCA=,iv:G7iDQKL6FGwQXNwKhPbXilZIn5LyTesNkXe609CFBnE=,tag:o2nlyfrMdJ9Sx9stbRWMVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
