---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vikunja

spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false

  values:
    controllers:
      vikunja:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: "16.3"
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: vikunja-init-db

        containers:
          app:
            image:
              repository: docker.io/vikunja/vikunja
              tag: 0.24.4@sha256:c93c58841215592c51a40fa978da25efadd1fff2460b42443c344132f322eef1

            env:
              VIKUNJA_SERVICE_TIMEZONE: ${CLUSTER_TIMEZONE}
              VIKUNJA_SERVICE_PUBLICURL: yarukoto.${SECRET_DOMAIN}
              VIKUNJA_SERVICE_ENABLETASKATTACHMENTS: true
              VIKUNJA_SERVICE_ENABLEREGISTRATION: true
              VIKUNJA_SERVICE_ENABLEEMAILREMINDERS: true
              VIKUNJA_DEFAULTSETTINGS_WEEK_START: 1
              VIKUNJA_DEFAULTSETTINGS_TIMEZONE: ${CLUSTER_TIMEZONE}
              VIKUNJA_MAILER_ENABLED: true
              VIKUNJA_MAILER_HOST: smtp-relay.networking.svc.cluster.local.
              VIKUNJA_MAILER_PORT: "25"
              VIKUNJA_MAILER_FROMEMAIL: Vikunja <noreply@${SECRET_MAIL_DOMAIN}>
              VIKUNJA_CACHE_ENABLED: 1
              VIKUNJA_CACHE_TYPE: redis
              VIKUNJA_REDIS_ENABLED: true
              VIKUNJA_REDIS_HOST: dragonfly.database.svc.cluster.local:6379
            envFrom:
              - secretRef:
                  name: vikunja-secret

            resources:
              requests:
                cpu: 15m
                memory: 24Mi
              limits:
                memory: 300Mi

    service:
      app:
        controller: *app
        ports:
          http:
            port: 3456

    persistence:
      config:
        enabled: true
        existingClaim: *app
        advancedMounts:
          vikunja:
            app:
              - path: /app/vikunja/files
      vikunja-config:
        enabled: true
        type: configMap
        name: vikunja-configmap
        advancedMounts:
          vikunja:
            app:
              - path: /etc/vikunja/config.yml
                subPath: config.yml
