apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
stringData:
    VIKUNJA_DATABASE_TYPE: ENC[AES256_GCM,data:etyCxFf0rm8=,iv:jRaLjsxi7xpV6kEUjKcs8FfGkLIMlXso8ZyydjIkzmo=,tag:BH/zR1z9qgdVnVGzocQRnQ==,type:str]
    VIKUNJA_DATABASE_HOST: ENC[AES256_GCM,data:pga/JAZobQxejYbenZ9yB4Zu2Fo=,iv:hbB2dk6BJ+16RJ7EkTb21rw9uA4kFDbkzQfvyZb/YXI=,tag:+zlFOam3r81WKOFdf83CqA==,type:str]
    VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:/fQek3WU7A==,iv:Q7mtdVoNRsdOKDKgGlH1t5I8wy2be5Lu7ZAPGGM5Jgg=,tag:k73SVRr9jh0sAXyweF9bZw==,type:str]
    VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:eZ+ww2dfMwpMeA==,iv:wVH2RgHG2/2NmoJ7QWhP9Jo+IQ9LWx3h7zimH8JKemc=,tag:+ioiRvoJYRViHCI1AG+7YA==,type:str]
    VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:mhIbRzKSZ6rQRY535zlBPE+pOzRemcqZqA==,iv:MVlsFDEhVG6wUmWp4ipqXAIANSCRyDIUPDkj+FzDlG4=,tag:u3vGtD8eH/ExdML79mws/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T15:07:13Z"
    mac: ENC[AES256_GCM,data:MpaIjOSSxPnLdimgqYCZdMruE6jjERm+V9ghvqAYLZFH+qTFkq8cFsJr7sFyuoM4EJZmwd0q8K7CxfGkVSd48yjMayE07VXfm9jAfSdnawctWzi34OXrYTBPQ/se5UGpuuqoyBFR8BzB+FFCN0ybLaOATLaOPCLOkTLmhEBt/84=,iv:ex/6kh4dPJig8bwdJs+K4tV6dlykkXEFy5FsdODjevI=,tag:HDUkguIcF/oEv3WEfJ6WUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: vikunja-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:3mWIVJLp+2a3Subq,iv:3WA5fI1bYDxhiIobYhQvSB1oHb2OXe/qsZFeAkVNmEU=,tag:SGubXqsa0jd0qHXPjsxMiQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:1Ep7sWlef+GlfPVeD05ZCcy1/wT7aNKuo3KHLhqyOr5JT6mJi0V/eL9E2y5Eov3Qgofgky7UE9I=,iv:FPmAUzK3XVVBjbqAGDrjNHeIwUkXsmRPkSGkiJV9VR8=,tag:/BDzsKj+yFqsTHqz3qW7CA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:xIoy4/3fbjtV+lsaOUZmyA==,iv:ju1UgumpE2lIgC+zH35WxwIEMkCm3Jucz6wi15ge+3M=,tag:UefR8NK/xIov4CikBuPfrg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:YEQL/kn9fw0J5f4bISED4KmOGL9xTI6qCldIMw5PE49MBqKP,iv:2sgkzxmdPFbzU36muGryMvV1zfAiNotxKhJiIcfRxjg=,tag:ZdEjNvN6oXYcj3JBgZd1xQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:0vsdISDqWPhwPOzcbn2NI4vFuojzaTS6rg==,iv:qGxaNqUp59UAdL/QMTnsyN7wqBNORCozQkFeK3J6cBY=,tag:/JahvbhXPs0iLEwROZ5tGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T15:07:13Z"
    mac: ENC[AES256_GCM,data:MpaIjOSSxPnLdimgqYCZdMruE6jjERm+V9ghvqAYLZFH+qTFkq8cFsJr7sFyuoM4EJZmwd0q8K7CxfGkVSd48yjMayE07VXfm9jAfSdnawctWzi34OXrYTBPQ/se5UGpuuqoyBFR8BzB+FFCN0ybLaOATLaOPCLOkTLmhEBt/84=,iv:ex/6kh4dPJig8bwdJs+K4tV6dlykkXEFy5FsdODjevI=,tag:HDUkguIcF/oEv3WEfJ6WUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
