apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
stringData:
    VIKUNJA_DATABASE_TYPE: ENC[AES256_GCM,data:cKNQTwJC1bU=,iv:hpX61e2dgcSuEDy48SdryHBBTkhjxr2jJA4fWRIbU78=,tag:/+vwlNFVdW5N+jxmD7a/yQ==,type:str]
    VIKUNJA_DATABASE_HOST: ENC[AES256_GCM,data:36aB7b8sTtUt1d8iz3oLSRQ9kA==,iv:B8KzwfOEEWoBFIPGIjwsf6utFGbnuG3JqNKjWTxnoiY=,tag:bLPN0UhJCIzH3nspW+gMCQ==,type:str]
    VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:NHaNblBNAg==,iv:AUZY7valkBqG7WMjCfMvlC8tbYslQjVYucpNJSzk8gU=,tag:pui16Zu+p6qAFgDhElr/dA==,type:str]
    VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:h4zyliE5LkTWBw==,iv:9oYgLCYNA9DG02J7GldM1l4cqWX8J+WBORU/6Kn737I=,tag:ikgMw/E0iaT7hEBoTfcByQ==,type:str]
    VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:86Eo9DUR40zNixAgBDwGLhXrEeJQes1wcg==,iv:lUZP7ZYzpum9oklONEl/hxf7eoY8zz5MjYT0mGjXQ2A=,tag:2ibKxKSF5TaI9kjGCnFdRA==,type:str]
    VIKUNJA_MAILER_HOST: ENC[AES256_GCM,data:PzWQROVVtKJ5KZ8x5PfkTas1ZsF0nIEWZEs5v9LmaWJnP1Cr8Bn+pw==,iv:upGYHAU0gpnqK+cDxemJ/xsxSQGUQYWYqOUF49Z5Gww=,tag:h7yQeeCuzswE4ba4UhZEkA==,type:str]
    VIKUNJA_MAILER_PORT: ENC[AES256_GCM,data:yDw=,iv:wFKkiVFqmlqQ+1MtRXmkpvL2pIX/ck5aKSZU5o50a2U=,tag:yYOu/qmcfcNuKZEH8HSbuw==,type:str]
    VIKUNJA_MAILER_FROMEMAIL: ENC[AES256_GCM,data:nYYnYJ6Hg8FCHw9QqaEgwrvffKatWIRNlUzB9QVgyyLPQ0A8,iv:iwKfnF/0sYEH+zCduKKxSnAGM6fPr1sy0jB8AwIZTW0=,tag:O4mgZrggSUQo1EbgHSqbsA==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T23:03:47Z"
    mac: ENC[AES256_GCM,data:GY73FJh/0/TCxZnTcYpOn+3uOpabKHViSx34cjLNlrh7iXg5EqW5mIFZC4+KsTsDg/3fFIQm09VbdJzCEMvfLYu7u9LARW4dtuA6vtBnsIIy6yjLu6k+cZMGiZtjmwKRHIoMLMOyNDwnAgpra1JyaJdkkIiu3nqU6Oc8dCBie6M=,iv:8J/Mas5If3hJE8fr45J9ulVPrV3ogwNIECTEUecIjBI=,tag:t9f+wdBQ3B1woi1ZAELfNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vikunja-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:74fb5yIISbZJLebX,iv:C98jd0QRcBIW4eQPJBqVlsg2v7kvzKW8HSwHX+ZPRvw=,tag:4ah9ZCQg9f2/uovshwwOhg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:+eVWqLN+wM37YnHMMoAdub40gpAKSJsWN4D0q681YTpawfKjDRyhwKtVGxwx9e6n5NMW2wkm748=,iv:hOqAsIDgf20frZ2Jy69+PuQA3tO23524O35RJWZrpMk=,tag:Mng6/ccfy72p+FcLvynvSg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:WmGpODwxlckUnda87ExBEQ==,iv:/Ry7MkaFTg/T2hKbdXNPgVnCFraP0xStEOVjW51oi/w=,tag:Tz+csZ+y44yw+F5DXQIfkw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:sS+hjKlC9gRjRTltkydD8RB1NAQ6qLxCYKkgRQCd79+hNF7G,iv:hflHJ3OcsdGvNrQQ1dJvxkYJzadStBdJnfIyoYRecE4=,tag:LJZbrWpr1inFFaJTuzMkhg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pFwxhGOwHKAu2xIyBftXJX/vVh2j2ZP9LA==,iv:yu6KuqH2ptJ+SYum+MVAdH0EYGNRDml3ZXxEivJXl58=,tag:IrJxPc2sWt01Y3ZRZdlmUg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T23:03:47Z"
    mac: ENC[AES256_GCM,data:GY73FJh/0/TCxZnTcYpOn+3uOpabKHViSx34cjLNlrh7iXg5EqW5mIFZC4+KsTsDg/3fFIQm09VbdJzCEMvfLYu7u9LARW4dtuA6vtBnsIIy6yjLu6k+cZMGiZtjmwKRHIoMLMOyNDwnAgpra1JyaJdkkIiu3nqU6Oc8dCBie6M=,iv:8J/Mas5If3hJE8fr45J9ulVPrV3ogwNIECTEUecIjBI=,tag:t9f+wdBQ3B1woi1ZAELfNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vikunja-config
stringData:
    config.yaml: ENC[AES256_GCM,data:6hD2WU5cz6XT6QtMLec3RTAWVCUfTaCLi/AzNO7dk3JDkeZw7vH2Ws4cYJUOG/Y6iNa0KxiaUWZNUqEF0fqDovL78Q/554O00ycJvpKVS+Tr3/pdRkVitel2khQuCfEWeoc7W7x3f/Osw/1NgDFR326n+5dKhpAGn2sF53zWIzj4lGjN/wtkZfJMnkdLHyGklople07pVYrdsRituVAXjQ6ZEYMKh29kzybAT7nqZyQLhaY1uC08n0+YbfDBLOijTtvDAaVs37ej9urYDxl+WU9N2jINVcrNkAYxhVNaPS6/NEz7eB3PHKx2yOg/oxi/MXdONP0HD2HyVis1j5PW1m5kx5f5ikG5pmzRiNKAaGrj55KKUHcwcWiAlbp48xPliu917lC+z7wQ5+wLFvKc3gG37hSK5nRg0omlBWMO7igAbmM/9WilExV2gPJ1IBLXQ7GQxUlTbAjRg/TynT45zhOjvHP5Xjz7LWkFzOLgg3NyHZrWMeQLtt7MzwYFVHeSVhHsV3xe1lUVYfsU9yXP0Zz+khTrUP5ZEwXD5M0GeicTWSkyhwZL3o4XA7A88cpe8kjdhcUb0nSQ+C7kS5bGbIFJkWVX2gf4zMEM9MEgapRFiyg1hCbKPbtbvNjwFOMnzN0Apu5RbzOl7tpbOAsCWA==,iv:/jO326Xi2RSCVhhuhNo3NV5gmfBwYK4viWmzDNqbiys=,tag:3CtObX8suiWZjuG6MPTjoQ==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T23:03:47Z"
    mac: ENC[AES256_GCM,data:GY73FJh/0/TCxZnTcYpOn+3uOpabKHViSx34cjLNlrh7iXg5EqW5mIFZC4+KsTsDg/3fFIQm09VbdJzCEMvfLYu7u9LARW4dtuA6vtBnsIIy6yjLu6k+cZMGiZtjmwKRHIoMLMOyNDwnAgpra1JyaJdkkIiu3nqU6Oc8dCBie6M=,iv:8J/Mas5If3hJE8fr45J9ulVPrV3ogwNIECTEUecIjBI=,tag:t9f+wdBQ3B1woi1ZAELfNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
