apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
stringData:
    VIKUNJA_DATABASE_TYPE: ENC[AES256_GCM,data:cKNQTwJC1bU=,iv:hpX61e2dgcSuEDy48SdryHBBTkhjxr2jJA4fWRIbU78=,tag:/+vwlNFVdW5N+jxmD7a/yQ==,type:str]
    VIKUNJA_DATABASE_HOST: ENC[AES256_GCM,data:36aB7b8sTtUt1d8iz3oLSRQ9kA==,iv:B8KzwfOEEWoBFIPGIjwsf6utFGbnuG3JqNKjWTxnoiY=,tag:bLPN0UhJCIzH3nspW+gMCQ==,type:str]
    VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:NHaNblBNAg==,iv:AUZY7valkBqG7WMjCfMvlC8tbYslQjVYucpNJSzk8gU=,tag:pui16Zu+p6qAFgDhElr/dA==,type:str]
    VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:h4zyliE5LkTWBw==,iv:9oYgLCYNA9DG02J7GldM1l4cqWX8J+WBORU/6Kn737I=,tag:ikgMw/E0iaT7hEBoTfcByQ==,type:str]
    VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:86Eo9DUR40zNixAgBDwGLhXrEeJQes1wcg==,iv:lUZP7ZYzpum9oklONEl/hxf7eoY8zz5MjYT0mGjXQ2A=,tag:2ibKxKSF5TaI9kjGCnFdRA==,type:str]
    VIKUNJA_MAILER_HOST: ENC[AES256_GCM,data:PzWQROVVtKJ5KZ8x5PfkTas1ZsF0nIEWZEs5v9LmaWJnP1Cr8Bn+pw==,iv:upGYHAU0gpnqK+cDxemJ/xsxSQGUQYWYqOUF49Z5Gww=,tag:h7yQeeCuzswE4ba4UhZEkA==,type:str]
    VIKUNJA_MAILER_PORT: ENC[AES256_GCM,data:yDw=,iv:wFKkiVFqmlqQ+1MtRXmkpvL2pIX/ck5aKSZU5o50a2U=,tag:yYOu/qmcfcNuKZEH8HSbuw==,type:str]
    VIKUNJA_MAILER_FROMEMAIL: ENC[AES256_GCM,data:nYYnYJ6Hg8FCHw9QqaEgwrvffKatWIRNlUzB9QVgyyLPQ0A8,iv:iwKfnF/0sYEH+zCduKKxSnAGM6fPr1sy0jB8AwIZTW0=,tag:O4mgZrggSUQo1EbgHSqbsA==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T17:07:16Z"
    mac: ENC[AES256_GCM,data:Gyu04i4C3KdX18M8UOpZbyY/jD3BBrIhpkD+Xt2InDy7SKx+kmJaksk54HELHcc4ebCmPdYdiiOB2hwl6vyoEuZ8b7RKHpgUAiifPyY2nFRWWYm7XrxWNsqTQpRhVg0k0IXVN0Ha9ib/b2few+BTcXTwamOrkUNsZynOkA4ZecY=,iv:AIhZTWiMSS2nD5hMps9P0iHMdpeXb/UgFXxvxlAz5GA=,tag:yktqsx0RO5VCidbxFyC/Gw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vikunja-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:74fb5yIISbZJLebX,iv:C98jd0QRcBIW4eQPJBqVlsg2v7kvzKW8HSwHX+ZPRvw=,tag:4ah9ZCQg9f2/uovshwwOhg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:+eVWqLN+wM37YnHMMoAdub40gpAKSJsWN4D0q681YTpawfKjDRyhwKtVGxwx9e6n5NMW2wkm748=,iv:hOqAsIDgf20frZ2Jy69+PuQA3tO23524O35RJWZrpMk=,tag:Mng6/ccfy72p+FcLvynvSg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:WmGpODwxlckUnda87ExBEQ==,iv:/Ry7MkaFTg/T2hKbdXNPgVnCFraP0xStEOVjW51oi/w=,tag:Tz+csZ+y44yw+F5DXQIfkw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:sS+hjKlC9gRjRTltkydD8RB1NAQ6qLxCYKkgRQCd79+hNF7G,iv:hflHJ3OcsdGvNrQQ1dJvxkYJzadStBdJnfIyoYRecE4=,tag:LJZbrWpr1inFFaJTuzMkhg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pFwxhGOwHKAu2xIyBftXJX/vVh2j2ZP9LA==,iv:yu6KuqH2ptJ+SYum+MVAdH0EYGNRDml3ZXxEivJXl58=,tag:IrJxPc2sWt01Y3ZRZdlmUg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T17:07:16Z"
    mac: ENC[AES256_GCM,data:Gyu04i4C3KdX18M8UOpZbyY/jD3BBrIhpkD+Xt2InDy7SKx+kmJaksk54HELHcc4ebCmPdYdiiOB2hwl6vyoEuZ8b7RKHpgUAiifPyY2nFRWWYm7XrxWNsqTQpRhVg0k0IXVN0Ha9ib/b2few+BTcXTwamOrkUNsZynOkA4ZecY=,iv:AIhZTWiMSS2nD5hMps9P0iHMdpeXb/UgFXxvxlAz5GA=,tag:yktqsx0RO5VCidbxFyC/Gw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vikunja-config
stringData:
    config.yaml: ENC[AES256_GCM,data:NEnx5rwl5sAj82Z+KECMs09g5KxQbzJFUEBVSeKRBJ6ZN/zjS+JnJ6C2HIUYalkDeu7Bmujerwe0jZ5jes1d9GEdHW8uAgBsZ5HDnEbPzxtCoLrgnfhnzZb599+QRH2rBGYJjlQF+StHisHzZtkJnjidPIM4d/QYOl/vzdyb6TQMTex9q3fwx8jy9SO7pOR0LesYhhJcW1qeH69wrFHvzQNMf6Z+/M+intI7KijFd9/yiKlmUVMxpof9zfjrKafem5FhBRHsuI1dMjPaA97RZxpL+xKUkoWSBhGK3w/V2z0UaBZasAxTXe2UBxsB6qIJ/YjWinSFO+QnsXCYlRFVYoGCFcNeDpfM1t/S8cXTTAPtswA1hcdIWdk0uCqbhiR9xtdeWgGdDoyleKKF0msWKQUx45rfuo63lZsgX/xz9LuplawxkpXp3CnXuAbSeb3nJnj+kwCB/nYsa3iBxtkKxmfntTEQYhnKYC5+zYmSI6PZ1v5bfzH7DkCRBrS2jW5hr9sqzn0xJXdyQNzuhGTJZ/CQc7u0awtvI6/75lOrF7R9kaKysaI7NJY3tDjdpykr6ZTyIgFUH68fC6ajt1ZIxYEFwogS+1l0zPSAU9LUyX0Uou5O0VkHUda3M5eVYlkVaEmwqyacznth3GxfCyDl/yTDbxcsPBJTh79SijJSTHjAbB+bdCZfEtztColIuITsbiuLM9qmqjH/rs1f4Mb7,iv:/GV6R6Tq3CTNbmwP2JGOIoD7W/zT0gfjps89woUVAsk=,tag:VQgpH+KBS8jcjGMXwj98hQ==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T17:07:16Z"
    mac: ENC[AES256_GCM,data:Gyu04i4C3KdX18M8UOpZbyY/jD3BBrIhpkD+Xt2InDy7SKx+kmJaksk54HELHcc4ebCmPdYdiiOB2hwl6vyoEuZ8b7RKHpgUAiifPyY2nFRWWYm7XrxWNsqTQpRhVg0k0IXVN0Ha9ib/b2few+BTcXTwamOrkUNsZynOkA4ZecY=,iv:AIhZTWiMSS2nD5hMps9P0iHMdpeXb/UgFXxvxlAz5GA=,tag:yktqsx0RO5VCidbxFyC/Gw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
