apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
stringData:
    VIKUNJA_DATABASE_TYPE: ENC[AES256_GCM,data:cKNQTwJC1bU=,iv:hpX61e2dgcSuEDy48SdryHBBTkhjxr2jJA4fWRIbU78=,tag:/+vwlNFVdW5N+jxmD7a/yQ==,type:str]
    VIKUNJA_DATABASE_HOST: ENC[AES256_GCM,data:36aB7b8sTtUt1d8iz3oLSRQ9kA==,iv:B8KzwfOEEWoBFIPGIjwsf6utFGbnuG3JqNKjWTxnoiY=,tag:bLPN0UhJCIzH3nspW+gMCQ==,type:str]
    VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:NHaNblBNAg==,iv:AUZY7valkBqG7WMjCfMvlC8tbYslQjVYucpNJSzk8gU=,tag:pui16Zu+p6qAFgDhElr/dA==,type:str]
    VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:h4zyliE5LkTWBw==,iv:9oYgLCYNA9DG02J7GldM1l4cqWX8J+WBORU/6Kn737I=,tag:ikgMw/E0iaT7hEBoTfcByQ==,type:str]
    VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:86Eo9DUR40zNixAgBDwGLhXrEeJQes1wcg==,iv:lUZP7ZYzpum9oklONEl/hxf7eoY8zz5MjYT0mGjXQ2A=,tag:2ibKxKSF5TaI9kjGCnFdRA==,type:str]
    VIKUNJA_MAILER_HOST: ENC[AES256_GCM,data:PzWQROVVtKJ5KZ8x5PfkTas1ZsF0nIEWZEs5v9LmaWJnP1Cr8Bn+pw==,iv:upGYHAU0gpnqK+cDxemJ/xsxSQGUQYWYqOUF49Z5Gww=,tag:h7yQeeCuzswE4ba4UhZEkA==,type:str]
    VIKUNJA_MAILER_PORT: ENC[AES256_GCM,data:yDw=,iv:wFKkiVFqmlqQ+1MtRXmkpvL2pIX/ck5aKSZU5o50a2U=,tag:yYOu/qmcfcNuKZEH8HSbuw==,type:str]
    VIKUNJA_MAILER_FROMEMAIL: ENC[AES256_GCM,data:nYYnYJ6Hg8FCHw9QqaEgwrvffKatWIRNlUzB9QVgyyLPQ0A8,iv:iwKfnF/0sYEH+zCduKKxSnAGM6fPr1sy0jB8AwIZTW0=,tag:O4mgZrggSUQo1EbgHSqbsA==,type:str]
    VIKUNJA_AUTH_OPENID_PROVIDERS: ENC[AES256_GCM,data:H8VPaFBFmCF0,iv:SZUIRxPsUTI+OgVJR69JtH7Eh0211WodM77kmVSrS5k=,tag:kxZDc7+E6s1ZjGcW+R7HKg==,type:str]
    VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_NAME: ENC[AES256_GCM,data:vEFhj5PNDfbL,iv:oazFgMNr+4ZzbSHDEjp4d4r1gMQrjPEh8XmRbU2UKz0=,tag:qqlXCW12G5MfIO3JBxIpsg==,type:str]
    VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_AUTHURL: ENC[AES256_GCM,data:0Btnvurae82KGOJIwJk5rO6A61DwdnuvKTv3OUF0OO8Ql1ynYEJnVm5zo22pTq1CH/LPgQ==,iv:9DXGiPQx+VDhFvJXrAEDksmg5WVbavRAueBSAOS2liY=,tag:ZGgAeSZibdKtUIegvhLyaw==,type:str]
    VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_LOGOUTURL: ENC[AES256_GCM,data:DJBmPSN25+tRBeLjd7W3LhsWiQuaETd4Igc8ULdcQ6yVrfLAgd/bz2O+f05c8VQG0tQTSBB++XxpcxsfXHhpsA==,iv:jMrYL3/raEAEu96NOtHsL7XRrunK3ERxREMwPIywcr4=,tag:ELxOFO/tVRrRlk4pp5j5Ag==,type:str]
    VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_CLIENTID: ENC[AES256_GCM,data:L/arMScOLwCQdwVKt60wRzChLq/c5MZ7kKc=,iv:sbZ4AlAXWU7d3heD1ChSR7ck4kbd4/osYV2nSrT3Jfc=,tag:btJ5anNkeyye/3TWTqeGhQ==,type:str]
    VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_CLIENTSECRET: ENC[AES256_GCM,data:fgQfdGqkxRgy3AtoZn72bDA3ElW2vo56m/PAOxKk,iv:EBPj/v1NTXY6+GQPMvh9ECueQjPl7oy+ZmG4rtoC5to=,tag:urH5xCjq7XrSshqO+343vQ==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T22:14:18Z"
    mac: ENC[AES256_GCM,data:MXB/yPF+fuoBdelIaSPPMfF9foe2fVQYT6+iB3Nf5X1F/PIUdCVDoIslqnUpXHI9d+O9lXGWT/zFWJ0feBE23v6oaW6PQKiYl3tI3PdAI2ykzAVRDc07z5cTTlKzQaaPT3/7wi1Jhj3V45gcmg/BeAkuZ792VQyKsvwXQxpRiHw=,iv:pHq2syokmw2r+P48IKb0bpN33I2fk/TjmsEw13iwYuA=,tag:myoFdt0cMislQ334VJnmPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vikunja-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:74fb5yIISbZJLebX,iv:C98jd0QRcBIW4eQPJBqVlsg2v7kvzKW8HSwHX+ZPRvw=,tag:4ah9ZCQg9f2/uovshwwOhg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:+eVWqLN+wM37YnHMMoAdub40gpAKSJsWN4D0q681YTpawfKjDRyhwKtVGxwx9e6n5NMW2wkm748=,iv:hOqAsIDgf20frZ2Jy69+PuQA3tO23524O35RJWZrpMk=,tag:Mng6/ccfy72p+FcLvynvSg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:WmGpODwxlckUnda87ExBEQ==,iv:/Ry7MkaFTg/T2hKbdXNPgVnCFraP0xStEOVjW51oi/w=,tag:Tz+csZ+y44yw+F5DXQIfkw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:sS+hjKlC9gRjRTltkydD8RB1NAQ6qLxCYKkgRQCd79+hNF7G,iv:hflHJ3OcsdGvNrQQ1dJvxkYJzadStBdJnfIyoYRecE4=,tag:LJZbrWpr1inFFaJTuzMkhg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pFwxhGOwHKAu2xIyBftXJX/vVh2j2ZP9LA==,iv:yu6KuqH2ptJ+SYum+MVAdH0EYGNRDml3ZXxEivJXl58=,tag:IrJxPc2sWt01Y3ZRZdlmUg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T22:14:18Z"
    mac: ENC[AES256_GCM,data:MXB/yPF+fuoBdelIaSPPMfF9foe2fVQYT6+iB3Nf5X1F/PIUdCVDoIslqnUpXHI9d+O9lXGWT/zFWJ0feBE23v6oaW6PQKiYl3tI3PdAI2ykzAVRDc07z5cTTlKzQaaPT3/7wi1Jhj3V45gcmg/BeAkuZ792VQyKsvwXQxpRiHw=,iv:pHq2syokmw2r+P48IKb0bpN33I2fk/TjmsEw13iwYuA=,tag:myoFdt0cMislQ334VJnmPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
