apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
stringData:
    VIKUNJA_DATABASE_TYPE: ENC[AES256_GCM,data:etyCxFf0rm8=,iv:jRaLjsxi7xpV6kEUjKcs8FfGkLIMlXso8ZyydjIkzmo=,tag:BH/zR1z9qgdVnVGzocQRnQ==,type:str]
    VIKUNJA_DATABASE_HOST: ENC[AES256_GCM,data:4axhvAK9QZaEI4h/L/tJTTQZjDM3,iv:bRysNnRo1i75EE2nIkYPHNlaiPJpBoTyfA1iD+QMh4o=,tag:8B/1HXsSpVu/FShLLbNlAw==,type:str]
    VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:/fQek3WU7A==,iv:Q7mtdVoNRsdOKDKgGlH1t5I8wy2be5Lu7ZAPGGM5Jgg=,tag:k73SVRr9jh0sAXyweF9bZw==,type:str]
    VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:eZ+ww2dfMwpMeA==,iv:wVH2RgHG2/2NmoJ7QWhP9Jo+IQ9LWx3h7zimH8JKemc=,tag:+ioiRvoJYRViHCI1AG+7YA==,type:str]
    VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:mhIbRzKSZ6rQRY535zlBPE+pOzRemcqZqA==,iv:MVlsFDEhVG6wUmWp4ipqXAIANSCRyDIUPDkj+FzDlG4=,tag:u3vGtD8eH/ExdML79mws/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T12:35:44Z"
    mac: ENC[AES256_GCM,data:neZxtcFzmmLANm0rCD7nfTc7fsIs/N7VVKC+1kTHxBAoZ2QOfNha+SkCqVNxty2Zdwoq/xAEnvjPS3S9sURvJqPqzBLcgV2m9bx1+oUfc2gS2p3vOeZ3N4inPdbgNWoiULB4CtWgLC4Jj67/CN/L7ipr/ZCxphG29pmOpnw9JGs=,iv:RhwKwrpN9IHU0Jf8Fqbb0goNh/2SKygzjOHxFW77z4s=,tag:gmwn1WOfcjePNrj5JUH6gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: vikunja-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:bf6egv8Yj+qP35IugVxcww==,iv:a5ixIemWb1FtL7n+Aje+bYt42PjZJPgosmRgaSePo10=,tag:kVkGmbLgeMMzMdkMi2spMQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:1Ep7sWlef+GlfPVeD05ZCcy1/wT7aNKuo3KHLhqyOr5JT6mJi0V/eL9E2y5Eov3Qgofgky7UE9I=,iv:FPmAUzK3XVVBjbqAGDrjNHeIwUkXsmRPkSGkiJV9VR8=,tag:/BDzsKj+yFqsTHqz3qW7CA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:HoD82cGsWXbetlV8lh49VQ==,iv:xsX7BggObzZHxYfAP2+ySrsFC9d4mUq34amhuTDOn4I=,tag:3RrAyXEbjC4LxqMx6IlT9Q==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:T5aIge4t48ctxHU2Q8QXokJ93DGVy1LBaXmBC+c8HO5bxt47,iv:lEnjTyy0SgwV1oIQqIMgwca+AcFoNORfYldOFCJCl5w=,tag:GgNLFK/w2M31jEUuEFabEg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:0vsdISDqWPhwPOzcbn2NI4vFuojzaTS6rg==,iv:qGxaNqUp59UAdL/QMTnsyN7wqBNORCozQkFeK3J6cBY=,tag:/JahvbhXPs0iLEwROZ5tGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T12:35:44Z"
    mac: ENC[AES256_GCM,data:neZxtcFzmmLANm0rCD7nfTc7fsIs/N7VVKC+1kTHxBAoZ2QOfNha+SkCqVNxty2Zdwoq/xAEnvjPS3S9sURvJqPqzBLcgV2m9bx1+oUfc2gS2p3vOeZ3N4inPdbgNWoiULB4CtWgLC4Jj67/CN/L7ipr/ZCxphG29pmOpnw9JGs=,iv:RhwKwrpN9IHU0Jf8Fqbb0goNh/2SKygzjOHxFW77z4s=,tag:gmwn1WOfcjePNrj5JUH6gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
