---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./firefly-iii/ks.yaml
  - ./ghostfolio/ks.yaml
  - ./hajimari/ks.yaml
  # - ./monica/ks.yaml
  - ./paperless/ks.yaml
