---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: &pv paperless-services-nfs
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: *pv
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${LOCAL_LAN_NAS}"
    path: /volume1/paperless
  mountOptions:
    # - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-services-data-v1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: paperless-services-nfs
  resources:
    requests:
      storage: 1Ti
