apiVersion: v1
kind: Secret
metadata:
    name: paperless-service-secret
stringData:
    #ENC[AES256_GCM,data:rdCUcmtCs6JKnQ==,iv:lB+gK3WuxdEZ8d+gClxmEcbe32n03pak3Yv12M5uTWM=,tag:ze+5LOZjYY0eRUlGzZIrOQ==,type:comment]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:NPcUIu1KN/OgJZ9L42sosD9fv+ue,iv:tMH0zaRoMHSmG5Q8KnQJ8HvwEgGouqJJ0oyCF8f6ibg=,tag:Kvq8uhDOr9qSJkprXwDYBA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:gWcL0uILciPso+mxNf4iH6vjKDb+EPl8,iv:T+Dl0DpJHNRcBRdTVlyCbBI6Am/m6T/oSTq+Nx0tP8Q=,tag:td0r2mzkReKFue+Z1RclHQ==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:3Yzmua8soMj6sdNIjEjWRpIigjmh2Ig27m/nNK6JU5Xybv6tflmseCGETIjYsXSx0WwWtEh/lyGyVyRoYBKXog==,iv:8D/bM4qQeQzoZFdKc8YgBLW06EHtf5rV3SIdqRCw7bA=,tag:erKkhc9tDT4owz93dYpEUw==,type:str]
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:Xmr1rtDfjAAuOKZ4SQlzsg==,iv:y6J1qKxpnEnQEtuo8CYohlxFJiYi10lbNDSYD14RWSI=,tag:hXHKAtsT/QPDoDgG3eKBPQ==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:G2ce3pS0PnbfwhtD9d5bQHZrf8MmQsMtwA==,iv:jgFVPwTBPNp9r7SKuiaBhrtwKSR3xUP3ZTgwkW6xOsU=,tag:TKq3T/JkXR01PxYT9XWlBg==,type:str]
    PAPERLESS_DBNAME: ENC[AES256_GCM,data:zaT8SPZSqxiX0BQz3keeriA=,iv:3y9HBHKgPnebeDCeKr4RdGRs3qKT/Zet4Kt7DLr5j4o=,tag:uy5WysHwe8oTgB7cVqhf/w==,type:str]
    PAPERLESS_DBHOST: ENC[AES256_GCM,data:VMPynLcuWUzgvLnnjk0AW5eOgA==,iv:arr2sz5XI0JMfYd5EnWk0ATKqMJZvsnvw57BiaRW2D0=,tag:P29onR/Ps0gWctN5V1NEsA==,type:str]
    PAPERLESS_DBPORT: ENC[AES256_GCM,data:ivqPjg==,iv:xFHycqboOLIrOpupYpeAaBgNADj1nPsrtgoVi8arQOk=,tag:j1h/MlEgfFi6/+26rr6fqQ==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:rJ+JAIKC5OldWSMNFmAV1QcAlrDhbRupSQByXqsa0GwI5zT11TlPzLfdhznGJvswlZuVLhMZ3VutdTEpGhj69QEnTZB4AQZGcYm5n99ST/Wz13DHw/C7lviLghpxFtuvZp03Vp4eR1tbvrF24vdEaRNNfgWjcqMZU5vuHZQwF2qFUHcR/6Qaja3AvBs/PwDa0LrlgnOq3wATb2HaMj5qjehfRGNhp/2dikLwFHlfa6XupdVTL/CeLhiRQ6sGpuqofcg1BCOSuIzjVWRxSXFmYTdLR2rCYqd2mH280odY3OFjHPWz3tK3y9LPncFA94hBbjO1lDmDcfU4NBTvuwKy8NAHOoX+TtCC+NpfOWnXo49fa8XDZaKZpkIUw7p7nS/rdj/1xoNUoQ+0/fanZuFmds1h1D71+qB4PPD0VnHLMbyNYuCRzi+MbKnBlcSXwB2lFw0w71aT6tSUqYH07cD55UCSB35++FSTpyqRS0FuouWorwVTiGUa14X5lDFJDMjCv+QgwxGHcWX35uSaiAWQ8U9Y+n28V/Yq17TjOgGfrjEFpfvioMu6xG6fIZ6l18q+W+20kDOsQlT0pUWdBBRk,iv:YMs7arv8DDdcLWkOBPYyPNrSxGsihRa6A9AkIhnmUts=,tag:2puneERBiVdMHqhAaIcQlA==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T16:33:30Z"
    mac: ENC[AES256_GCM,data:4L6lL8lOxfX6AD8ihRtIlqvuh/JVeswe3Qa49KjAVnXRaBAkPDj1L3Gn3YwlM7XD2YL2ouRcokJa4UhkvOKQaWOYS9538lt7nDKRslAEvHUNuGx1sYC6FDDBExUAnsB9Vdy9Wx8H3M+qsnW6R+vvNVQDH624dyvpV8VhN4SNyVI=,iv:aNpmFlOrHZfDtmjbyr7Xg8WKV47hbiUJtfT2ze2UciI=,tag:YKlkqKjvxOmentELxn4nMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-service-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:GiX29UySQcY6qNnx+Vur3zKeJSZrwSui,iv:w5J/LUocfSif/7AHZ3LBJKho4mZlG9YB46ZwCiKgmuQ=,tag:z02ub/mK8kildIyPtvKbtg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:K+r4TiBaMBq43MDbRnG4G5Zc73lS0P1oHqGq+hvrfIzY+lKdWVBTPETpxRz/xrpa7Jze6TvuSvA=,iv:xse5rSLRbUTWP/AktwrabwulretXr2DkOo/dWlGF3e4=,tag:SDR5TlmY16Dg8PsqPTrILA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:qy7O/IdZb5O7dWE5/t5bNN4UIbMp42AJ,iv:6N2vWcdyHNfJK1kARYBhneqLFcPfv0fC9LCcGnDBxMQ=,tag:aqfDGiMJUjzCRN33FS9HSg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:dEPnAkoXHqE2W37Xn4orWx7CuM4Gw3ZBp+I1H+Lppqb+83Gp,iv:HEe8hBEZ1b5GJBc980I24AoF/hR+hVYAAsmOXw4sogE=,tag:TI3awv92NbWzg9acmzom0A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pFwxhGOwHKAu2xIyBftXJX/vVh2j2ZP9LA==,iv:yu6KuqH2ptJ+SYum+MVAdH0EYGNRDml3ZXxEivJXl58=,tag:IrJxPc2sWt01Y3ZRZdlmUg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T16:33:30Z"
    mac: ENC[AES256_GCM,data:4L6lL8lOxfX6AD8ihRtIlqvuh/JVeswe3Qa49KjAVnXRaBAkPDj1L3Gn3YwlM7XD2YL2ouRcokJa4UhkvOKQaWOYS9538lt7nDKRslAEvHUNuGx1sYC6FDDBExUAnsB9Vdy9Wx8H3M+qsnW6R+vvNVQDH624dyvpV8VhN4SNyVI=,iv:aNpmFlOrHZfDtmjbyr7Xg8WKV47hbiUJtfT2ze2UciI=,tag:YKlkqKjvxOmentELxn4nMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
