---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unifi

spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      unifi:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: jacobalberty/unifi
              tag: v9.3.45@sha256:6f1cc8eeda6a2303a3939f8f6565d4e4ca963b18b2d5dfae7e1ed4799d102eeb
              pullPolicy: IfNotPresent

            env:
              TZ: ${CLUSTER_TIMEZONE}
              # -- Run UniFi as root
              RUNAS_UID0: "false"
              # -- Specify the user ID the application will run as
              UNIFI_UID: "999"
              # -- Specify the group ID the application will run as
              UNIFI_GID: "999"
              UNIFI_STDOUT: "true"
              # -- Java Virtual Machine (JVM) initial, and minimum, heap size
              # # Unset value means there is no lower limit
              # JVM_INIT_HEAP_SIZE:
              # -- Java Virtual Machine (JVM) maximum heap size
              # For larger installations a larger value is recommended.
              # For memory constrained system this value can be lowered.
              JVM_MAX_HEAP_SIZE: 1024M
              # # -- External MongoDB URI
              # DB_URI:  # mongodb://unifi-mongodb:27017/unifi
              # STATDB_URI:  # mongodb://unifi-mongodb:27017/unifi_stat
              # DB_NAME:  # unifi

            resources:
              requests:
                cpu: "25m"
                memory: "1Gi"
              limits:
                memory: "2Gi"

    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          coredns.io/hostname: unifi
          io.cilium/lb-ipam-ips: "${CLUSTER_LB_UNIFI}"
          traefik.ingress.kubernetes.io/service.serversscheme: "https"
        loadBalancerIP: "${CLUSTER_LB_UNIFI}"
        externalTrafficPolicy: Cluster
        ports:
          http:
            enabled: true
            port: 8443
            protocol: HTTPS
          # -- Configure Controller port used for device command/control
          controller:
            enabled: true
            port: 8080
            protocol: TCP
          # -- Configure Captive Portal HTTP port
          portal-http:
            enabled: false
            port: 8880
            protocol: HTTP
          # -- Configure Captive Portal HTTPS port
          portal-https:
            enabled: false
            port: 8843
            protocol: HTTPS
          # -- Configure Speedtest port (used for UniFi mobile speed test)
          speedtest:
            enabled: true
            port: 6789
            protocol: TCP
          # -- Configure STUN port
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          # -- Configure remote syslog port
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
          # -- Configure device discovery port
          discovery:
            enabled: true
            port: 10001
            protocol: UDP

    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /unifi
