---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: chain-cloudflare-secure-forwardauth
  namespace: networking
spec:
  chain:
    middlewares:
      - name: ip-cloudflare
      - name: headers-secure
      - name: auth-forward
      - name: rate-limit
