---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: chain-internal-default-noauth
  namespace: networking
spec:
  chain:
    middlewares:
      - name: ip-internal
      - name: headers-default
