---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: headers-secure
  namespace: networking
spec:
  headers:
    sslRedirect: true
    sslHost: "${SECRET_DOMAIN}"
    stsSeconds: 315360000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
    contentTypeNosniff: true
    browserXssFilter: true
