---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ip-internal
  namespace: networking
spec:
  ipWhiteList:
    sourceRange:
      - 10.52.0.0/16
      - 10.53.0.0/16
      - 172.30.100.0/22
      - 192.168.254.2/32
      - 2001:1620:552e::/48
