---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app minio
  namespace: flux-system
spec:
  targetNamespace: minio
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/minio/minio/app
  dependsOn:
    - name: traefik
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: *app
      namespace: minio
  prune: true
  wait: true
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      GATUS_GROUP: infrastructure
      GATUS_PATH: /login

