---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plex

spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 5
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 5
  uninstall:
    keepHistory: false

  values:
    controllers:
      plex:
        replicas: 1

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.41.8.9834@sha256:40e620ffcdc65331a0c2a7ed9a95700da7d527244f33c21bd35fc30aa25f19ea

            env:
              #General
              TZ: ${CLUSTER_TIMEZONE}
              PLEX_ADVERTISE_URL: https://plex.${SECRET_DOMAIN}:443,http://${CLUSTER_LB_PLEX}:32400
              PLEX_NO_AUTH_NETWORKS: ${INTERNAL_NETWORK},${INTERNAL_NETWORK_2},${INTERNAL_NETWORK_3}
              HOSTNAME: "plex"
              # UID and GID
              PLEX_UID: "568"
              PLEX_GID: "568"

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: &port 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 500m
                memory: 2Gi
              limits:
                gpu.intel.com/i915: 1
                memory: 5Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [44, 109, 1503, 10000]
        seccompProfile: { type: RuntimeDefault }

      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"

    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          coredns.io/hostname: plex
          lbipam.cilium.io/ips: ${CLUSTER_LB_PLEX}
          # traefik.ingress.kubernetes.io/service.serversscheme: "https"
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: *port

    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /config

      config-cache:
        existingClaim: plex-cache
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Cache

      transcode:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /transcode

      logs:
        type: emptyDir
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Logs

      media:
        type: nfs
        server: ${LOCAL_LAN_NAS}
        path: /mnt/tank/library/media
        globalMounts:
          - path: /data/media
