---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pgadmin
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: pgadmin

  maxHistory: 5
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false

  values:

    controllers:
      pgadmin:
        strategy: Recreate
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: dpage/pgadmin4
              tag: 9.13@sha256:d243a4bcc02d2ee6b447c601692813531d2d0fbca18b583d9f7f9658da835d81

            env:
              PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
              PGADMIN_DISABLE_POSTFIX: "true"
              PGADMIN_LISTEN_PORT: 80
            envFrom:
              - secretRef:
                  name: pgadmin-secrets

            resources:
              requests:
                cpu: 15m
                memory: 165M
              limits:
                memory: 256M

        pod:
          securityContext:
            runAsUser: 5050
            runAsGroup: 5050
            fsGroup: 5050
            fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: *app
        ports:
          http:
            port: 80

    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /var/lib/pgadmin
      server-json:
        enabled: true
        type: configMap
        name: pgadmin-server-configmap
        globalMounts:
          - path: /pgadmin4/servers.json
            subPath: servers.json
