apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secrets
type: Opaque
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:F6DdhTV4za8as5p3vhp9SwzJ8IxI,iv:t4dRUtBJq5z3IsMGWshjQqZqD6ZRVDI500Xz8vNu5E4=,tag:GIFD27+jHulDEvqex2R7zw==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:jY30yY3Kl5g3DDdSHfnrFXGlHBBB/a+b+dfkSf5KHBvGlA==,iv:kNcwZ2G7DwstcheyIT4C9dgKy2QAx2OaLEcB9z0incA=,tag:PBIviEwPKaqCo46LDfbTUA==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T13:53:19Z"
    mac: ENC[AES256_GCM,data:27XpZJAJbnWDepUp7YnktIJLqrQx391nytxi4f7dC3HfW0LxntyMkHtz3I3CsKpQzu8tK9dQeWVaXMUvryGznJIgVeTM28v6v9OwTo5RtYsUNk+6ybADQ4eFey/oaKwDiitIQb6ScGyHjCgpxdrqqM5i1zfUTlSZ0zuiFIEZGr0=,iv:71ClAi9evmhVYzZX/dWIh7H4Cdkh+OIyQmaSrQQbbfc=,tag:czUybEXja2IHoSD7aZtq0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
