apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secrets
type: Opaque
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:tXbHuxywyv4X3iKiFvlq2XmHWQrm,iv:m8VX+FIo68K3/Y8HjJQ+OkOfwV9QQSGiANmM5ocePnk=,tag:6tg7rYJHDYNAVEp/Za6y5A==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:O/VEffQJRBGUpdTXb1QNbBDE6+b7XRJX3kyiIG7W5O8Wpg==,iv:jETbsz9ggqe1GVSR6jF5x4ddcLtzxbIQFSmBElUNkZw=,tag:O7muZZo74ftf50zEetBIkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T11:58:48Z"
    mac: ENC[AES256_GCM,data:0rA9deOKp+Nk2lP1PjEUW3tbPyB8YFmdMR0WJVXRDpvQ5J5smizYOUNIZnGfy8Qnkbm5mWl3I/nC3Py35Du+iOsZQcDlOttWxREgl9vr031Y2s6FcrIIVvUdyvFPmAskYrTjnXxQfGlAtNSIfcjecsatg1+r7gIxISCDGM2JxYg=,iv:2wDBp39IFfmGl/gVz/7Ldmt+jlDnG7Vx7Ytsl2FseKQ=,tag:XX1SXDN7oUpdlNj10x2K9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
