---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless-ai

spec:
  chartRef:
    kind: OCIRepository
    name: paperless-home-ai
  interval: 1h

  maxHistory: 5
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 5
  uninstall:
    keepHistory: false

  values:
    controllers:
      paperless-ai:
        strategy: RollingUpdate
        replicas: 1
        type: statefulset

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/clusterzx/paperless-ai
              tag: 3.0.9@sha256:2b65888163fd59716f1c8285b31c5bd0b30c9c3c192c42b516688e3887d4ba60

            env:
              #General
              TZ: ${CLUSTER_TIMEZONE}
              PAPERLESS_AI_PORT: &port 3000
              SCAN_INTERVAL: "*/10 * * * *"

              # Feature Flags
              ACTIVATE_TAGGING: yes
              ACTIVATE_CORRESPONDENTS: yes
              ACTIVATE_DOCUMENT_TYPE: yes
              ACTIVATE_TITLE: yes
              ACTIVATE_CUSTOM_FIELDS: yes

              #AI Config
              AI_PROVIDER: ollama
              OLLAMA_API_URL: http://ollama.ai.svc.cluster.local:11434
              OLLAMA_MODEL: qwen3.5:9b
              OLLAMA_NUM_CTX: "4096"

              #Paperless Config
              PAPERLESS_API_URL: http://paperless.selfhosted.svc.cluster.local:8000/api
              PROCESS_PREDEFINED_DOCUMENTS: yes
              TAGS: KI-Inbox
              USE_EXISTING_DATA: yes
              RESTRICT_TO_EXISTING_DOCUMENT_TYPES: yes
              ADD_AI_PROCESSED_TAG: yes
              AI_PROCESSED_TAG_NAME: "KI-Analysiert"

            envFrom:
              - secretRef:
                  name: paperless-ai-secret

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

            resources:
              requests:
                cpu: 25m
                memory: 256Mi
              limits:
                memory: 1Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      main:
        controller: *app
        ports:
          http:
            port: *port

    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /app/data
      cache:
        type: emptyDir
        globalMounts:
          - path: /app/public/images
      home:
        type: emptyDir
        globalMounts:
          - path: /home/node/.pm2
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/logs
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp

