apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-secrets
type: Opaque
stringData:
    SPARKY_FITNESS_DB_HOST: ENC[AES256_GCM,data:Ce7KEGkieaq6sjQHGyKUuatPNw==,iv:4onqUUQpaIl0Dfbwa1C6CCi8LZC32WGYacyCZlL4siQ=,tag:TVsWr/nETwRcQoN7aJqMLg==,type:str]
    SPARKY_FITNESS_DB_PORT: ENC[AES256_GCM,data:xtkSqg==,iv:t0s3CGk1aHVKenw0iqKkDwoo/mdXtauT+il/iTDQeIE=,tag:bF8J5Kc58+ZqPRUo85WFTA==,type:str]
    SPARKY_FITNESS_APP_DB_USER: ENC[AES256_GCM,data:k6TDWzl3kQywrl46qs7KOldF8Q==,iv:q2zI0TD2Tzod4jPlUhkor7nRumBPhDJRzupnwbS4noI=,tag:YKurBVFY3185d5ApCBnYuA==,type:str]
    SPARKY_FITNESS_APP_DB_PASSWORD: ENC[AES256_GCM,data:ZJqZqbaUBzxKo0+Un2LUsCt3GsEZ19ReDWM=,iv:cADR/yjO0UEh4plI0hYaAuERdOhnomlzsLM0uB5/SJM=,tag:YZ0HKZn3UcxvMq5njtTBHQ==,type:str]
    SPARKY_FITNESS_DB_NAME: ENC[AES256_GCM,data:/qahVOrrhfJJm7hJuw==,iv:Egpwd74XRi11AprIaRIxRPe2liRIMXHUBHDBWOn4nn4=,tag:+Qo/otiDtPyOu4zk0hUsgQ==,type:str]
    SPARKY_FITNESS_DB_USER: ENC[AES256_GCM,data:+QViR4LI/FjGAbvKfToyrd0rMA==,iv:nAzwP5udGsvkMccgMYBCxFi7HIxaBNaD6v9ta8Qfc8w=,tag:LdYrxcSF/358E1vGQ3xyfg==,type:str]
    SPARKY_FITNESS_DB_PASSWORD: ENC[AES256_GCM,data:al6gzDfHJJ2dDtve+sAAKOlYxdXosO10R4Q=,iv:jsOGJy2Np5SUchKzun5d+OpqVH/8/eJv9fTU0ZS4nCk=,tag:qZjGS5XX48l7xpc3TdVeuA==,type:str]
    SPARKY_FITNESS_ADMIN_EMAIL: ENC[AES256_GCM,data:2PNo7A1XfZEUHamUr7MsC/WFCbu7Puw=,iv:/Frt0Z6KfSqboqoanRvG+3a/+7L/8rTVKc+OR/mRNow=,tag:IRf3eIBk9TS/TGvS24zZNQ==,type:str]
    SPARKY_FITNESS_API_ENCRYPTION_KEY: ENC[AES256_GCM,data:3FDmWyInU1oDGlW7p34hmfhk7JTCql7gGtIu41rxJynHu0ogFJETSoe75BcWxiIW2JdIT+Wp/z1dPazSKRbf1Q==,iv:hVzy3woGBXmipNcGjNp9yeBxVMla3H93K53nEsNekzM=,tag:AXRWX7MBtyWQPHp7noaetg==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:4Q4BvUYuWWATo76k/XV9blR+93yROCGjXQ7sTTrYLlW6aWEj011wPpvYfApyzb8YE0gwhfze1snx8KvYNjgOgQ==,iv:Km88YXrxB0FfeZPyvmefvVkBXYpVSKP5a9P1yJotPMs=,tag:5g6V6hvS29wSUF1KrZcyAQ==,type:str]
    SPARKY_FITNESS_EMAIL_HOST: ENC[AES256_GCM,data:LSrPHFs8LlKDKLUyT67Nn7BU2H4P8uM+vHR13XZo9lTvxvOaiw==,iv:hgmjAwBMpwMfW8jLwJMq7PH23Mz+beKylTfGEhxO98E=,tag:DpaIWTsrUWHk2vkS5d9NYg==,type:str]
    SPARKY_FITNESS_EMAIL_PORT: ENC[AES256_GCM,data:h8I=,iv:CD88j7tAzpRkrf5HsCxlMDSDUveZjDGbgmjYe8lKsxg=,tag:tVsdSppct43ScQhLofXYyw==,type:str]
    SPARKY_FITNESS_EMAIL_SECURE: ENC[AES256_GCM,data:itjg5Ks=,iv:VqD+s1x2tvkpbCNTTxvdcO/MowY0r6tuIhN9Drw6+w4=,tag:DgfjE/DNF/puMFGfF7SqEg==,type:str]
    SPARKY_FITNESS_EMAIL_FROM: ENC[AES256_GCM,data:2UZFCnRjnboa6TLYn3FaVUz24tMOQNAT9fY=,iv:xKXOhgE+cH8MtkZyLKhmhz/9ztoe7B4ay9oCl1mvFyk=,tag:90PxJWuUAUMbbFt3I9REfA==,type:str]
    SPARKY_FITNESS_OIDC_AUTH_ENABLED: ENC[AES256_GCM,data:WncEfA==,iv:/ah3h9CO/MIqXQqaN+1xBq4A2+6mWwjH5SA03ZcpEkM=,tag:9hdAytWfhV3x8Hd+2fOzQw==,type:str]
    SPARKY_FITNESS_OIDC_AUTO_REGISTER: ENC[AES256_GCM,data:k+QUqA==,iv:k8EYGHFNIOW3oi4a8VsS2kI2tgrPCq6M8JydvcdDK/I=,tag:F+DGvgWJisSTXe/oBy/6HA==,type:str]
    SPARKY_FITNESS_OIDC_PROVIDER_SLUG: ENC[AES256_GCM,data:yTZFSOmJJIU2,iv:3vHNfpTHBP5mZU+HVaGfcvB1/Q97jGwORO+UhR8kSZw=,tag:UUuAX3huh7Hqq4m+c6iajQ==,type:str]
    SPARKY_FITNESS_OIDC_PROVIDER_NAME: ENC[AES256_GCM,data:VcKBRmTpq02pqg==,iv:3S6a8OW1AcjZKnzW/wIh2pF9mzWDKPqVQZF/RMJXDb0=,tag:SwELXfWJ8wPDUDoVO76ojg==,type:str]
    SPARKY_FITNESS_OIDC_ISSUER_URL: ENC[AES256_GCM,data:FGfWJsIEyxbDDjmhbwpwgkL8UxpPOlEYuufYb6Z6nBgpuxei1n+Xon4MxgybbiTkAwTpaoMPS3v5,iv:z2gZbYK3WCceYiPel7hxQlKRDeGQdqU19dyJOVi90mo=,tag:zQPTBV/mwjeqr1PJJkf3Zw==,type:str]
    SPARKY_FITNESS_OIDC_CLIENT_ID: ENC[AES256_GCM,data:i0zU3M6lL1yH3G2+eiTco7OBOQw7KzqVsiFFWId4czka,iv:UTI14n5zyn4mvW5znydzYlGLwF93Hi5VwynMRCHAi08=,tag:d54LESsIDhZc8lbGTqiRgA==,type:str]
    SPARKY_FITNESS_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:kWh8HK8H6tRL1z2S3EGzA/35Anh8LRuOFyMCx2WU9x45lXS5ig==,iv:EiBjcBnJNqq/5LImAQIp4cBYGK1JqSHt3vSrTb7mJ84=,tag:gv9qEGnE94IMHenbCLuPxA==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbDMvOUVFVEQ5R1VkcHN4
            dWplU0cvRldlN29KU0Jub0h4UDFUVEZhQ1hRCk85L2hMRXZianRNRHR0NlJ0eW9P
            MkFLdzdqbzZjb2hIaVlFTysyN1RJSE0KLS0tIGtRc0FZemwzZlhpdVpTcnNBeGVr
            Y2krb0pVTWk0TnJLalhhT09pZC82bXMKW59BVpnSVACGbzVgJtdOAjW9qVOTTjpW
            RLuyt+Nct7O+eYb2ZenB8aohSsanVzmU4mFvh3yKaKEFnMPhcCXmjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T15:21:35Z"
    mac: ENC[AES256_GCM,data:dW3ZfRDLhfi88bYQglhmlgvQQfNQ52bHxccdg/RQZYMElEQzJ2AOn9JD2kwivIH4DX8eeGFEhxMfM9Hd4+Pzypz8xW8JC+1rK9i3n1+Fr+7DQdoGwcEpCKv0qUJa/cq6siOn1rOUfNlHHV6mO1ICCn9ANjhUrTTrz64v3lWeRTU=,iv:KNLkpgX6ICN7LGkCr2hYuxWo8ltWCVe0FVTfHSqKqkU=,tag:Yn/NxjW3GiLTX5NA0MTILA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:4zY9XNyDrlsxTYiYWkD1Nrxp2Zk=,iv:Jlu6STaK7q48eXg8/4v5JlV+XSo8EaT9iOTZ+EYs7Ps=,tag:a1bec7of9vbaxohVrakhLA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Cry8bsabpbJhtCOfYtA6vmx1T73+LhqWcR65Y1MQTq9jzW6YwmE69dRaAQ4CDuNEkcX/IXPb5tA=,iv:UWEXWDvElr8o0Ytzit4/9uhF7cfnL2UyIStaSV3pg/w=,tag:TDofV7oG5z2YdHM1Ba3Xbg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:/EfypWzhPeYrLlLar3qVDXGsu1pHCcOcybyhvg==,iv:42y6Y3aBSLJb+zHl9XVbl6ZfQVEqI1ahy7i1TPKYp0c=,tag:xsscZQcRpPAP4DX9ZaYRPw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:YAUFzk+Nj0f8N0wyEo76L2eNU9jW2C/hOxzz4JXiMyLLxL4z,iv:BkZoAlPtGYVPc6Vxk3HVGkt92ZrDO7tvCKYQtWuwnQ8=,tag:nSiL6KvoZcXGuYeY6TwAbw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:D9Ui1ji3u4xvUd4NinlwWs09jxhxzEsDGw==,iv:c/fuFReoBOKjqHYf0hA0eWZQqU/j2gNg9LzIZakOexY=,tag:EIVEzxTX91QRf/E6uVDKrA==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbDMvOUVFVEQ5R1VkcHN4
            dWplU0cvRldlN29KU0Jub0h4UDFUVEZhQ1hRCk85L2hMRXZianRNRHR0NlJ0eW9P
            MkFLdzdqbzZjb2hIaVlFTysyN1RJSE0KLS0tIGtRc0FZemwzZlhpdVpTcnNBeGVr
            Y2krb0pVTWk0TnJLalhhT09pZC82bXMKW59BVpnSVACGbzVgJtdOAjW9qVOTTjpW
            RLuyt+Nct7O+eYb2ZenB8aohSsanVzmU4mFvh3yKaKEFnMPhcCXmjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T15:21:35Z"
    mac: ENC[AES256_GCM,data:dW3ZfRDLhfi88bYQglhmlgvQQfNQ52bHxccdg/RQZYMElEQzJ2AOn9JD2kwivIH4DX8eeGFEhxMfM9Hd4+Pzypz8xW8JC+1rK9i3n1+Fr+7DQdoGwcEpCKv0qUJa/cq6siOn1rOUfNlHHV6mO1ICCn9ANjhUrTTrz64v3lWeRTU=,iv:KNLkpgX6ICN7LGkCr2hYuxWo8ltWCVe0FVTfHSqKqkU=,tag:Yn/NxjW3GiLTX5NA0MTILA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
