apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
data:
    username: ENC[AES256_GCM,data:9kjt6UoFfW06X5I00EmmV4fMjDvC2jconQ==,iv:DMAMUdPixG92IUINFsDjJlUWRsgRPX+XXlI4gTaz9nU=,tag:JbGmVgITa2WvGe9TJukRFA==,type:str]
    password: ENC[AES256_GCM,data:xOtNlNFH55Y4UZYtXHGR4rlxSqwYRcW9jA==,iv:r3JdiKS57yl7k+lhjCqnsOVuI36FyEulY22GbmajO88=,tag:o+FGLlijhUL+iy1/WvL1Lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-22T16:11:18Z"
    mac: ENC[AES256_GCM,data:HbiOFvbl3+EGJx4wsTpJ4qPHH5AH2bAjJXXaJ+XB8wBplUfc6DK49qIEY92uDEbbdBgwWAncTRH4+P6MPylUReBOO1/RsRw23bhtRgN0Td18UPY5/vuS5GsNbXvrXuCTXoXqZagHUWl1KKZK8dTAndvr5LkTDeTXStjztw2w1Bo=,iv:VNIMEdYH8baRu28YDjRpSwQQ8DnxU5yauLzt9yS/YGk=,tag:K+tGy/d8Vjp1INmVuK9mnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio-secret
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:aNKGGXkIEAoQL0WIIt9VnvZCAQk=,iv:Cira/t7hTB3gK8PrCYRnQEbCnboj2mqioOWneuluAd0=,tag:NZ0emsGguWJHC2ub0Q7+1w==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:eIAG0ki2fq10zokLMtX3f4CSWLIkP54yld5xXaIIr0FU7cGgclR6AA==,iv:kjGcUSvOsHEJKzobCiyqS/eErIlNQYV5xfBlN8hZSmc=,tag:9M1Crejy5R1zdzTYb9Z0Jg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-22T16:11:18Z"
    mac: ENC[AES256_GCM,data:HbiOFvbl3+EGJx4wsTpJ4qPHH5AH2bAjJXXaJ+XB8wBplUfc6DK49qIEY92uDEbbdBgwWAncTRH4+P6MPylUReBOO1/RsRw23bhtRgN0Td18UPY5/vuS5GsNbXvrXuCTXoXqZagHUWl1KKZK8dTAndvr5LkTDeTXStjztw2w1Bo=,iv:VNIMEdYH8baRu28YDjRpSwQQ8DnxU5yauLzt9yS/YGk=,tag:K+tGy/d8Vjp1INmVuK9mnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
