apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
data:
    username: ENC[AES256_GCM,data:9kjt6UoFfW06X5I00EmmV4fMjDvC2jconQ==,iv:DMAMUdPixG92IUINFsDjJlUWRsgRPX+XXlI4gTaz9nU=,tag:JbGmVgITa2WvGe9TJukRFA==,type:str]
    password: ENC[AES256_GCM,data:xOtNlNFH55Y4UZYtXHGR4rlxSqwYRcW9jA==,iv:r3JdiKS57yl7k+lhjCqnsOVuI36FyEulY22GbmajO88=,tag:o+FGLlijhUL+iy1/WvL1Lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T15:07:57Z"
    mac: ENC[AES256_GCM,data:ZUjcHhC2R/Ew8LCd6scsuZ+K1ypQR5m5/iK2hR3+nveZybYlP+k/OTgY97S60+CSnVc3koyDB8XtoZv3JNgp+bO7vgt3wVtSqGDYUuPmlPeCXVT636xnaB6U0MFfvKAWAfUXqTPcnKPdLuSsY+J9aM372uQrFn309G7OexzJVLw=,iv:CASFV++2XLfLrb5YpB3YzdzXaa8hsGEh4hlMXFr7Res=,tag:9xaOFEOxzRDLJlhsr4RhDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio-secret
stringData: null
MINIO_ACCESS_KEY: kadagSteqxCINLENtHFK
MINIO_SECRET_KEY: KdcxyyH8yBNmOikjAidPpX60SHu9P4LG9nLtd4ha
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T15:07:57Z"
    mac: ENC[AES256_GCM,data:ZUjcHhC2R/Ew8LCd6scsuZ+K1ypQR5m5/iK2hR3+nveZybYlP+k/OTgY97S60+CSnVc3koyDB8XtoZv3JNgp+bO7vgt3wVtSqGDYUuPmlPeCXVT636xnaB6U0MFfvKAWAfUXqTPcnKPdLuSsY+J9aM372uQrFn309G7OexzJVLw=,iv:CASFV++2XLfLrb5YpB3YzdzXaa8hsGEh4hlMXFr7Res=,tag:9xaOFEOxzRDLJlhsr4RhDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
