---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mealie
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: services
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/services/mealie/app
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: authentik
    - name: rook-ceph-cluster
    - name: smtp-relay
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: mealie
      namespace: services
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
