---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: &pv paperless-nfs-consume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: *pv
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${LOCAL_LAN_NAS}"
    path: /mnt/tank/documents/consume-home
  mountOptions:
    # - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume-v1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: paperless-nfs-consume
  resources:
    requests:
      storage: 1Gi
