---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless

spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 5
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 5
  uninstall:
    keepHistory: false

  values:
    controllers:
      paperless:
        strategy: RollingUpdate
        replicas: 1
        type: statefulset

        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: "17.6"
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: paperless-init-db

        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.18.2@sha256:fbe142ff2e02713740329ebb5981c6bb6fe54f8b4de18e98637c2ff586ea1935

            env:
              #General
              PAPERLESS_URL: https://dms.${SECRET_DOMAIN}
              PAPERLESS_PORT: &port 8000
              PAPERLESS_TIME_ZONE: ${CLUSTER_TIMEZONE}
              PAPERLESS_TASK_WORKERS: 2
              # Configure user permissions
              USERMAP_UID: "1000"
              USERMAP_GID: "1000"
              #Folder Config
              PAPERLESS_CONSUMPTION_DIR: /consume
              PAPERLESS_MEDIA_ROOT: /library/media
              PAPERLESS_DATA_DIR: /library/data
              PAPERLESS_EXPORT_DIR: /library/export
              # PAPERLESS_FILENAME_FORMAT: "{{ created_year }}/{{ correspondent }}/{{ created_month }}-{{ created_day }}_{{ title }}"
              #Import Folder Config
              PAPERLESS_CONSUMER_POLLING: "60"
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
              # OIDC
              PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
              PAPERLESS_ACCOUNT_ALLOW_SIGNUPS: "false"
              PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: "true"
              PAPERLESS_SOCIAL_AUTO_SIGNUP: "true"
              PAPERLESS_DISABLE_REGULAR_LOGIN: "true"
              PAPERLESS_REDIRECT_LOGIN_TO_SSO: "true"
              PAPERLESS_ACCOUNT_SESSION_REMEMBER: "false"
              PAPERLESS_SESSION_COOKIE_AGE: "14400"
              #Language
              PAPERLESS_OCR_LANGUAGES: deu
              PAPERLESS_OCR_LANGUAGE: deu
              PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'
              #Redis
              PAPERLESS_REDIS: redis://dragonfly.database.svc.cluster.local.:6379/2
              PAPERLESS_REDIS_PREFIX: home
              #Tika & Gotenberg
              PAPERLESS_TIKA_ENABLED: 1
              PAPERLESS_TIKA_ENDPOINT: http://tika.serivces.svc.cluster.local:9998
              PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg.serivces.svc.cluster.local:3000

            envFrom:
              - secretRef:
                  name: paperless-secret

            resources:
              requests:
                cpu: 25m
                memory: 1Gi
              limits:
                memory: 5Gi

    service:
      main:
        controller: *app
        ports:
          http:
            port: *port

    persistence:
      library:
        enabled: true
        existingClaim: paperless-data-v1
        globalMounts:
          - path: /library
      consume:
        enabled: true
        existingClaim: paperless-consume-v1
        globalMounts:
          - path: /consume
