apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
stringData:
    #ENC[AES256_GCM,data:rdCUcmtCs6JKnQ==,iv:lB+gK3WuxdEZ8d+gClxmEcbe32n03pak3Yv12M5uTWM=,tag:ze+5LOZjYY0eRUlGzZIrOQ==,type:comment]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:NPcUIu1KN/OgJZ9L42sosD9fv+ue,iv:tMH0zaRoMHSmG5Q8KnQJ8HvwEgGouqJJ0oyCF8f6ibg=,tag:Kvq8uhDOr9qSJkprXwDYBA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:gWcL0uILciPso+mxNf4iH6vjKDb+EPl8,iv:T+Dl0DpJHNRcBRdTVlyCbBI6Am/m6T/oSTq+Nx0tP8Q=,tag:td0r2mzkReKFue+Z1RclHQ==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:B9DEFa890n0fsMGBc3Wb9zbfj96DOPBHpsYlJSRS+c33RM6oHo1v4xxvrwZKf4mLt0vOmtZKzfb70EjVc4CGeA==,iv:rU1DIbK4UXhzAYzh4KLv3JUXHfPjRa3nXP66r798dNU=,tag:IDQYSc7VrAgqgax+Qqn6/A==,type:str]
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:7UAJEM3f/j4y,iv:0ui21Q0PhuOq6qcn/chL26L3MS4Zw+yw9zWPY2hcr18=,tag:JGRC9JY4qT9q5IhV2V8jlQ==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:cHe0K8YGfVB2Xo4upZBXZqMwzOxJDnfk,iv:qsEXoynIHEeszZyWcJcHMtpvmNkrCEHHF2u+VIXUme0=,tag:XI3dVbeex7JAmHnRgtHBNQ==,type:str]
    PAPERLESS_DBNAME: ENC[AES256_GCM,data:hT1fb743t0Gpu8TojrU=,iv:FEJqkf545OipZ0U+SHE6Hu4/T8g6v1OdVdd2U2s1UH4=,tag:KMo/szD9tL3m2cXn8L8bxw==,type:str]
    PAPERLESS_DBHOST: ENC[AES256_GCM,data:VMPynLcuWUzgvLnnjk0AW5eOgA==,iv:arr2sz5XI0JMfYd5EnWk0ATKqMJZvsnvw57BiaRW2D0=,tag:P29onR/Ps0gWctN5V1NEsA==,type:str]
    PAPERLESS_DBPORT: ENC[AES256_GCM,data:ivqPjg==,iv:xFHycqboOLIrOpupYpeAaBgNADj1nPsrtgoVi8arQOk=,tag:j1h/MlEgfFi6/+26rr6fqQ==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:Vg0mKHPYQabcRMKO16XKSl2rtKyuA/cum36+xI1DNTu6m00/8HFo9H/kUb3BtrtZwEVso8+TiWppDsh/LGPvPIL5iDp+hKvYFPanMiI+68UuiO54Yi8oUCY3OL0zdvJ8ZDXHz3I7aI+mMudbZxjSYublSlgCz8u4qmVr7KGaUVQvftSDflHswv+8YLfruRtChksACHIrjEQsrwCoYp1oS4oH2BFsj2W+bjXABm1Ob/CFH+n/WGZieZvuOL0WyRYWrjeqd9h98PvQqoJtd9xKPbX/IfNC5u44kc5ztMxHiL0A/bDRzRq60I/CZE7rvMa+4SWvooQEVpLDqkVNRDGTTGNvtVBCdUTVzFnCzWPrK0/jjWLpsaWstQ7jykjAeiEOjhYZeepg8qlQuimGz452FUkgF+Ce8iXVfbbEMbLl1ZBq2oqaW3Wcx4+UYKRP2ccGsabIQ5VddsOmtKUicWzzIRhKCs2fmJst2M9tXF5X+OME4yFwqAxZNiNZI5SzmTzC9shGFZF3FlT29TQ2QvmhoA1dIccDKw9gAgw0pqSoOaftN+Hyex4=,iv:TFaeuOCKvCsPuhqxrPqTkLROJ2gUDDXEU/5JkbQBeiw=,tag:VWDd7GBsSJddVztzL7n1iw==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T23:10:58Z"
    mac: ENC[AES256_GCM,data:DQkPz2n6uQQsUQDVCs6u4qAXBjIQRilQ5UXjzvHyu8FucnJsJutFKrhNjy6PySZlG0lSqJDLVwNOMF0S2wISuZa1s/YV719mRBGLgZjU4I6iFjPe+3M5GdiriampF/bz6snynT/DItbTLDy+wJHFvFdoe+B5uTYEyPTAcJ6+I7k=,iv:QAf276Dfo12btd4u64/DR7F8sPvb2TKZ5v8q7twi4hw=,tag:sVhPT7D3eauW7A+OropSNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:IMVVSPDbGllwGljQkDpgiyb4Uyw=,iv:OBBr4INS0rOBdetEDPdPkr/ICI6th28htr1HuQ/LNaE=,tag:cSzrNziLAEW5jAxaxLOXfw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:LyLStpyUAJieIzI6+4wRB+8X7h2EsLsvqPmik9JfybC7J2LUnBZ3Z7tSaXYU17XrIwuM9OcQuTQ=,iv:WnE2NLqChaa1hcRkQyVbxPspFErDT9Tpm/8DpnKflfM=,tag:LveekByoX9MFTJ7m32QuFQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:qpK963+P3jzLzkOE,iv:X+ywYNCOCQNustF3cAl4kkg1jcEEMHhJmtq2s8RQkoA=,tag:35khZm3/Ip/OG25vYyuwwA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:RRvAdalUr9q8kls5ldSxWcwf8BGhdk/fmKvY0lvafnQ=,iv:uWk0EmXsu3DqXnt0Qrg9ueCCIaguDsqXZbtEhdE9XoU=,tag:vsL2Z5D5nN1dEexxwHV05w==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pFwxhGOwHKAu2xIyBftXJX/vVh2j2ZP9LA==,iv:yu6KuqH2ptJ+SYum+MVAdH0EYGNRDml3ZXxEivJXl58=,tag:IrJxPc2sWt01Y3ZRZdlmUg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T23:10:58Z"
    mac: ENC[AES256_GCM,data:DQkPz2n6uQQsUQDVCs6u4qAXBjIQRilQ5UXjzvHyu8FucnJsJutFKrhNjy6PySZlG0lSqJDLVwNOMF0S2wISuZa1s/YV719mRBGLgZjU4I6iFjPe+3M5GdiriampF/bz6snynT/DItbTLDy+wJHFvFdoe+B5uTYEyPTAcJ6+I7k=,iv:QAf276Dfo12btd4u64/DR7F8sPvb2TKZ5v8q7twi4hw=,tag:sVhPT7D3eauW7A+OropSNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
