apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: immich-db-superuser
data:
    username: ENC[AES256_GCM,data:vdFLdXyk/dVZz86Y3vOKnjgJ+CIqjwidgw==,iv:MARW30LCUA+1OUX7gpZS6B1pCjIneHGbPtmgfVHoGsE=,tag:Y3seEv/oxwvtNmZCQvBY4g==,type:str]
    password: ENC[AES256_GCM,data:ykjGBm9VANRzveg5ZAm5LY9uDJxJ+T3cAFeOlQ0fMhtfWN0ZI+V7muxKOsQ=,iv:36Vt6AQKbhQraayYpW4MxcVSP1TlkTxn3vmXKfuKJ9w=,tag:nIIx31wHBiKwkFvTVNNHOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T21:59:29Z"
    mac: ENC[AES256_GCM,data:holw4U7rSfbDRp7vB3LnEZ8iQce6pAmCgwpgAxCfFO3muDDt+tDp6X3pGbzUFSCZuMRRxLyfy8LSFwGmJDl9HA+BQ9IcAgqQCfKp/KEZOEOKXSveQ+1vXMCz2VaxdeOsUYjkdjOrWwM+5luseY2+YIfh2s49UXdBUpZG5aiX5dw=,iv:xDB8KZgV746ssRSRCTLSFDaO8OCHC4m0HXMDmc2k8OI=,tag:/u4n+EmIMVk4U2aeLyUgRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: immich-db-minio-secret
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:lE00tlyiv/fxqmdqqIRmVSULaRY=,iv:LkWz/SLy7riz2JHyBoIDKBoi0TjTDDRMKF3QG5LrBz8=,tag:gswzgQsZQVa/79Kh1Ug3Jg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:lfXNu2wc6dXl8nKd8BBXFiLAVbbetVsT+HFA5Kc6URxK2N2WrzTeFw==,iv:sBiZZ8EPSWcchvr/o4YW+ySK/x6JjTsKkFpHgBLp680=,tag:ChRIOj8Zvx/uCUchBVTzJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T21:59:29Z"
    mac: ENC[AES256_GCM,data:holw4U7rSfbDRp7vB3LnEZ8iQce6pAmCgwpgAxCfFO3muDDt+tDp6X3pGbzUFSCZuMRRxLyfy8LSFwGmJDl9HA+BQ9IcAgqQCfKp/KEZOEOKXSveQ+1vXMCz2VaxdeOsUYjkdjOrWwM+5luseY2+YIfh2s49UXdBUpZG5aiX5dw=,iv:xDB8KZgV746ssRSRCTLSFDaO8OCHC4m0HXMDmc2k8OI=,tag:/u4n+EmIMVk4U2aeLyUgRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
