---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app firefly-iii

spec:
  chartRef:
    kind: OCIRepository
    name: firefly-iii
  interval: 1h

  maxHistory: 5
  install:
    createNamespace: false
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    controllers:
      firefly-iii:
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: 'true'

        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: "18.3"
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: firefly-iii-init-db

        containers:
          app:
            image:
              repository: docker.io/fireflyiii/core
              tag: version-6.5.9@sha256:fe4ecec4c2ba2b2978a32b3defaf270407f9fddf0e789a18648121ab84bb68d2

            env:
              TZ: ${CLUSTER_TIMEZONE}
              APP_URL: "kakeibo.${SECRET_DOMAIN}"
              TRUSTED_PROXIES: "**" #TODO: Change this
              AUTHENTICATION_GUARD: "remote_user_guard"
              AUTHENTICATION_GUARD_HEADER: X-Authentik-Ffiii-User
              AUTHENTICATION_GUARD_EMAIL: X-Authentik-Ffiii-Email
              SEND_REGISTRATION_MAIL: false
              SEND_ERROR_MESSAGE: false
              SEND_LOGIN_NEW_IP_WARNING: false
              MAIL_MAILER: smtp
              MAIL_HOST: smtp-relay.network.svc.cluster.local.
              MAIL_PORT: "25"
              DB_CONNECTION: pgsql
              DB_HOST: "${POSTGRES_HOST_18}"
              DB_PORT: "${POSTGRES_PORT}"
              DB_DATABASE: *app
            envFrom:
              - secretRef:
                  name: firefly-iii-secret

            resources:
              requests:
                cpu: 100m
                memory: 150Mi
              limits:
                memory: 1Gi

      data-importer:
        containers:
          importer:
            image:
              repository: docker.io/fireflyiii/data-importer
              tag: version-2.2.3@sha256:ab52bf9325466431af8b311e9879f0a271b1b555b34cb0e1115d0d10a4ef9665

            env:
              # General
              TZ: ${CLUSTER_TIMEZONE}
              APP_ENV: "production"
              APP_DEBUG: "false"
              LOG_CHANNEL: "stdout"

              # App settings
              FIREFLY_III_URL: "http://firefly-iii-app.selfhosted.svc.cluster.local"
              VANITY_URL: "https://kakeibo.${SECRET_DOMAIN}"

            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 1Gi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true

    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
      importer:
        controller: data-importer
        ports:
          http:
            port: 8080

    persistence:
      config:
        enabled: true
        existingClaim: *app
        advancedMounts:
          firefly-iii:
            app:
              - path: /var/www/html/firefly-iii/storage/upload
      importer-uploads:
        type: emptyDir
        advancedMounts:
          data-importer:
            importer:
              - path: /var/www/html/storage/uploads
