---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: firefly-iii
  namespace: selfhosted
  annotations:
    hajimari.io/enable: "true"
    hajimari.io/icon: abacus
    hajimari.io/group: finance
    hajimari.io/appName: kakeibo
spec:
  hostnames:
    - "kakeibo.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: firefly-iii
          port: 8080
