apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-secret
stringData:
    #ENC[AES256_GCM,data:aGzarl2dmPsauljv,iv:JzptTe9mDFU26JVaIxzDbfrlT6g7m073GdFvnHk6GKU=,tag:4WuW6gMBRD66k9ENLwJF6g==,type:comment]
    DB_USERNAME: ENC[AES256_GCM,data:t5+j0GFoF9kBvWg=,iv:ckYHY7JLnemhA893sCbcCKuxjZtBFOOHYOBStX8cSU4=,tag:DiQgufC/jAlQ89dbOYYqzw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:C27AzpLMDiNbid0l3WVM6HToGbQQW4SlP4Q=,iv:2TjRODIMrfoJxUBhyAORuHBC2POELe/Ichzm0MC4UZg=,tag:WrYobGHiBxAkRuPyI5k+NQ==,type:str]
    APP_KEY: ENC[AES256_GCM,data:SRLUHgsQ+Pnce5XGnWxfgWRMgHZ1fr2R54LHg6uiS8k=,iv:J8X9+JyS/hDXJrzS+yjHv0QxKR78UceTguO0cfP2BIE=,tag:WpmWB5v+jPidoYXtlNVUlw==,type:str]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:ezaFErXovwHFfCXXIFUThhGhfRzhDhdfncZQ/NfgmDU=,iv:PwbwISbTRq8Jj6HgZbKlNaR7czcTbBwGlcJ5ICJE/cg=,tag:6JlPCgOfmpflvfuaYftlZQ==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:KSOV5+TAq9HjHLb8dfkvlo4rAGhTTDkMTsc=,iv:JTm/qbhHh0kqAjGaiyBN8z8keB9ADGeUL01qiRzAumo=,tag:oqmwDy96IfflwpI/JWHVZg==,type:str]
    MAIL_USERNAME: null
    MAIL_PASSWORD: null
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:63bG1g==,iv:LkJfjKAVimRGGGPU9/hJsYTPROVGiETgRb5KKERwo20=,tag:m4xqvk+80slEihWJEMd7ZQ==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T19:34:04Z"
    mac: ENC[AES256_GCM,data:cisDRfQIjNlG+lrnqBWEjQtYfZ53w0kmi/Na8hDBDswJUAZYELPVxSHXHVcFvxoLaN2Yivm/oZMGgVqG6L6XD5B+JhUBlY6vVXOjEJHwcoexEiSsaPq/dBKxiI6fCuFq8/MAl50V3EMLAFR5SzT+tp1cpm8FZ3gZ/lwCUNuhAww=,iv:iElSIPj+d/OEfpZiyJsWFG7LwDk0GEud/Z4a1IRl1z0=,tag:HhvdrGMm82gADLpgB66cUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:TLn+jq9biNfmghep1NiMFA==,iv:2y4+xs0WbaCIBvNnNaknEZ45TSzpiqrjMeYnHRwhqz4=,tag:yO9JPpG8Za+Fy9AIBc/lgA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:ZwhB1Ue8ioUfExhED6h8VJvtdg26oR8BK2/h8V9GGgw40TDvkfS3XgA0nRKph7h0H/xWMpdnqJ4=,iv:Ouqi25uAUo6ZJV5GjSrYYeS9zr7NQc9pzm4WUyaZhRc=,tag:/bH1TBP6jKAEvC8IYFDEtA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:VanSEgfPNF0fD55ijR8BTg==,iv:MKO7jXHRuwzsZ6vwk9XiBqwhpz7Q4pff0irbUS6qC/w=,tag:KKqTW265UvbEElFcya+hhg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:vciCqyjWW2d1Ol89GdNtXpvzt/knpQJhzRXW3SFp6MtDKuTT,iv:O0UwjzrMrZySShUONBhn6rN4jyHbRHuhLFf3d9JhwgQ=,tag:Vxk2UrslWVZ4HyDTNi+MlQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pFwxhGOwHKAu2xIyBftXJX/vVh2j2ZP9LA==,iv:yu6KuqH2ptJ+SYum+MVAdH0EYGNRDml3ZXxEivJXl58=,tag:IrJxPc2sWt01Y3ZRZdlmUg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T19:34:04Z"
    mac: ENC[AES256_GCM,data:cisDRfQIjNlG+lrnqBWEjQtYfZ53w0kmi/Na8hDBDswJUAZYELPVxSHXHVcFvxoLaN2Yivm/oZMGgVqG6L6XD5B+JhUBlY6vVXOjEJHwcoexEiSsaPq/dBKxiI6fCuFq8/MAl50V3EMLAFR5SzT+tp1cpm8FZ3gZ/lwCUNuhAww=,iv:iElSIPj+d/OEfpZiyJsWFG7LwDk0GEud/Z4a1IRl1z0=,tag:HhvdrGMm82gADLpgB66cUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
