apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-secret
stringData:
    #ENC[AES256_GCM,data:aGzarl2dmPsauljv,iv:JzptTe9mDFU26JVaIxzDbfrlT6g7m073GdFvnHk6GKU=,tag:4WuW6gMBRD66k9ENLwJF6g==,type:comment]
    DB_USERNAME: ENC[AES256_GCM,data:t5+j0GFoF9kBvWg=,iv:ckYHY7JLnemhA893sCbcCKuxjZtBFOOHYOBStX8cSU4=,tag:DiQgufC/jAlQ89dbOYYqzw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:C27AzpLMDiNbid0l3WVM6HToGbQQW4SlP4Q=,iv:2TjRODIMrfoJxUBhyAORuHBC2POELe/Ichzm0MC4UZg=,tag:WrYobGHiBxAkRuPyI5k+NQ==,type:str]
    APP_KEY: ENC[AES256_GCM,data:SRLUHgsQ+Pnce5XGnWxfgWRMgHZ1fr2R54LHg6uiS8k=,iv:J8X9+JyS/hDXJrzS+yjHv0QxKR78UceTguO0cfP2BIE=,tag:WpmWB5v+jPidoYXtlNVUlw==,type:str]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:ezaFErXovwHFfCXXIFUThhGhfRzhDhdfncZQ/NfgmDU=,iv:PwbwISbTRq8Jj6HgZbKlNaR7czcTbBwGlcJ5ICJE/cg=,tag:6JlPCgOfmpflvfuaYftlZQ==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:KSOV5+TAq9HjHLb8dfkvlo4rAGhTTDkMTsc=,iv:JTm/qbhHh0kqAjGaiyBN8z8keB9ADGeUL01qiRzAumo=,tag:oqmwDy96IfflwpI/JWHVZg==,type:str]
    MAIL_USERNAME: null
    MAIL_PASSWORD: null
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:63bG1g==,iv:LkJfjKAVimRGGGPU9/hJsYTPROVGiETgRb5KKERwo20=,tag:m4xqvk+80slEihWJEMd7ZQ==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T23:21:04Z"
    mac: ENC[AES256_GCM,data:Lu+1yZOWlxG9CdJaTB1bZUDjVT4GyauDID4UUBQY5R/uoH6v8mnDYJ6eASQy9xj2YbpU5RDtknE/0GBJvtsWpwIPUmO1FQOp2FgAezhIzurw/JPLYXrsynMq5cVnLdbfNMlO5jcMJeTmj9TZAWmepwkuCts5JbTjh0y5qv6jXiM=,iv:HZCIRIHPGluoQZg9rSAEK7uDbbtrVJSWATHktM2a+TA=,tag:K2y4LoGL1GuA2AbhLDpcyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-importer-secret
stringData:
    #ENC[AES256_GCM,data:aGzarl2dmPsauljv,iv:JzptTe9mDFU26JVaIxzDbfrlT6g7m073GdFvnHk6GKU=,tag:4WuW6gMBRD66k9ENLwJF6g==,type:comment]
    FIREFLY_III_ACCESS_TOKEN: ENC[AES256_GCM,data:g78aeZNwj8YzyWP0OR8EyuFsnF+TC1YeCY1tt0igdAkwvdtyNcy0pXyYWLt3fMaluY3LPWOpKT38OzWJCt4gQ7ox448DSRxnhQQKGAg/A6EuDS3djvJYi56KZi9makSMUtpwGT22kA/Ab1Sa7sBlTgT/ZMWBZDPyKZF5ZqbHZHA+Hi6dGzCWpB0QSdO7jcMdPiHrgGlae72w1wGNHSDGUvnBc66mUKmsgzMseI2rsIi6b6H5pXAdYWuc4C40iK01E1fo5am0zcwAuSFpzGLS109mQiWct7n6mlP3do+y0z+1M0KT4TosDCw20ZuCzv2H1ItseiY3i3sgh2v50RiUmAHkL5NOAMroOyKM5VSnCGr1CEkQj6iTHrv67LXMeX2azfKOa2xmbdDQIXAxrfOlQDHzmab5kImOynYPCadWzSObokdo2YDX6kjdRle//R74pJuCQj8xJDMt0g7wYR8M/ezCoOIIWZvu4gjCE9WvYFGz2SB2c7Naqw91JjR1Yg3f783W5XTVkhrVs0smPgbs1JgxTpLnTNPyY407amI+NHkQIp8f43Jn4Zn8yq6GN4X0xUl68GjEF/92TM7dAV65+ZR1oZsZJvNcKqVbZukxQ1WZQs4z3VHC1iyFBk0xUKiRMsOu21WE3lnvN7es41y2gGb+ytQzqxlx6sezN2XrBV8DB0IHQfEnkR2M+DjkbK6kHDneUA2jZHNzmcjuShVjJ5HBmS9kHC550ZVs6v9uBUCwk7cznxa6vMyGPFoAPRo0ek3EqLC5axdX5H+rkww1H0X8dTvO0K5y2j05aKSY15MCvF6ThrfAy87i7081QbrlXww50SdRYh60P+XgKYu2sPYkqVTzEFV9Ghm+E3QaPYym57S8ESLrRIB72vOuYxj/8nS6KwTizMPUiAXSbKsTMez2DL2boaFoTcAAEdWdQIpIEvuMO7Of3CuvdIkqzfrbyYij3Ib1jXcBV3h7b5rY7D8DChLdwY3XVFKm76MV3pRJ7Sk6EuRWKUWyBAnEGGaK3TKpDZOup3sjaPQIkKMuVUGxphToYu/F+Pz7DRlDi2VJCdVs+fSm43wnkDaHxw5FmhSB3tWhYauHZHk4FjKxkHEdEVeJEcH7jjIVrpXcRt6MBcFbCsPoBg2IgJ2N04Ua5Kuhq7rtc5xAT8/sDgojNCjSluFlQbncn8nT/j5up/Q86unurX7w1Y99Vuq2jq7j0q43gp8fAEqqgb4u0P1np5ILE6uRUQeaL5J1X28HcfA88F4eOdw3skztlDKwAu17pDtLm9DlN6LA1KUzOMUdOhzxO5JKaZY=,iv:APBkbCdfrv8VDlWwElfuOXgWe8WE6qG67lBzzbLXyq0=,tag:YABqmvTucC7gJECt1cB3BA==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T23:21:04Z"
    mac: ENC[AES256_GCM,data:Lu+1yZOWlxG9CdJaTB1bZUDjVT4GyauDID4UUBQY5R/uoH6v8mnDYJ6eASQy9xj2YbpU5RDtknE/0GBJvtsWpwIPUmO1FQOp2FgAezhIzurw/JPLYXrsynMq5cVnLdbfNMlO5jcMJeTmj9TZAWmepwkuCts5JbTjh0y5qv6jXiM=,iv:HZCIRIHPGluoQZg9rSAEK7uDbbtrVJSWATHktM2a+TA=,tag:K2y4LoGL1GuA2AbhLDpcyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:TLn+jq9biNfmghep1NiMFA==,iv:2y4+xs0WbaCIBvNnNaknEZ45TSzpiqrjMeYnHRwhqz4=,tag:yO9JPpG8Za+Fy9AIBc/lgA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:ZwhB1Ue8ioUfExhED6h8VJvtdg26oR8BK2/h8V9GGgw40TDvkfS3XgA0nRKph7h0H/xWMpdnqJ4=,iv:Ouqi25uAUo6ZJV5GjSrYYeS9zr7NQc9pzm4WUyaZhRc=,tag:/bH1TBP6jKAEvC8IYFDEtA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:VanSEgfPNF0fD55ijR8BTg==,iv:MKO7jXHRuwzsZ6vwk9XiBqwhpz7Q4pff0irbUS6qC/w=,tag:KKqTW265UvbEElFcya+hhg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:vciCqyjWW2d1Ol89GdNtXpvzt/knpQJhzRXW3SFp6MtDKuTT,iv:O0UwjzrMrZySShUONBhn6rN4jyHbRHuhLFf3d9JhwgQ=,tag:Vxk2UrslWVZ4HyDTNi+MlQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pFwxhGOwHKAu2xIyBftXJX/vVh2j2ZP9LA==,iv:yu6KuqH2ptJ+SYum+MVAdH0EYGNRDml3ZXxEivJXl58=,tag:IrJxPc2sWt01Y3ZRZdlmUg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T23:21:04Z"
    mac: ENC[AES256_GCM,data:Lu+1yZOWlxG9CdJaTB1bZUDjVT4GyauDID4UUBQY5R/uoH6v8mnDYJ6eASQy9xj2YbpU5RDtknE/0GBJvtsWpwIPUmO1FQOp2FgAezhIzurw/JPLYXrsynMq5cVnLdbfNMlO5jcMJeTmj9TZAWmepwkuCts5JbTjh0y5qv6jXiM=,iv:HZCIRIHPGluoQZg9rSAEK7uDbbtrVJSWATHktM2a+TA=,tag:K2y4LoGL1GuA2AbhLDpcyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
