apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-secret
stringData:
    #ENC[AES256_GCM,data:aGzarl2dmPsauljv,iv:JzptTe9mDFU26JVaIxzDbfrlT6g7m073GdFvnHk6GKU=,tag:4WuW6gMBRD66k9ENLwJF6g==,type:comment]
    DB_USERNAME: ENC[AES256_GCM,data:t5+j0GFoF9kBvWg=,iv:ckYHY7JLnemhA893sCbcCKuxjZtBFOOHYOBStX8cSU4=,tag:DiQgufC/jAlQ89dbOYYqzw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:C27AzpLMDiNbid0l3WVM6HToGbQQW4SlP4Q=,iv:2TjRODIMrfoJxUBhyAORuHBC2POELe/Ichzm0MC4UZg=,tag:WrYobGHiBxAkRuPyI5k+NQ==,type:str]
    APP_KEY: ENC[AES256_GCM,data:SRLUHgsQ+Pnce5XGnWxfgWRMgHZ1fr2R54LHg6uiS8k=,iv:J8X9+JyS/hDXJrzS+yjHv0QxKR78UceTguO0cfP2BIE=,tag:WpmWB5v+jPidoYXtlNVUlw==,type:str]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:ezaFErXovwHFfCXXIFUThhGhfRzhDhdfncZQ/NfgmDU=,iv:PwbwISbTRq8Jj6HgZbKlNaR7czcTbBwGlcJ5ICJE/cg=,tag:6JlPCgOfmpflvfuaYftlZQ==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:KSOV5+TAq9HjHLb8dfkvlo4rAGhTTDkMTsc=,iv:JTm/qbhHh0kqAjGaiyBN8z8keB9ADGeUL01qiRzAumo=,tag:oqmwDy96IfflwpI/JWHVZg==,type:str]
    MAIL_USERNAME: null
    MAIL_PASSWORD: null
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:63bG1g==,iv:LkJfjKAVimRGGGPU9/hJsYTPROVGiETgRb5KKERwo20=,tag:m4xqvk+80slEihWJEMd7ZQ==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T23:14:22Z"
    mac: ENC[AES256_GCM,data:Dc+CiDu5CSpdQsztsR/I67OaN6o/dLQhtjeqQe8KM9cOanK2iAllzWUQ9/W/VSsESw0/dwlZuTxgqvUoMkHUOlKJsKOL2BCLYl991gpPV5cgUgblZa6zwGZrSpaKLKRrhwGF7yRDNGTYwcz+tnk+kWKAn+xzxwEJzeH/qmPq3W0=,iv:oxCjtqnmnqvGrdhiXYPmYVWgEh4qMbEh0PL6bmHvhRU=,tag:R/9J3mjGSLoMovNXoLyPng==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-importer-secret
stringData:
    #ENC[AES256_GCM,data:aGzarl2dmPsauljv,iv:JzptTe9mDFU26JVaIxzDbfrlT6g7m073GdFvnHk6GKU=,tag:4WuW6gMBRD66k9ENLwJF6g==,type:comment]
    FIREFLY_III_ACCESS_KEY: ENC[AES256_GCM,data:jSz//Vcwlz+0LpvQW+r0+vcOA52LitSgFSxWo1tnLNJd3sbyDa6zIbkxtMYG6BsS++XoQBkUm1Yf7r6M+EGAc9lkqDsjTmscrisGPcLPm2DUl47iBOtLvX4A6vAe6zdQaUd+TLonxUmr36X4Ecb0CcjbaPEtaGljWWli+EpxHapfGDBkjeo61Rclk702lNQYd3cvwM5iKTCjOSM4dWCaLW0GsigNHnQDewDywroQZCRiJwsQkYceer32FrJWkoEPTgDQ8fEvnZxBxYND712oOUDEi2rzRo1WluhGbFYo0BJL64hTk+wxaNRXaYfohr5AEaontiuI5sg3pZKeh72/sHp2/iggiNzfRsmjbnx41LJgDyDcJNruY/W9PraN/PebD9oLgOR6E7aRzp0FUB7lJDVIPYyYUsCHbOvQ2WqyXmKb8A1BTZto/ZhOWRUoOBVOBR0mLj2ePEdekkhR3YY/RMGoyV/CtPZU6wyLfWZS/sr/o2IstJwv8KAaTtbju0iMqTG4Gz0L0Nnvkz31Iign/7DhwAGprdy06GKk2ApXrLheQ7oNrHTZtU0FC2IW+xzP9Qlgc3DP8gkgDbn5dND4s6zGEHmh5H5xZX+ZAhC+TW41ZD4UdsscBgrJDKMNRJuY2/fOVjHlfeJjg+z3owbPVb74u2mjsjzCDI0/M0C01mDSNcKUssoapsMT1UUE16IE9NR43elabyrAT/9OP4H/SEOCbDr2YDuycbI2p9uAKAjlORDJeKQaJmftqBVrhR24qskqW7FKo4d3YAG8Sg5Y+FqpfDBGBqItABXsYHkpVIshFPY1ahpDY2BIp9jtYZSbxSwZNFyPU38ztYC9kLA6hmx15YOGjxbCYM+YV6Zib8VS3IFP5wQ2ijGyZR5hYWvmKatYae3ST6tUSTj5DQtuz76XCv7CAy6QPfzIMbdtzbqRIaykkrLkME/wwrqL38O9p+krMYdRjdzLm6XduedMpty2arfeuIGn8kyFZARoYlsFiJE7nRW8envytnq7eCmBfnYt+sy79IZtO9Jx3ix2zUuiTROaKL3ScvZ+MaDq1H7II44lvkmt9Otui4kRRHQa8U7fif63N6t7O+2b6lapsrWjK25pXXuwwrLB1lIN5++PaBBuymOLJRBW7mJStYZC5i239uEG0V/Pggb+IDhNnuSV9pQpXNpUVwZJic4mU5jTqWTTr/LvU2RTwa1d07d+9lxAJ9HemLIbwR86sSQBEk2jtCig2AWTeo+5rZd0UppLDtHBEDowMNFGUWeq3+qzUdT1Tl2pN6DUscVn8IN3rKohQOM5uT0=,iv:bviSrVJ3ZldF2Gq92WUChvZJvMyYB3kkWTJdLIlANYM=,tag:0AQ35EK82j50Hau7ufJltA==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T23:14:22Z"
    mac: ENC[AES256_GCM,data:Dc+CiDu5CSpdQsztsR/I67OaN6o/dLQhtjeqQe8KM9cOanK2iAllzWUQ9/W/VSsESw0/dwlZuTxgqvUoMkHUOlKJsKOL2BCLYl991gpPV5cgUgblZa6zwGZrSpaKLKRrhwGF7yRDNGTYwcz+tnk+kWKAn+xzxwEJzeH/qmPq3W0=,iv:oxCjtqnmnqvGrdhiXYPmYVWgEh4qMbEh0PL6bmHvhRU=,tag:R/9J3mjGSLoMovNXoLyPng==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:TLn+jq9biNfmghep1NiMFA==,iv:2y4+xs0WbaCIBvNnNaknEZ45TSzpiqrjMeYnHRwhqz4=,tag:yO9JPpG8Za+Fy9AIBc/lgA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:ZwhB1Ue8ioUfExhED6h8VJvtdg26oR8BK2/h8V9GGgw40TDvkfS3XgA0nRKph7h0H/xWMpdnqJ4=,iv:Ouqi25uAUo6ZJV5GjSrYYeS9zr7NQc9pzm4WUyaZhRc=,tag:/bH1TBP6jKAEvC8IYFDEtA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:VanSEgfPNF0fD55ijR8BTg==,iv:MKO7jXHRuwzsZ6vwk9XiBqwhpz7Q4pff0irbUS6qC/w=,tag:KKqTW265UvbEElFcya+hhg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:vciCqyjWW2d1Ol89GdNtXpvzt/knpQJhzRXW3SFp6MtDKuTT,iv:O0UwjzrMrZySShUONBhn6rN4jyHbRHuhLFf3d9JhwgQ=,tag:Vxk2UrslWVZ4HyDTNi+MlQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pFwxhGOwHKAu2xIyBftXJX/vVh2j2ZP9LA==,iv:yu6KuqH2ptJ+SYum+MVAdH0EYGNRDml3ZXxEivJXl58=,tag:IrJxPc2sWt01Y3ZRZdlmUg==,type:str]
sops:
    age:
        - recipient: age1m69dr9zpyj8ma7fd9ym86qnp56378rmrdc9hxek664jh2w4q9s3qd7sha2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeHN3MEw5RXkra2lBekM4
            MW5sK1N6dndrV2FOdEs5WVBqem16RnY5bTBFCjViQlZRVGV1aVBDUlZ1c1ZFKzdu
            Vmc4cFk4bms5TDIyKzNWeUNWWEZaOGMKLS0tIC95S0drbzVNaEZiQTVXL1RmbGtP
            SWd4MXdwbkFYSm12YVc0T2RiUjJGbjQKVbbgf8K+dPTFRe5vRFRS4jm/U5lELkgA
            gfNUvO66AWc/Yc3WvzYpqp1zkKCi9lD3c9CIoH+q83jc24bfDv9bfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T23:14:22Z"
    mac: ENC[AES256_GCM,data:Dc+CiDu5CSpdQsztsR/I67OaN6o/dLQhtjeqQe8KM9cOanK2iAllzWUQ9/W/VSsESw0/dwlZuTxgqvUoMkHUOlKJsKOL2BCLYl991gpPV5cgUgblZa6zwGZrSpaKLKRrhwGF7yRDNGTYwcz+tnk+kWKAn+xzxwEJzeH/qmPq3W0=,iv:oxCjtqnmnqvGrdhiXYPmYVWgEh4qMbEh0PL6bmHvhRU=,tag:R/9J3mjGSLoMovNXoLyPng==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
