apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-secret
stringData:
    #ENC[AES256_GCM,data:uUCrBN5fqgTbdAkq,iv:+9evFQs4EkrrgH0tste2RsKWdsSdwHGDXOjqr0sJaik=,tag:cRUYqF60PsU1E99g+7x9xA==,type:comment]
    DB_USERNAME: ENC[AES256_GCM,data:GMCIUmtGwzyzSzU=,iv:5cMMq61oHRpVFVKvCgQfQNHrFJoWNVKY/O8AaItMYtE=,tag:DwsS9DYAeRHjvnx5KC5bfQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:XxLwhfiAiG1rhne6yHh2H32xwKjB34bzseA=,iv:nrDk/J+/luX1wKc8wuEc+PQZ2FaKbDr+HktHrWTqIlA=,tag:6M4H0eEOnRpua24L27p8Cg==,type:str]
    APP_KEY: ENC[AES256_GCM,data:tkP612IFS66UPaAAZNaP0KCS7raAK46GR0wEMYTyOvQ=,iv:90U+fu9lgLGP08swu3yebdTzGR54B9cJ0kD3ioM9tsg=,tag:RoxU4765q7IE52ej2CFpGQ==,type:str]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:i/BPnsZn4iMe40yl89oaACHHyfJl18Gu9BMrQ66RrTo=,iv:80BH+y0BaN1eYTrEYo0gvJZhpADM8+TR0xpjv9/rOlU=,tag:bkCdRj7VQqxVzUayTuZyjg==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:zJHipA0pBzMHjA4F3wbvNDW8GcrubpYfCIY=,iv:J4S2Q29JoU4gcWeRmu5f8cqKTIaSTA954OcdUAc9zF0=,tag:ZElWW9z6gjDVZNJGC85mrw==,type:str]
    MAIL_USERNAME: null
    MAIL_PASSWORD: null
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:XVbnLg==,iv:O2tXX3ltCrpFgDTgWff/ud86Ux2lc5Ex7q/KQ4q7T4Q=,tag:MNDYr1PPurLo8XUwkDm1Vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T15:34:47Z"
    mac: ENC[AES256_GCM,data:0XJIAoME2capduKCk/N/AEI9MVmbexOgx0B9QvbGoCg6ZwvoAnEAzh1HFtTDcLdOB6iD287LCj2cO+2aHfo/QnyGl1XOQJoK3XO6PDpwyBZ+0b51QhibspzU5eYyAhahqvrbTDfnpDFVvkMktWJOYZOwfFyxUlMi4f5c4xCzJLI=,iv:+OjeAg8kG5lSwa+3q9y+KutksSS0qjz+ehVIUMiRiM8=,tag:/E2JpJ20Cb4WmsFbVtSTug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:6x9M7HRejzT4/8L9glsELA==,iv:+dS31tboaM5IKwJVDaTmlR6e1eexTQzYd2Tk5UMcklE=,tag:Ff+ydVHwpHdSRPdK2wuJxg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:1gwD9ccK3YRyZFpJ4xgcZdxpMd+wcddxXQqfRvJVWVNc1NLSpMkRXveMFp7CgmmNPGtFZ1BnM48=,iv:csZPrDu79LhUq4zO64pKFUPkd8MoM9xF/85/krnPg0c=,tag:TVc/HKRKRhqdqIoB4wY8bQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:HHpxJ0J7xklPMorKRXF01Q==,iv:xdjreJbwzzhKFPPGDJ5P4x4WBnXC72j0gF4PD/RzPqo=,tag:sWc/h8T4IrpWBiqnz4/eDQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:PrI5tu8aGdoh+2k0cJEHLhx/eIYUqjvKpLmx2LgcP98Couct,iv:u8cBrSkieHcmVdbvF5nIKUft5yu6b9cRrRpUVuejdzw=,tag:144Hp4P15a0OzrslemkNvg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:/CkHY6zTAG75ivkV/pm0ONMvY0u35u9jMA==,iv:td9wNNe136PrYZNiHuOsG8usU14D25hmEikZ06poZD8=,tag:q+HVuy1joNEE5TAbrTv0fQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T15:34:47Z"
    mac: ENC[AES256_GCM,data:0XJIAoME2capduKCk/N/AEI9MVmbexOgx0B9QvbGoCg6ZwvoAnEAzh1HFtTDcLdOB6iD287LCj2cO+2aHfo/QnyGl1XOQJoK3XO6PDpwyBZ+0b51QhibspzU5eYyAhahqvrbTDfnpDFVvkMktWJOYZOwfFyxUlMi4f5c4xCzJLI=,iv:+OjeAg8kG5lSwa+3q9y+KutksSS0qjz+ehVIUMiRiM8=,tag:/E2JpJ20Cb4WmsFbVtSTug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
