---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rook-ceph
  namespace: flux-system
spec:
  targetNamespace: rook-ceph
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/rook-ceph/rook-ceph/app
  dependsOn:
    - name: snapshot-controller
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  prune: false # never should be deleted
  wait: false
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rook-ceph-cluster
  namespace: flux-system
spec:
  targetNamespace: rook-ceph
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/rook-ceph/rook-ceph/cluster
  dependsOn:
    - name: rook-ceph
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  prune: false # never should be deleted
  wait: false
  interval: 30m
  retryInterval: 2m
  timeout: 15m
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: rook
      GATUS_GROUP: infrastructure
