apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-dashboard-password
    namespace: rook-ceph
stringData:
    password: ENC[AES256_GCM,data:av/hQNxbFKr2ylEorChne1qwrBujt3HF,iv:vbkg9e6tx+bnRgIqUbOhu9Plhzu1En0CsgfKLgzoJt8=,tag:qiDJL3bozbJmP8Kcvy7h4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8yx4amydmu5npe8c7vrz077hzywactfdg9wll7j2rhd05qwyeeq5mcm49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVElGOXRvbDhiWWt4cUJD
            dGptZTRrUzVCdnFTVHZnNzJOVDJrRjdGcVh3CjF5aHJnMGJibXE4VEhYZlZKVHBD
            K1BZd2V6RUd0eGFNK0N1WlF4cmY5ZHcKLS0tIEgxVU15WHI1OW5yM0c2L1Iyd0Za
            L21jNXFsbFZoY25VNnIyaHBmYklVbTQKjIlzQ8kWDC9OED7lH+sLeRaIXyQGPwp4
            Iie/KK/XEa/p6410iSkwWjoleIusyxeI0WTsjcwKEHyo/XxQ26Jfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T12:14:03Z"
    mac: ENC[AES256_GCM,data:fkQXf9B0dGUOQm+ecqI6y0+7csk19s2znnTxFfmg2O822h6ybiLbNA5QsacFfC8z85HJYoTdy1RIq1mlJcSJDV8Y90VmqP8NR34Hozarm0CX+xo8WNDDqt5s20NtwuIUynD/iyXFj+kgxceP+PBeWmRSN9qmbvyTuaAAjp0j7hE=,iv:PIXzYbolKo14lvovx1L/syMlMqimeI9Lk4nS6jLfuI8=,tag:mMf8I/17Un86SK3DPXtLUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
